from .common import item as i

CH = "API အခြေခံ"


def samples():
    return [
        i("concept_qa", "API ဆိုတာ ဘာလဲ?",
          "API ဆိုတာ ပရိုဂရမ်နှစ်ခု စကားပြောတဲ့ စည်းကမ်း ဖြစ်ပါတယ်။\n\nမိုဘိုင်းအက်ပ်က server ဆီ data တောင်းနိုင်ပါတယ်။ JSON နဲ့ ပြန်တတ်ပါတယ်။\n\nဥပမာ ရာသီဥတု API က အပူချိန် ပေးပါတယ်။",
          ["API"], CH),
        i("concept_qa", "REST API ဆိုတာ ဘာလဲ?",
          "REST API က HTTP method နဲ့ resource ကို ကိုင်တဲ့ ပုံစံ ဖြစ်ပါတယ်။\n\nGET က ဖတ်၊ POST က ဖန်တီး၊ PUT/PATCH က ပြင်၊ DELETE က ဖျက်ပါတယ်။ URL က ရှင်းသင့်ပါတယ်။\n\n/users/1 က user တစ်ယောက် ဖြစ်ပါတယ်။",
          ["REST", "API"], CH),
        i("concept_qa", "HTTP status code 200 နဲ့ 404 ဘာကွာလဲ?",
          "200 က အောင်မြင်ပြီး 404 က မတွေ့ကြောင်း ပြပါတယ်။\n\nclient က ဒီဂဏန်းကို ကြည့်ပြီး ဘာလုပ်မလဲ ဆုံးဖြတ်ပါတယ်။ 500 က server အမှား ဖြစ်ပါတယ်။\n\nမှန်ကန်တဲ့ code ပေးမှ UI မှန်ပါတယ်။",
          ["HTTP"], CH),
        i("concept_qa", "Endpoint ဆိုတာ ဘာလဲ?",
          "Endpoint က API ရဲ့ တိကျတဲ့ လိပ်စာ ဖြစ်ပါတယ်။\n\nmethod နဲ့ path ပေါင်းပါတယ်။ GET /api/posts က ပို့စ်စာရင်း ဖြစ်နိုင်ပါတယ်။\n\nစာရွက်စာတမ်းမှာ ရှင်းအောင် ရေးရပါတယ်။",
          ["endpoint", "API"], CH),
        i("concept_qa", "Authentication နဲ့ authorization ဘာကွာလဲ?",
          "Authentication က ဘယ်သူလဲ သက်သေပြခြင်း၊ authorization က ဘာလုပ်ခွင့်ရှိလဲ ဆိုတာ ဖြစ်ပါတယ်။\n\nlogin ပြီးမှတောင် ပြင်ခွင့် မရှိနိုင်ပါ။ token နဲ့ role သုံးတတ်ပါတယ်။\n\nနှစ်ခုလုံး လိုအပ်ပါတယ်။",
          ["API"], CH),
        i("concept_qa", "JSON API body ဆိုတာ ဘာလဲ?",
          "Body က request/response ထဲက data အဓိက ဖြစ်ပါတယ်။\n\nJSON object နဲ့ ပို့တတ်ပါတယ်။ Content-Type ကို application/json ပေးရပါတယ်။\n\n{ \"title\": \"Hello\" } လို ပုံစံ ရှိပါတယ်။",
          ["JSON", "API"], CH),
        i("concept_qa", "Idempotent ဆိုတာ ဘာလဲ?",
          "Idempotent က တူညီတဲ့ request ကို ခါများများ ပို့လည်း ရလဒ်တူခြင်း ဖြစ်ပါတယ်။\n\nGET နဲ့ PUT က အများအားဖြင့် ဒီလို ဖြစ်သင့်ပါတယ်။ POST က အသစ်ထပ်ထွက်နိုင်ပါတယ်။\n\nကွန်ရက်ပြတ်ပြီး ပြန်ပို့ရင် အရေးကြီးပါတယ်။",
          ["HTTP"], CH),
        i("explain_code", "ဒီ GET fetch ကို ရှင်းပြပါ။",
          "ဒီ code က ပို့စ်စာရင်းကို ယူပါတယ်။\n\nGET က ဖတ်ရုံ ဖြစ်ပါတယ်။ json() က body ကို object ပြောင်းပါတယ်။\n\nစာရင်းကို console မှာ မြင်ပါတယ်။",
          ["GET", "API"], CH,
          "const res = await fetch(\"/api/posts\");\nconst posts = await res.json();"),
        i("explain_code", "ဒီ POST fetch ကို ရှင်းပြပါ။",
          "ဒီ code က ပို့စ်အသစ် တင်ပါတယ်။\n\nmethod POST ဖြစ်ပါတယ်။ headers က JSON ဖြစ်ကြောင်း ပြပါတယ်။ body က ခေါင်းစဉ် ဖြစ်ပါတယ်။\n\nserver က ပို့စ်အသစ် သိမ်းပါတယ်။",
          ["POST", "JSON"], CH,
          "await fetch(\"/api/posts\", {\n  method: \"POST\",\n  headers: { \"Content-Type\": \"application/json\" },\n  body: JSON.stringify({ title: \"Hello\" })\n});"),
        i("explain_code", "ဒီ Authorization header ကို ရှင်းပြပါ။",
          "ဒီ request က token နဲ့ ကိုယ်ဘယ်သူလဲ ပြပါတယ်။\n\nBearer က token ပို့တဲ့ ပုံစံ ဖြစ်ပါတယ်။ မပါရင် 401 ဖြစ်နိုင်ပါတယ်။\n\nကာကွယ်ထားတဲ့ endpoint ကို ဖွင့်နိုင်ပါတယ်။",
          ["HTTP", "API"], CH,
          "fetch(\"/api/me\", {\n  headers: { Authorization: \"Bearer \" + token }\n});"),
        i("explain_code", "ဒီ status check ကို ရှင်းပြပါ။",
          "ဒီ code က အောင်မှ data ဖတ်ပါတယ်။\n\nok မဟုတ်ရင် error ပစ်ပါတယ်။ 404 ကို အောင်တယ်လို့ မမှတ်ပါ။\n\nUI မှာ မှန်အောင် ပြနိုင်ပါတယ်။",
          ["HTTP"], CH,
          "const res = await fetch(\"/api/posts/1\");\nif (!res.ok) {\n  throw new Error(\"Request failed\");\n}\nconst post = await res.json();"),
        i("explain_code", "ဒီ query string ကို ရှင်းပြပါ။",
          "ဒီ URL က ရှာဖွေစကားလုံး q ကို ပို့ပါတယ်။\n\nGET မှာ filter ကို လိပ်စာမှာ တပ်ပါတယ်။ server က cat နဲ့ စစ်ပါတယ်။\n\nရလဒ်စာရင်း ကျဉ်းပါတယ်။",
          ["GET", "endpoint"], CH,
          "fetch(\"/api/posts?q=cat\");"),
        i("explain_code", "ဒီ PUT update ကို ရှင်းပြပါ။",
          "ဒီ request က id 4 ကို အပြည့် ပြင်ပါတယ်။\n\nPUT က resource တစ်ခုလုံး အစားထိုးတတ်ပါတယ်။ title အသစ် တင်ပါတယ်။\n\nနောက် GET မှာ Hello 2 တွေ့ရပါမယ်။",
          ["HTTP", "API"], CH,
          "fetch(\"/api/posts/4\", {\n  method: \"PUT\",\n  headers: { \"Content-Type\": \"application/json\" },\n  body: JSON.stringify({ title: \"Hello 2\" })\n});"),
        i("explain_code", "ဒီ DELETE ကို ရှင်းပြပါ။",
          "ဒီ request က id 4 ကို ဖျက်ပါတယ်။\n\nDELETE method ဖြစ်ပါတယ်။ အောင်ရင် 204 သို့မဟုတ် 200 ရနိုင်ပါတယ်။\n\nစာရင်းက ပျောက်ပါတယ်။",
          ["HTTP"], CH,
          "fetch(\"/api/posts/4\", { method: \"DELETE\" });"),
        i("debug_explain", "ဒီ GET နဲ့ body ပို့တာကို ပြင်ပါ။",
          "GET မှာ body မပို့သင့်ပါ။ ရှာဖွေမှုကို query string သုံးပါ။\n\nမှန်ကန်သော code:\nfetch(\"/api/posts?q=cat\");",
          ["GET", "API"], CH,
          "fetch(\"/api/posts\", {\n  method: \"GET\",\n  body: JSON.stringify({ q: \"cat\" })\n});"),
        i("debug_explain", "ဒီ Content-Type ပျောက်တာကို ပြင်ပါ။",
          "JSON ပို့ပေမယ့် header မပါရင် server က နားမလည်နိုင်ပါ။\n\nContent-Type ထည့်ပါ။\n\nမှန်ကန်သော code:\nfetch(\"/api/posts\", {\n  method: \"POST\",\n  headers: { \"Content-Type\": \"application/json\" },\n  body: JSON.stringify({ title: \"Hi\" })\n});",
          ["JSON", "POST"], CH,
          "fetch(\"/api/posts\", {\n  method: \"POST\",\n  body: JSON.stringify({ title: \"Hi\" })\n});"),
        i("concept_qa", "Rate limiting ဆိုတာ ဘာလဲ?",
          "Rate limiting က တစ်ချိန်အတွင်း ခေါ်ခွင့် အရေအတွက် ကန့်သတ်ခြင်း ဖြစ်ပါတယ်။\n\nအလွန်အကျွံ သုံးတာကို တားပါတယ်။ 429 status ရနိုင်ပါတယ်။\n\nAPI ကို တည်ငြိမ်စေပါတယ်။",
          ["API"], CH),
        i("concept_qa", "Pagination ဆိုတာ ဘာလဲ?",
          "Pagination က ရလဒ်ကို စာမျက်နှာခွဲခြင်း ဖြစ်ပါတယ်။\n\npage နဲ့ limit ပို့တတ်ပါတယ်။ တစ်ခါတည်း အကုန်မယူသင့်ပါ။\n\nစာရင်းရှည်ရင် မြန်ပါတယ်။",
          ["API"], CH),
        i("explain_code", "ဒီ page query ကို ရှင်းပြပါ။",
          "ဒီ request က ဒုတိယမျက်နှာ၊ ၁၀ ခုယူပါတယ်။\n\npage=2 နဲ့ limit=10 က ခွဲပေးပါတယ်။ server က ၁၁ ကနေ ၂၀ ပြန်နိုင်ပါတယ်။\n\nနောက်မျက်နှာ ခလုတ်အတွက် သုံးပါတယ်။",
          ["GET"], CH,
          "fetch(\"/api/posts?page=2&limit=10\");"),
        i("concept_qa", "CORS ဆိုတာ ဘာလဲ?",
          "CORS က ဘရောက်ဇာက အခြား domain က API ခေါ်ခွင့်ကို ထိန်းခြင်း ဖြစ်ပါတယ်။\n\nserver က ခွင့်ပြု header မပို့ရင် ဖွင့်မရပါ။ frontend နဲ့ API domain မတူရင် တွေ့ရပါတယ်။\n\nဖွံ့ဖြိုးချိန်မှာ သတိထားရပါတယ်။",
          ["API"], CH),
        i("concept_qa", "Webhook ဆိုတာ ဘာလဲ?",
          "Webhook က အဖြစ်အပျက်ဖြစ်ရင် ကျွန်တော်တို့ဆီ POST ပြန်ပို့ခြင်း ဖြစ်ပါတယ်။\n\nငါတို့က မေးစရာမလိုပါ။ ငွေပေးချေမှု ပြီးကြောင်း လာနိုင်ပါတယ်။\n\nလက်မှတ်စစ်ပြီးမှ ယုံသင့်ပါတယ်။",
          ["API", "POST"], CH),
        i("explain_code", "ဒီ 201 response ကို ရှင်းပြပါ။",
          "ဒီ server က အသစ်ဖန်တီးအောင်မြင်ကြောင်း 201 ပေးပါတယ်။\n\njson က ပို့စ်အသစ် ပြန်ပေးပါတယ်။ client က id ယူနိုင်ပါတယ်။\n\n200 ထက် ဖန်တီးမှုကို ပိုတိကျစွာ ပြပါတယ်။",
          ["HTTP", "JSON"], CH,
          "return response()->json($post, 201);"),
        i("explain_code", "ဒီ 422 validation ကို ရှင်းပြပါ။",
          "ဒီ response က title မမှန်ကြောင်း ပြပါတယ်။\n\n422 က ဖောင်အမှား ဖြစ်ပါတယ်။ errors object ထဲမှာ field အလိုက် စာ ရှိပါတယ်။\n\nUI က title အောက်မှာ ပြနိုင်ပါတယ်။",
          ["HTTP", "form"], CH,
          "return response()->json([\n  'errors' => ['title' => ['Title is required']]\n], 422);"),
        i("concept_qa", "Versioning API ဘာကြောင့် လုပ်သလဲ?",
          "ဟောင်းတဲ့ app တွေ မပျက်အောင် ပုံစံအသစ်ကို /v2 လို ခွဲပါတယ်။\n\nတစ်ခါတည်း ဖြိုရင် client အကုန် ကျနိုင်ပါတယ်။ စာရွက်စာတမ်းမှာ ရှင်းပြရပါတယ်။\n\nဖြည်းဖြည်း ပြောင်းနိုင်ပါတယ်။",
          ["API"], CH),
        i("explain_code", "ဒီ v1 path ကို ရှင်းပြပါ။",
          "ဒီ endpoint က ဗားရှင်း ၁ ရဲ့ users ဖြစ်ပါတယ်။\n\n/api/v1 က အဟောင်းကို ထိန်းပါတယ်။ အသစ်ကို v2 မှာ ထည့်နိုင်ပါတယ်။\n\nclient က ဘယ်ဗားရှင်းသုံးလဲ ရွေးနိုင်ပါတယ်။",
          ["endpoint"], CH,
          "GET /api/v1/users"),
        i("debug_explain", "ဒီ 401 ကို ဘယ်လို နားလည်မလဲ?",
          "token မပါ သို့မဟုတ် မှားလို့ 401 တက်ပါတယ်။\n\nAuthorization header ထည့်ပါ။\n\nမှန်ကန်သော code:\nfetch(\"/api/me\", {\n  headers: { Authorization: \"Bearer \" + token }\n});",
          ["HTTP", "API"], CH,
          "fetch(\"/api/me\");"),
        i("concept_qa", "Cache header က ဘာအကျိုးရှိလဲ?",
          "Cache က မပြောင်းသေးတဲ့ data ကို ပြန်မခေါ်အောင် ကူပါတယ်။\n\nETag သို့မဟုတ် Cache-Control သုံးပါတယ်။ server ဝန် လျော့ပါတယ်။\n\nသတင်းအသစ်လို ချက်ချင်းပြောင်းရင် ကန့်သတ်သင့်ပါတယ်။",
          ["HTTP"], CH),
        i("concept_qa", "OpenAPI / Swagger က ဘာလဲ?",
          "OpenAPI က API ကို စာရွက်စာတမ်း စံပုံစံနဲ့ ရေးခြင်း ဖြစ်ပါတယ်။\n\nendpoint၊ body၊ status တွေ ရှင်းပါတယ်။ ကိရိယာက client code ထုတ်နိုင်ပါတယ်။\n\nအဖွဲ့လိုက် နားလည်မှု တူစေပါတယ်။",
          ["API"], CH),
        i("explain_code", "ဒီ PATCH ကို ရှင်းပြပါ။",
          "ဒီ request က title ပဲ ပြင်ပါတယ်။\n\nPATCH က တစ်စိတ်တစ်ပိုင်း ပြင်ပါတယ်။ PUT လို အကုန်မပို့ရပါ။\n\nကျန် field တွေ မပျက်ပါ။",
          ["HTTP"], CH,
          "fetch(\"/api/posts/4\", {\n  method: \"PATCH\",\n  headers: { \"Content-Type\": \"application/json\" },\n  body: JSON.stringify({ title: \"New\" })\n});"),
        i("explain_code", "ဒီ error JSON ကို ရှင်းပြပါ။",
          "ဒီ ပုံစံက အမှားကို စက်နဲ့ လူဖတ်ရအောင် ပေးပါတယ်။\n\nmessage က ရှင်းပါတယ်။ code က ပရိုဂရမ်က ခွဲခြားပါတယ်။\n\nlog မှာ လိုက်ရှာရ လွယ်ပါတယ်။",
          ["JSON"], CH,
          "{ \"error\": { \"code\": \"NOT_FOUND\", \"message\": \"Post not found\" } }"),
        i("concept_qa", "Stateless API ဆိုတာ ဘာလဲ?",
          "Stateless က server က ယခင် request ကို မမှတ်ဘဲ token နဲ့ပဲ ဆုံးဖြတ်ခြင်း ဖြစ်ပါတယ်။\n\nscale လုပ်ရ လွယ်ပါတယ်။ session မမှီခိုပါ။\n\nJWT လို token သုံးတတ်ပါတယ်။",
          ["API"], CH),
        i("explain_code", "ဒီ Accept header ကို ရှင်းပြပါ။",
          "ဒီ request က JSON ပြန်ချင်ကြောင်း ပြောပါတယ်။\n\nAccept က ဘာပုံစံလိုချင်လဲ ညွှန်ပါတယ်။ server က ကိုက်အောင် ပြန်ပါတယ်။\n\nXML မဟုတ်ဘဲ JSON ရနိုင်ပါတယ်။",
          ["HTTP"], CH,
          "fetch(\"/api/posts\", {\n  headers: { Accept: \"application/json\" }\n});"),
    ]
