from .common import item as i

CH = "Bootstrap အခြေခံ"


def samples():
    return [
        i("concept_qa", "Bootstrap ဆိုတာ ဘာလဲ?",
          "Bootstrap က ဝက်ဘ် UI ကို မြန်မြန် တည်ဆောက်တဲ့ CSS framework ဖြစ်ပါတယ်။\n\nခလုတ်၊ ဂရစ်၊ form ပုံစံတွေ အသင့်ရှိပါတယ်။ class နာမည် တပ်ရုံနဲ့ အလုပ်ဖြစ်ပါတယ်။\n\nresponsive စာမျက်နှာအတွက် အထောက်အကူ ဖြစ်ပါတယ်။",
          ["bootstrap"], CH),
        i("concept_qa", "Grid system ဆိုတာ ဘာလဲ?",
          "Grid က စာမျက်နှာကို ကော်လံ ၁၂ ခု ခွဲသုံးခြင်း ဖြစ်ပါတယ်။\n\nrow ထဲမှာ col class တွေ ထည့်ပါတယ်။ ဖုန်းနဲ့ ကွန်ပျူတာမှာ အကျယ် မတူအောင် ပြောင်းနိုင်ပါတယ်။\n\nဥပမာ col-md-6 က အလယ်အရွယ်မှာ တစ်ဝက် ယူပါတယ်။",
          ["grid"], CH),
        i("concept_qa", "Responsive design ဆိုတာ ဘာလဲ?",
          "Responsive ဆိုတာ မျက်နှာပြင်အကျယ်ပေါ်မူတည်ပြီး ပုံစံပြောင်းခြင်း ဖြစ်ပါတယ်။\n\nဖုန်းမှာ တစ်တန်း၊ ကွန်ပျူတာမှာ နှစ်တန်း ဖြစ်နိုင်ပါတယ်။ Bootstrap breakpoint က sm၊ md၊ lg ရှိပါတယ်။\n\nသုံးရ လွယ်စေပါတယ်။",
          ["responsive"], CH),
        i("concept_qa", "Container နဲ့ container-fluid ဘာကွာလဲ?",
          "container က အလယ်မှာ အကျယ်ကန့်သတ်ပါတယ်။ container-fluid က မျက်နှာပြင်အပြည့် ယူပါတယ်။\n\nစာဖတ်ရ လွယ်ချင်ရင် container သုံးတတ်ပါတယ်။\n\nbanner ကျယ်ချင်ရင် fluid သုံးပါတယ်။",
          ["bootstrap"], CH),
        i("concept_qa", "Utility class ဆိုတာ ဘာလဲ?",
          "Utility class က margin၊ padding၊ အရောင်လို အသေးအမွှားကို တပ်ရုံနဲ့ ပြင်ခြင်း ဖြစ်ပါတယ်။\n\nmt-3 က အပေါ်ဝေး၊ text-center က စာအလယ် ဖြစ်ပါတယ်။ CSS ဖိုင်အသစ် မရေးရပါ။\n\nမြန်မြန် စမ်းလို့ရပါတယ်။",
          ["bootstrap"], CH),
        i("explain_code", "ဒီ row col ကို ရှင်းပြပါ။",
          "ဒီ markup က ကော်လံနှစ်ခု တန်းစီပါတယ်။\n\nrow က ဘေးချင်းကပ်စေပါတယ်။ col က တစ်ဝက်စီ ယူနိုင်ပါတယ်။\n\nLeft နဲ့ Right ဘေးချင်း ပေါ်ပါတယ်။",
          ["grid"], CH,
          "<div class=\"row\">\n  <div class=\"col\">Left</div>\n  <div class=\"col\">Right</div>\n</div>"),
        i("explain_code", "ဒီ col-md-6 ကို ရှင်းပြပါ။",
          "ဒီကော်လံက အလယ်အရွယ်မှာ ၁၂ ထဲက ၆ ယူပါတယ်။\n\nဖုန်းမှာ အပြည့်ကျယ်နိုင်ပါတယ်။ md က breakpoint ဖြစ်ပါတယ်။\n\nနှစ်ကော်လံက ကွန်ပျူတာမှာ တန်းပါတယ်။",
          ["grid", "responsive"], CH,
          "<div class=\"col-12 col-md-6\">Content</div>"),
        i("explain_code", "ဒီ btn primary ကို ရှင်းပြပါ။",
          "ဒီ class က ခလုတ်ကို အဓိကအရောင် ပေးပါတယ်။\n\nbtn က ခလုတ်ပုံ၊ btn-primary က အပြာရောင်စံ ဖြစ်ပါတယ်။\n\nSave ခလုတ် ပေါ်လွင်ပါတယ်။",
          ["bootstrap"], CH,
          "<button class=\"btn btn-primary\">Save</button>"),
        i("explain_code", "ဒီ alert ကို ရှင်းပြပါ။",
          "ဒီ box က အောင်မြင်ကြောင်း ပြပါတယ်။\n\nalert-success က အစိမ်းရောင် သတိပေး ဖြစ်ပါတယ်။ role=alert က ဖတ်စက်အတွက် ကောင်းပါတယ်။\n\nSaved ကို သုံးသူ မြင်ပါတယ်။",
          ["bootstrap"], CH,
          "<div class=\"alert alert-success\" role=\"alert\">Saved</div>"),
        i("explain_code", "ဒီ navbar ကို ရှင်းပြပါ။",
          "ဒီ navigation က အမှတ်တံဆိပ်နဲ့ လင့် ပြပါတယ်။\n\nnavbar-expand-lg က ကျယ်ရင် ဖြန့်ပါတယ်။ container က အလယ်သွပ်ပါတယ်။\n\nHome လင့် နှိပ်လို့ရပါတယ်။",
          ["bootstrap"], CH,
          "<nav class=\"navbar navbar-expand-lg\">\n  <div class=\"container\">\n    <a class=\"navbar-brand\" href=\"/\">Shop</a>\n  </div>\n</nav>"),
        i("explain_code", "ဒီ form-control ကို ရှင်းပြပါ။",
          "ဒီ input က Bootstrap ပုံစံ ရပါတယ်။\n\nform-control က အကျယ်၊ နယ်နိမိတ် ညှိပါတယ်။ label နဲ့ တွဲသုံးသင့်ပါတယ်။\n\nအီးမေးလ်ရိုက်တဲ့ အကွက် လှပါတယ်။",
          ["form", "bootstrap"], CH,
          "<label class=\"form-label\">Email</label>\n<input class=\"form-control\" type=\"email\">"),
        i("explain_code", "ဒီ d-flex ကို ရှင်းပြပါ။",
          "ဒီ class က အတွင်းက ဟာတွေကို ဘေးချင်းစီပါတယ်။\n\nflex box ဖြစ်ပါတယ်။ gap-2 က ကြားကွာပါတယ်။\n\nခလုတ်နှစ်ခု ကပ်မနေပါ။",
          ["bootstrap"], CH,
          "<div class=\"d-flex gap-2\">\n  <button class=\"btn btn-primary\">Ok</button>\n  <button class=\"btn btn-secondary\">Cancel</button>\n</div>"),
        i("explain_code", "ဒီ mt-3 ကို ရှင်းပြပါ။",
          "ဒီ class က အပေါ်ကနေ ဝေးစေပါတယ်။\n\nmargin-top အဆင့် ၃ ဖြစ်ပါတယ်။ ခေါင်းစဉ်နဲ့ စာကြား ခြားပါတယ်။\n\nကြည့်ရ လေဝင်လေထွက် ကောင်းပါတယ်။",
          ["bootstrap"], CH,
          "<p class=\"mt-3\">Hello</p>"),
        i("explain_code", "ဒီ table ကို ရှင်းပြပါ။",
          "ဒီ table က နယ်နိမိတ်နဲ့ ကြားညှိ ပုံစံ ရပါတယ်။\n\ntable-striped က တစ်ကြောင်းခြား အရောင်ပေးပါတယ်။ ဖတ်ရ လွယ်ပါတယ်။\n\nAung ရဲ့ အတန်း ပေါ်ပါတယ်။",
          ["bootstrap"], CH,
          "<table class=\"table table-striped\">\n  <tr><td>Aung</td></tr>\n</table>"),
        i("explain_code", "ဒီ modal trigger ကို ရှင်းပြပါ။",
          "ဒီ ခလုတ်က modal ဖွင့်ပါတယ်။\n\ndata-bs-toggle နဲ့ target က Bootstrap JS ကို ခိုင်းပါတယ်။ #box ကို ဖွင့်ပါတယ်။\n\nအပိုဝင်းဒိုး ပေါ်ပါတယ်။",
          ["bootstrap"], CH,
          "<button data-bs-toggle=\"modal\" data-bs-target=\"#box\">Open</button>"),
        i("debug_explain", "ဒီ row ကို container မခြုံတာ ဘာဖြစ်နိုင်လဲ?",
          "row က အနှုတ် margin ရှိလို့ container မခြုံရင် ဘေးထွက်နိုင်ပါတယ်။\n\ncontainer ထဲ ထည့်ပါ။\n\nမှန်ကန်သော code:\n<div class=\"container\">\n  <div class=\"row\">\n    <div class=\"col\">A</div>\n  </div>\n</div>",
          ["grid"], CH,
          "<div class=\"row\">\n  <div class=\"col\">A</div>\n</div>"),
        i("debug_explain", "ဒီ col စုပေါင်း ၁၂ ကျော်တာကို ပြင်ပါ။",
          "col-8 နှစ်ခုက ၁၆ ဖြစ်လို့ ဒုတိယက နောက်တန်းကျပါတယ်။\n\n၁၂ ထဲဝင်အောင် ၆ နဲ့ ၆ ခွဲပါ။\n\nမှန်ကန်သော code:\n<div class=\"row\">\n  <div class=\"col-6\">A</div>\n  <div class=\"col-6\">B</div>\n</div>",
          ["grid"], CH,
          "<div class=\"row\">\n  <div class=\"col-8\">A</div>\n  <div class=\"col-8\">B</div>\n</div>"),
        i("concept_qa", "Breakpoint sm md lg ဆိုတာ ဘာလဲ?",
          "ဒါတွေက မျက်နှာပြင်အကျယ် အဆင့် ဖြစ်ပါတယ်။\n\nsm က ဖုန်းကျယ်၊ md က တက်ဘလက်၊ lg က ကွန်ပျူတာ နီးပါး ဖြစ်ပါတယ်။ class နာမည်မှာ တပ်ပါတယ်။\n\ncol-lg-4 က ကျယ်မှ သုံးကော်လံ ဖြစ်ပါတယ်။",
          ["responsive"], CH),
        i("explain_code", "ဒီ text-center ကို ရှင်းပြပါ။",
          "ဒီ class က စာကို အလယ်တင်ပါတယ်။\n\nခေါင်းစဉ်အတွက် သုံးတတ်ပါတယ်။ CSS မရေးရပါ။\n\nWelcome က အလယ်ရောက်ပါတယ်။",
          ["bootstrap"], CH,
          "<h1 class=\"text-center\">Welcome</h1>"),
        i("explain_code", "ဒီ img-fluid ကို ရှင်းပြပါ။",
          "ဒီ class က ပုံကို နေရာအကျယ်ထက် မကျော်အောင် ချုံ့ပါတယ်။\n\nဖုန်းမှာ ပုံမလျှံပါ။ height အလိုအလျောက် လိုက်ပါတယ်။\n\nresponsive ပုံ ဖြစ်ပါတယ်။",
          ["responsive"], CH,
          "<img class=\"img-fluid\" src=\"photo.jpg\" alt=\"Photo\">"),
        i("explain_code", "ဒီ badge ကို ရှင်းပြပါ။",
          "ဒီ span က အရေအတွက် အမှတ်တံဆိပ် ပြပါတယ်။\n\nbadge-primary က အရောင်ပေးပါတယ်။ ၃ ဆိုတဲ့ ဂဏန်း ပေါ်လွင်ပါတယ်။\n\nအသνηကြားစာ ဦးရေ ပြရာမှာ သုံးပါတယ်။",
          ["bootstrap"], CH,
          "<span class=\"badge text-bg-primary\">3</span>"),
        i("concept_qa", "Bootstrap JS plugin ဘာလုပ်သလဲ?",
          "Modal၊ dropdown၊ collapse ကို JavaScript နဲ့ ဖွင့်ပေးပါတယ်။\n\nCSS တင်မက JS ဖိုင်လည်း ထည့်ရပါတယ်။ data attribute နဲ့ ခိုင်းလို့ရပါတယ်။\n\nခလုတ်နှိပ်ရင် ဝင်းဒိုးပွင့်ပါတယ်။",
          ["bootstrap"], CH),
        i("explain_code", "ဒီ collapse ကို ရှင်းပြပါ။",
          "ဒီ ခလုတ်က အထဲက စာကို ဖွင့်ပိတ်ပါတယ်။\n\ndata-bs-toggle=collapse က ပြသမှု ပြောင်းပါတယ်။ #more ကို ချိတ်ပါတယ်။\n\nအသေးစိတ် ဖုံးထားနိုင်ပါတယ်။",
          ["bootstrap"], CH,
          "<button data-bs-toggle=\"collapse\" data-bs-target=\"#more\">More</button>"),
        i("debug_explain", "ဒီ btn class ပျောက်တာကို ပြင်ပါ။",
          "btn မပါရင် Bootstrap ခလုတ်ပုံ မရပါ။\n\nbtn နဲ့ အရောင် class တွဲပါ။\n\nမှန်ကန်သော code:\n<button class=\"btn btn-primary\">Save</button>",
          ["bootstrap"], CH,
          "<button class=\"btn-primary\">Save</button>"),
        i("concept_qa", "Gutters ဆိုတာ ဘာလဲ?",
          "Gutter က ကော်လံကြား ခြားတဲ့ နေရာ ဖြစ်ပါတယ်။\n\ng-3 လို class နဲ့ ချိန်နိုင်ပါတယ်။ ကပ်လွန်းရင် ဖတ်ရ ခက်ပါတယ်။\n\nဒီဇိုင်းကို လေဝင်လေထွက် ကောင်းစေပါတယ်။",
          ["grid"], CH),
        i("explain_code", "ဒီ g-3 ကို ရှင်းပြပါ။",
          "ဒီ row က ကော်လံကြား ခြားပါတယ်။\n\ng-3 က gutter အဆင့် ၃ ဖြစ်ပါတယ်။ A နဲ့ B မကပ်ပါ။\n\nကြည့်ရ သက်သောင့်သက်သာ ရှိပါတယ်။",
          ["grid"], CH,
          "<div class=\"row g-3\">\n  <div class=\"col\">A</div>\n  <div class=\"col\">B</div>\n</div>"),
    ]
