from .common import item as i

C = {
    1: "Chapter 1",
    3: "Chapter 3",
    4: "Chapter 4",
    6: "Chapter 6",
    8: "Chapter 8",
}


def samples():
    return [
        i("concept_qa", "Database ဆိုတာ ဘာလဲ?",
          "Database ဆိုတာ data တွေကို စနစ်တကျ သိမ်း၊ ရှာ၊ ပြင်နိုင်တဲ့ စနစ် ဖြစ်ပါတယ်။\n\nဖိုင်ထဲ ပုံမှန် သိမ်းတာထက် အများကြီးကို မြန်မြန် ရှာနိုင်ပါတယ်။ Table တွေနဲ့ ဆက်စပ် သိမ်းတတ်ပါတယ်။\n\nဥပမာ ကျောင်းသား နာမည်နဲ့ အတန်းကို database ထဲ ထည့်ထားနိုင်ပါတယ်။",
          ["database"], C[1]),
        i("concept_qa", "Relational database ဆိုတာ ဘာလဲ?",
          "Relational database ဆိုတာ table တွေကို ဆက်စပ်ပြီး သိမ်းတဲ့ database ဖြစ်ပါတယ်။\n\nတစ်ခုနဲ့တစ်ခု key နဲ့ ချိတ်ပါတယ်။ MySQL၊ PostgreSQL တို့ ပါဝင်ပါတယ်။\n\nဥပမာ students နဲ့ teachers table ကို school database ထဲမှာ ပေါင်းသုံးနိုင်ပါတယ်။",
          ["database", "table"], C[1]),
        i("concept_qa", "Table, row, column ဆိုတာ ဘာလဲ?",
          "Table က ဇယား၊ row က တစ်ကြောင်း data၊ column က တစ်မျိုးတည်းသော အချက် ဖြစ်ပါတယ်။\n\nRow တစ်ကြောင်းက ကျောင်းသား တစ်ယောက် ဖြစ်နိုင်ပါတယ်။ Column က name သို့မဟုတ် age ဖြစ်နိုင်ပါတယ်။\n\nဥပမာ Students table မှာ ID, Name, Grade ရှိနိုင်ပါတယ်။",
          ["table"], C[1]),
        i("concept_qa", "Primary key ဆိုတာ ဘာလဲ?",
          "Primary key ဆိုတာ row တစ်ကြောင်းကို တစ်ခုတည်း ခွဲခြားပေးတဲ့ column ဖြစ်ပါတယ်။\n\nထပ်နေလို့မရပါ။ ဗလာမဖြစ်ရပါ။ ရှာဖွေ ချိတ်ဆက်ရာမှာ အခြေခံ ဖြစ်ပါတယ်။\n\nဥပမာ student_id က ကျောင်းသား တစ်ယောက်ကို ကိုယ်စားပြုပါတယ်။",
          ["primary key", "table"], C[8]),
        i("concept_qa", "Foreign key ဆိုတာ ဘာလဲ?",
          "Foreign key ဆိုတာ အခြား table ရဲ့ primary key ကို ညွှန်တဲ့ column ဖြစ်ပါတယ်။\n\nဆက်စပ်မှုကို စည်းကမ်းနဲ့ ထိန်းပါတယ်။ မရှိတဲ့ id ကို ထည့်လို့မရအောင် ကာကွယ်နိုင်ပါတယ်။\n\nဥပမာ orders.customer_id က customers.id ကို ညွှန်ပါတယ်။",
          ["foreign key", "table"], C[8]),
        i("concept_qa", "SQL ဆိုတာ ဘာလဲ?",
          "SQL ဆိုတာ database ထဲက data ကို မေး၊ ထည့်၊ ပြင်၊ ဖျက်တဲ့ ဘာသာစကား ဖြစ်ပါတယ်။\n\nSELECT၊ INSERT၊ UPDATE၊ DELETE က အခြေခံ ဖြစ်ပါတယ်။ MySQL မှာ အသုံးများပါတယ်။\n\nဥပမာ SELECT name FROM students က နာမည်တွေ ဆွဲထုတ်ပါတယ်။",
          ["query"], C[4]),
        i("concept_qa", "ACID ဆိုတာ ဘာလဲ?",
          "ACID ဆိုတာ transaction ကို စိတ်ချရအောင် ထိန်းတဲ့ ဂုဏ်သတ္တိ လေးခု ဖြစ်ပါတယ်။\n\nAtomicity၊ Consistency၊ Isolation၊ Durability ပါဝင်ပါတယ်။ ငွေလွှဲလို အလုပ်မှာ အရေးကြီးပါတယ်။\n\nတစ်ဆင့်ပျက်ရင် အကုန် ပြန်ဆုတ်ပြီး data မပျောက်ပါ။",
          ["database"], C[1]),
        i("concept_qa", "Atomicity ဆိုတာ ဘာလဲ?",
          "Atomicity ဆိုတာ transaction ထဲက အဆင့်တွေ အကုန်အောင်မှ ပြီးတယ်လို့ သတ်မှတ်ခြင်း ဖြစ်ပါတယ်။\n\nတစ်ခုပျက်ရင် rollback လုပ်ပါတယ်။ တစ်ဝက်တစ်ပျက် မကျန်ပါ။\n\nဥပမာ A ကနေ နုတ်ပြီး B ကို မပေါင်းခင် ပြတ်ရင် A ကို ပြန်ထားပါတယ်။",
          ["database"], C[1]),
        i("concept_qa", "Normalization ဆိုတာ ဘာလဲ?",
          "Normalization ဆိုတာ data ထပ်နေတာ လျှော့ပြီး table တွေ ခွဲသိမ်းခြင်း ဖြစ်ပါတယ်။\n\nပြင်ရင် တစ်နေရာတည်း ပြင်ရပါတယ်။ 1NF၊ 2NF၊ 3NF စသဖြင့် အဆင့်ရှိပါတယ်။\n\nဥပမာ ကျောင်းသားနဲ့ ဘာသာရပ်ကို table ခွဲသိမ်းနိုင်ပါတယ်။",
          ["normalization", "table"], C[8]),
        i("concept_qa", "1NF ဆိုတာ ဘာလဲ?",
          "1NF ဆိုတာ column တစ်ခုထဲမှာ တန်ဖိုး အများကြီး မထည့်ရခြင်း ဖြစ်ပါတယ်။\n\nပုံစံ တူညီရပါတယ်။ ခွဲထုတ်လို့ရတဲ့ list ကို row ခွဲရပါတယ်။\n\nဥပမာ ဖုန်းနံပါတ် နှစ်လုံးကို column တစ်ခုထဲ ကော်မာနဲ့ မထည့်သင့်ပါ။",
          ["normalization"], C[8]),
        i("concept_qa", "JOIN ဆိုတာ ဘာလဲ?",
          "JOIN ဆိုတာ table နှစ်ခုကို ဆက်စပ် column နဲ့ ပေါင်းကြည့်ခြင်း ဖြစ်ပါတယ်။\n\nINNER JOIN က ကိုက်ညီတာပဲ ပြပါတယ်။ LEFT JOIN က ဘယ်ဘက် table အကုန် ပြပါတယ်။\n\nဥပမာ ကျောင်းသားနဲ့ အမှတ်ကို student_id နဲ့ ပေါင်းနိုင်ပါတယ်။",
          ["JOIN", "table"], C[4]),
        i("concept_qa", "Index ဆိုတာ ဘာလဲ?",
          "Index ဆိုတာ ရှာဖွေမြန်အောင် column ပေါ်မှာ လမ်းညွှန်ထားခြင်း ဖြစ်ပါတယ်။\n\nစာအုပ်အညွှန်းလို နေရာကို မြန်မြန် ညွှန်ပါတယ်။ ရေးချိန်နည်းနည်း ပိုကုန်နိုင်ပါတယ်။\n\nဥပမာ email ကို မကြာခဏ ရှာရင် index ထားနိုင်ပါတယ်။",
          ["index", "query"], C[8]),
        i("concept_qa", "CRUD ဆိုတာ ဘာလဲ?",
          "CRUD ဆိုတာ Create၊ Read၊ Update၊ Delete လေးမျိုး ဖြစ်ပါတယ်။\n\nSQL မှာ INSERT၊ SELECT၊ UPDATE၊ DELETE နဲ့ ကိုက်ပါတယ်။ App တိုင်းလိုလို ဒီအလုပ်တွေ ရှိပါတယ်။\n\nဥပမာ ကျောင်းသားအသစ်ထည့်တာ Create ဖြစ်ပါတယ်။",
          ["query"], C[3]),
        i("concept_qa", "NoSQL ဆိုတာ ဘာလဲ?",
          "NoSQL ဆိုတာ table ဆက်စပ်မှုကို အဓိကမထားတဲ့ database အမျိုးအစား ဖြစ်ပါတယ်။\n\nDocument၊ key-value စသဖြင့် သိမ်းပါတယ်။ MongoDB၊ Redis တို့ ဥပမာ ဖြစ်ပါတယ်။\n\nပုံစံပြောင်းလွယ်တဲ့ data အတွက် သုံးတတ်ပါတယ်။",
          ["database"], C[1]),
        i("concept_qa", "Super key ဆိုတာ ဘာလဲ?",
          "Super key ဆိုတာ row ကို ခွဲခြားနိုင်တဲ့ column စု ဖြစ်ပါတယ်။\n\nPrimary key က super key ထဲက အတိုဆုံး ရွေးချယ်မှု ဖြစ်ပါတယ်။ Column တစ်ခု သို့မဟုတ် အများကြီး ဖြစ်နိုင်ပါတယ်။\n\nဥပမာ student_id သို့မဟုတ် student_id + name က super key ဖြစ်နိုင်ပါတယ်။",
          ["primary key"], C[8]),
        i("explain_code", "ဒီ SELECT * code ကို ရှင်းပြပါ။",
          "ဒီ query က students table က row အကုန် ဆွဲထုတ်ပါတယ်။\n\n* က column အားလုံးကို ဆိုလိုပါတယ်။ WHERE မပါလို့ စစ်ထုတ်ခြင်း မရှိပါ။\n\nTable ထဲမှာ ၃ ယောက်ရှိရင် ၃ ကြောင်း ထွက်ပါတယ်။",
          ["SELECT", "table"], C[4],
          "SELECT * FROM students;"),
        i("explain_code", "ဒီ SELECT column code ကို ရှင်းပြပါ။",
          "ဒီ query က နာမည်နဲ့ အတန်းပဲ ယူပါတယ်။\n\n* မသုံးဘဲ လိုအပ်တဲ့ column ကို ရွေးပါတယ်။ ဖတ်ရ ပိုရှင်းပါတယ်။\n\nအခြား column တွေ မပါပါ။",
          ["SELECT", "table"], C[4],
          "SELECT name, grade FROM students;"),
        i("explain_code", "ဒီ WHERE query ကို ရှင်းပြပါ။",
          "ဒီ query က Grade 10 ကျောင်းသားတွေပဲ ယူပါတယ်။\n\nWHERE က စစ်ထုတ်ချက် ဖြစ်ပါတယ်။ တူညီတဲ့ row တွေသာ ကျန်ပါတယ်။\n\nGrade 9 တွေ မပါပါ။",
          ["query", "SELECT"], C[4],
          "SELECT name FROM students WHERE grade = 10;"),
        i("explain_code", "ဒီ INSERT code ကို ရှင်းပြပါ။",
          "ဒီ query က ကျောင်းသားအသစ် တစ်ယောက် ထည့်ပါတယ်။\n\nname နဲ့ age column ကို တန်ဖိုး ပေးပါတယ်။ id က auto ဖြစ်နိုင်ပါတယ်။\n\nSu, 16 က table ထဲ ရောက်ပါတယ်။",
          ["INSERT", "table"], C[3],
          "INSERT INTO students (name, age) VALUES ('Su', 16);"),
        i("explain_code", "ဒီ UPDATE code ကို ရှင်းပြပါ။",
          "ဒီ query က id 1 ရဲ့ နာမည်ကို ပြင်ပါတယ်။\n\nSET က column အသစ်ပေးပါတယ်။ WHERE မပါရင် အကုန် ပြောင်းသွားနိုင်ပါတယ်။\n\nဒီမှာ id 1 ပဲ Aung Lin ဖြစ်ပါတယ်။",
          ["UPDATE", "primary key"], C[6],
          "UPDATE students SET name = 'Aung Lin' WHERE id = 1;"),
        i("explain_code", "ဒီ DELETE code ကို ရှင်းပြပါ။",
          "ဒီ query က id 3 ကို ဖျက်ပါတယ်။\n\nWHERE က ဘယ် row ကို ဖျက်မလဲ ကန့်သတ်ပါတယ်။ မပါရင် table ဗလာ ဖြစ်နိုင်ပါတယ်။\n\nid 3 ပဲ ပျောက်ပါတယ်။",
          ["DELETE", "table"], C[6],
          "DELETE FROM students WHERE id = 3;"),
        i("explain_code", "ဒီ CREATE TABLE code ကို ရှင်းပြပါ။",
          "ဒီ code က students table တည်ဆောက်ပါတယ်။\n\nid က int၊ အလိုအလျောက် တိုးပြီး primary key ဖြစ်ပါတယ်။ name က စာသား မဖြစ်မနေ ထည့်ရပါတယ်။\n\nTable အသစ် အဆင်သင့် ဖြစ်ပါတယ်။",
          ["table", "primary key"], C[3],
          "CREATE TABLE students (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  name VARCHAR(100) NOT NULL\n);"),
        i("explain_code", "ဒီ INNER JOIN ကို ရှင်းပြပါ။",
          "ဒီ query က ကျောင်းသားနဲ့ အမှတ်ကို ပေါင်းပါတယ်။\n\nON က id တူတာကို တွဲပါတယ်။ နှစ်ဖက်စလုံးမှာ ရှိမှ ပြပါတယ်။\n\nအမှတ်မရှိတဲ့ ကျောင်းသား မပါပါ။",
          ["JOIN", "query"], C[4],
          "SELECT students.name, scores.mark\nFROM students\nINNER JOIN scores ON students.id = scores.student_id;"),
        i("explain_code", "ဒီ ORDER BY ကို ရှင်းပြပါ။",
          "ဒီ query က အသက် အကြီးကနေ အငယ် စီပါတယ်။\n\nDESC က ကြီးရာက စပါတယ်။ name တွေ အသက်စဉ်အတိုင်း ထွက်ပါတယ်။\n\nအငယ်ဆုံးက နောက်ဆုံး ရောက်ပါတယ်။",
          ["SELECT", "query"], C[4],
          "SELECT name, age FROM students ORDER BY age DESC;"),
        i("explain_code", "ဒီ LIMIT query ကို ရှင်းပြပါ။",
          "ဒီ query က ရှေ့ဆုံး ၅ ယောက်ပဲ ယူပါတယ်။\n\nLIMIT က ရလဒ် အရေအတွက် ဖြတ်ပါတယ်။ စာမျက်နှာခွဲရာမှာ သုံးပါတယ်။\n\nကျန် row တွေ မပါပါ။",
          ["SELECT"], C[4],
          "SELECT name FROM students LIMIT 5;"),
        i("explain_code", "ဒီ COUNT query ကို ရှင်းပြပါ။",
          "ဒီ query က ကျောင်းသား ဘယ်နှစ်ယောက်ရှိလဲ ရေတွက်ပါတယ်။\n\nCOUNT(*) က row အရေအတွက် ပေးပါတယ်။ တစ်ကြောင်းတည်း ထွက်ပါတယ်။\n\n၁၀ ယောက်ရှိရင် ၁၀ ရပါတယ်။",
          ["query"], C[4],
          "SELECT COUNT(*) FROM students;"),
        i("explain_code", "ဒီ GROUP BY ကို ရှင်းပြပါ။",
          "ဒီ query က အတန်းအလိုက် ကျောင်းသားဦးရေ တွက်ပါတယ်။\n\nGROUP BY က တူညီတဲ့ grade ကို စုပါတယ်။ COUNT က အုပ်စုတိုင်း ရေတွက်ပါတယ်။\n\nGrade 10 မှာ ၃၀ ယောက် စသဖြင့် ထွက်ပါတယ်။",
          ["query", "table"], C[4],
          "SELECT grade, COUNT(*) FROM students GROUP BY grade;"),
        i("explain_code", "ဒီ mysql login command ကို ရှင်းပြပါ။",
          "ဒီ command က MySQL ကို root အကောင့်နဲ့ ဝင်ပါတယ်။\n\n-u က user၊ -p က password တောင်းမှာ ဖြစ်ပါတယ်။ မှန်ကန်ရင် SQL ရေးလို့ရတဲ့ prompt ရပါတယ်။\n\nPassword မှားရင် ဝင်လို့မရပါ။",
          ["database"], C[3],
          "mysql -uroot -p"),
        i("explain_code", "ဒီ CREATE DATABASE ကို ရှင်းပြပါ။",
          "ဒီ query က school အမည်နဲ့ database အသစ် လုပ်ပါတယ်။\n\nTable မထည့်ခင် database ရှိရပါတယ်။ နောက် USE school နဲ့ ရွေးသုံးပါတယ်။\n\nနာမည်တူ ရှိပြီးသားဆို error တက်နိုင်ပါတယ်။",
          ["database"], C[3],
          "CREATE DATABASE school;"),
        i("explain_code", "ဒီ USE database ကို ရှင်းပြပါ။",
          "ဒီ command က နောက် SQL တွေကို school ပေါ်မှာ လုပ်ခိုင်းပါတယ်။\n\nDatabase အများကြီးရှိရင် ဘယ်ဟာသုံးမလဲ ရွေးရပါတယ်။ မရွေးရင် table ကို ရှာမတွေ့နိုင်ပါ။\n\nschool ကို active ဖြစ်စေပါတယ်။",
          ["database"], C[3],
          "USE school;"),
        i("debug_explain", "ဒီ UPDATE ဘာကြောင့် အကုန် ပြောင်းသွားသလဲ?",
          "WHERE မပါလို့ row အားလုံး name ပြောင်းသွားပါတယ်။\n\nပြင်ချင်တဲ့ row ကို key နဲ့ ကန့်သတ်ရပါတယ်။\n\nမှန်ကန်သော code:\nUPDATE students SET name = 'Aung' WHERE id = 1;",
          ["UPDATE", "debug"], C[6],
          "UPDATE students SET name = 'Aung';"),
        i("debug_explain", "ဒီ DELETE အန္တရာယ်ကို ပြင်ပါ။",
          "WHERE မပါတဲ့ DELETE က table ကို ဗလာလုပ်ပါတယ်။\n\nဖျက်ချင်တဲ့ id ကို တိတိကျကျ ရေးရပါတယ်။\n\nမှန်ကန်သော code:\nDELETE FROM students WHERE id = 2;",
          ["DELETE", "debug"], C[6],
          "DELETE FROM students;"),
        i("debug_explain", "ဒီ JOIN syntax ကို ပြင်ပါ။",
          "ON မပါလို့ table နှစ်ခု ကားတီးဆက် ဖြစ်သွားနိုင်ပါတယ်။\n\nဘယ် column တူလဲ ပြောရပါတယ်။\n\nမှန်ကန်သော code:\nSELECT students.name, scores.mark\nFROM students\nINNER JOIN scores ON students.id = scores.student_id;",
          ["JOIN", "syntax"], C[4],
          "SELECT students.name, scores.mark\nFROM students\nINNER JOIN scores;"),
        i("concept_qa", "Transaction ဆိုတာ ဘာလဲ?",
          "Transaction ဆိုတာ အလုပ်အချို့ကို တစ်စုတည်း အောင် သို့မဟုတ် ပျက် စေခြင်း ဖြစ်ပါတယ်။\n\nBEGIN၊ COMMIT၊ ROLLBACK သုံးပါတယ်။ ငွေလွှဲလို အလုပ်မှာ လိုအပ်ပါတယ်။\n\nအောင်ရင် COMMIT၊ ပျက်ရင် ROLLBACK လုပ်ပါတယ်။",
          ["database"], C[1]),
        i("explain_code", "ဒီ COMMIT transaction ကို ရှင်းပြပါ။",
          "ဒီ code က ငွေလွှဲ နှစ်ဆင့်ကို တစ်ကြိမ်တည်း အတည်ပြုပါတယ်။\n\nနှစ်ခုလုံး အောင်မှ COMMIT ဖြစ်ပါတယ်။ တစ်ခုပျက်ရင် ဒီပုံစံအတိုင်း မသိမ်းသင့်ပါ။\n\nA လျော့ပြီး B တိုးတာ နှစ်ခုလုံး ကျပါတယ်။",
          ["database"], C[1],
          "START TRANSACTION;\nUPDATE accounts SET balance = balance - 100 WHERE id = 1;\nUPDATE accounts SET balance = balance + 100 WHERE id = 2;\nCOMMIT;"),
        i("concept_qa", "VARCHAR နဲ့ INT ဘာကွာလဲ?",
          "VARCHAR က စာသား၊ INT က ကိန်းပြည့် ဖြစ်ပါတယ်။\n\nနာမည်ကို VARCHAR၊ အသက်ကို INT သုံးသင့်ပါတယ်။ အရွယ်အစား သေးရင် သိုလှောင်မှု သက်သာပါတယ်။\n\nဖုန်းကို စာသားအဖြစ် သိမ်းတတ်ပါတယ်။ တွက်စရာ မဟုတ်လို့ပါ။",
          ["integer"], C[3]),
        i("concept_qa", "NULL ဆိုတာ ဘာလဲ?",
          "NULL ဆိုတာ တန်ဖိုး မရှိသေးကြောင်း ပြပါတယ်။\n\n၀ သို့မဟုတ် ဗလာစာသားနဲ့ မတူပါ။ NOT NULL ဆိုရင် မဖြစ်မနေ ထည့်ရပါတယ်။\n\nဥပမာ ဖုန်းမရှိသေးရင် phone က NULL ဖြစ်နိုင်ပါတယ်။",
          ["table"], C[3]),
        i("explain_code", "ဒီ NOT NULL column ကို ရှင်းပြပါ။",
          "ဒီ table မှာ name မထည့်ရင် row မရပါ။\n\nNOT NULL က ဗလာမခံပါ။ email က ချန်လို့ရပါတယ်။\n\nname မပါတဲ့ INSERT က ရှုံးပါတယ်။",
          ["table"], C[3],
          "CREATE TABLE users (\n  id INT PRIMARY KEY,\n  name VARCHAR(50) NOT NULL,\n  email VARCHAR(100)\n);"),
        i("explain_code", "ဒီ DISTINCT query ကို ရှင်းပြပါ။",
          "ဒီ query က ထပ်နေတဲ့ မြို့နာမည်တွေကို တစ်ခုတည်း ပြပါတယ်။\n\nDISTINCT က ထပ်တာ ဖယ်ပါတယ်။ စာရင်းရှင်းပါတယ်။\n\nYangon နှစ်ကြိမ်ရှိရင် တစ်ကြိမ်ပဲ တွေ့ပါတယ်။",
          ["SELECT"], C[4],
          "SELECT DISTINCT city FROM students;"),
        i("explain_code", "ဒီ LIKE query ကို ရှင်းပြပါ။",
          "ဒီ query က A နဲ့စတဲ့ နာမည်တွေကို ရှာပါတယ်။\n\n% က နောက်စာ မည်မျှမဆို ကိုက်ပါတယ်။ စာသားစစ်ထုတ်ရာမှာ သုံးပါတယ်။\n\nAung၊ Aye တို့ ပါနိုင်ပါတယ်။",
          ["query"], C[4],
          "SELECT name FROM students WHERE name LIKE 'A%';"),
        i("concept_qa", "Many-to-many ဆိုတာ ဘာလဲ?",
          "Many-to-many ဆိုတာ နှစ်ဖက်စလုံး အများချင်း ဆက်နိုင်ခြင်း ဖြစ်ပါတယ်။\n\nကျောင်းသားတစ်ယောက် ပရောဂျက်အများ၊ ပရောဂျက်တစ်ခု ကျောင်းသားအများ ရှိနိုင်ပါတယ်။ အလယ် table လိုပါတယ်။\n\nဥပမာ student_project table က နှစ်ဖက် id ကို သိမ်းပါတယ်။",
          ["table", "foreign key"], C[8]),
        i("explain_code", "ဒီ intermediate table ကို ရှင်းပြပါ။",
          "ဒီ table က ကျောင်းသားနဲ့ ပရောဂျက်ကို ချိတ်ပါတယ်။\n\nforeign key နှစ်ခုက မိဘ table တွေကို ညွှန်ပါတယ်။ တူညီတဲ့ စုံတွဲ ထပ်မရအောင် primary key ပေါင်းထားပါတယ်။\n\nကျောင်းသား ၂ က ပရောဂျက် ၅ မှာ ပါကြောင်း သိမ်းနိုင်ပါတယ်။",
          ["foreign key", "table"], C[8],
          "CREATE TABLE student_project (\n  student_id INT,\n  project_id INT,\n  PRIMARY KEY (student_id, project_id)\n);"),
        i("concept_qa", "One-to-many ဆိုတာ ဘာလဲ?",
          "One-to-many ဆိုတာ တစ်ခုက အများနဲ့ ဆက်ခြင်း ဖြစ်ပါတယ်။\n\nဆရာတစ်ယောက်မှာ တန်းအများ ရှိနိုင်ပါတယ်။ တန်းတစ်ခုမှာ ဆရာအဓိက တစ်ယောက် ရှိနိုင်ပါတယ်။\n\nforeign key က many ဘက်မှာ နေပါတယ်။",
          ["foreign key"], C[8]),
        i("explain_code", "ဒီ AVG query ကို ရှင်းပြပါ။",
          "ဒီ query က ပျမ်းမျှ အမှတ် တွက်ပါတယ်။\n\nAVG က ဂဏန်းတွေရဲ့ ပျမ်းမျှ ပေးပါတယ်။ NULL ကို ကျော်တတ်ပါတယ်။\n\n၈၀ နဲ့ ၁၀၀ ရှိရင် ၉၀ ရနိုင်ပါတယ်။",
          ["query"], C[4],
          "SELECT AVG(mark) FROM scores;"),
        i("explain_code", "ဒီ HAVING query ကို ရှင်းပြပါ။",
          "ဒီ query က ကျောင်းသား ၂ ယောက်နှင့်အထက်ရှိတဲ့ အတန်းပဲ ပြပါတယ်။\n\nWHERE က row ကို စစ်ပြီး HAVING က group ကို စစ်ပါတယ်။ COUNT ပြီးမှ ဖြတ်ပါတယ်။\n\nလူနည်းတဲ့ အတန်း မပါပါ။",
          ["query"], C[4],
          "SELECT grade, COUNT(*) AS total\nFROM students\nGROUP BY grade\nHAVING COUNT(*) >= 2;"),
        i("concept_qa", "View ဆိုတာ ဘာလဲ?",
          "View ဆိုတာ သိမ်းထားတဲ့ SELECT ရလဒ်ပုံစံ ဖြစ်ပါတယ်။\n\nမူရင်း table ကို ထပ်မကူးဘဲ မေးခွန်းကို နာမည်ပေးထားပါတယ်။ ဖတ်ရ လွယ်ပါတယ်။\n\nဥပမာ top_students view က အမှတ်မြင့်သူတွေကို ပြနိုင်ပါတယ်။",
          ["query"], C[8]),
        i("concept_qa", "Backup ဘာကြောင့် လိုအပ်လဲ?",
          "Backup ဆိုတာ data ပျက်စီးရင် ပြန်ယူဖို့ မိတ္တူ ဖြစ်ပါတယ်။\n\nဖျက်မှားခြင်း၊ disk ပျက်ခြင်းတွေက ဖြစ်နိုင်ပါတယ်။ ပုံမှန် ကူးယူထားရင် ဆုံးရှုံးမှု နည်းပါတယ်။\n\nဥပမာ ညတိုင်း database dump လုပ်နိုင်ပါတယ်။",
          ["database"], C[1]),
        i("debug_explain", "ဒီ SELECT syntax ကို ပြင်ပါ။",
          "FROM မပါလို့ table ကို မသိပါ။\n\nSELECT ပြီး ဘယ်ကယူမလဲ ပြောရပါတယ်။\n\nမှန်ကန်သော code:\nSELECT name FROM students;",
          ["SELECT", "syntax"], C[4],
          "SELECT name students;"),
        i("explain_code", "ဒီ BETWEEN query ကို ရှင်းပြပါ။",
          "ဒီ query က အသက် ၁၅ မှ ၁၈ ထိ ယူပါတယ်။\n\nBETWEEN က နှစ်ဖက်စွန်း ပါဝင်ပါတယ်။ ၁၄ နဲ့ ၁၉ မပါပါ။\n\nအသက်ကန့်သတ် စာရင်းအတွက် သုံးပါတယ်။",
          ["query"], C[4],
          "SELECT name FROM students WHERE age BETWEEN 15 AND 18;"),
        i("explain_code", "ဒီ IN query ကို ရှင်းပြပါ။",
          "ဒီ query က Yangon သို့မဟုတ် Mandalay က ကျောင်းသားတွေကို ယူပါတယ်။\n\nIN က စာရင်းထဲ ပါမပါ စစ်ပါတယ်။ OR များများ ရေးစရာ မလိုပါ။\n\nအခြားမြို့ မပါပါ။",
          ["query"], C[4],
          "SELECT name FROM students WHERE city IN ('Yangon', 'Mandalay');"),
        i("concept_qa", "Referential integrity ဆိုတာ ဘာလဲ?",
          "Referential integrity ဆိုတာ foreign key က တကယ်ရှိတဲ့ row ကိုပဲ ညွှန်ရခြင်း ဖြစ်ပါတယ်။\n\nမရှိတဲ့ parent ကို ချိတ်လို့မရပါ။ ကလေးရှိရင် parent ကို မဆင်မခြင် မဖျက်သင့်ပါ။\n\nဒါကြောင့် ဆက်စပ် data မပျက်ပါ။",
          ["foreign key"], C[8]),
        i("explain_code", "ဒီ UNIQUE column ကို ရှင်းပြပါ။",
          "ဒီ table မှာ email ထပ်လို့မရပါ။\n\nUNIQUE က တူညီတဲ့ တန်ဖိုး နှစ်ခု မခံပါ။ login အတွက် အသုံးဝင်ပါတယ်။\n\nတူတဲ့ email နဲ့ INSERT က ရှုံးပါတယ်။",
          ["table"], C[3],
          "CREATE TABLE accounts (\n  id INT PRIMARY KEY,\n  email VARCHAR(120) UNIQUE\n);"),
        i("concept_qa", "Schema ဆိုတာ ဘာလဲ?",
          "Schema ဆိုတာ table၊ column၊ ဆက်စပ်မှုတွေရဲ့ ဖွဲ့စည်းပုံ ဖြစ်ပါတယ်။\n\nData မထည့်ခင် ပုံစံ သတ်မှတ်ပါတယ်။ မှားရင် နောက်မှ ပြင်ရ ခက်ပါတယ်။\n\nကောင်းတဲ့ schema က မေးခွန်းတွေကို လွယ်ကူစေပါတယ်။",
          ["database", "table"], C[1]),
        i("explain_code", "ဒီ ALTER TABLE ကို ရှင်းပြပါ။",
          "ဒီ command က students ထဲကို phone column ထပ်ထည့်ပါတယ်။\n\nရှိပြီးသား table ကို ဖျက်စရာမလိုပါ။ VARCHAR(20) က ဖုန်းစာသား သိမ်းပါတယ်။\n\ncolumn အသစ်က ယခင် row တွေမှာ NULL ဖြစ်နိုင်ပါတယ်။",
          ["table"], C[6],
          "ALTER TABLE students ADD phone VARCHAR(20);"),
        i("debug_explain", "ဒီ INSERT column အရေအတွက် မှားတာကို ပြင်ပါ။",
          "Column နှစ်ခုပေးပြီး တန်ဖိုး သုံးခု ပေးထားလို့ မကိုက်ပါ။\n\nအရေအတွက် တူအောင် ရေးရပါတယ်။\n\nမှန်ကန်သော code:\nINSERT INTO students (name, age) VALUES ('Min', 17);",
          ["INSERT", "syntax"], C[3],
          "INSERT INTO students (name, age) VALUES ('Min', 17, 'Grade10');"),
        i("concept_qa", "Data type size ဘာကြောင့် အရေးကြီးလဲ?",
          "Size ကြီးရင် သိုလှောင်မှု ပိုကုန်ပြီး ရှာဖွေနှေးနိုင်ပါတယ်။\n\nလိုအပ်သလောက်သာ ယူသင့်ပါတယ်။ နာမည်တိုကို VARCHAR(500) ပေးစရာမလိုပါ။\n\nမှန်ကန်တဲ့ အရွယ်က စွမ်းဆောင်ရည် ကောင်းစေပါတယ်။",
          ["database"], C[3]),
        i("explain_code", "ဒီ LEFT JOIN ကို ရှင်းပြပါ။",
          "ဒီ query က ကျောင်းသား အကုန်ပြပြီး အမှတ်ရှိမှ ပေါင်းပါတယ်။\n\nအမှတ်မရှိသူမှာ mark က NULL ဖြစ်ပါတယ်။ INNER JOIN ထက် ပိုပြည့်ပါတယ်။\n\nစာမေးပွဲမဖြေရသေးသူကိုလည်း မြင်နိုင်ပါတယ်။",
          ["JOIN"], C[4],
          "SELECT students.name, scores.mark\nFROM students\nLEFT JOIN scores ON students.id = scores.student_id;"),
        i("concept_qa", "MySQL ကို ဘာကြောင့် သင်ရလဲ?",
          "MySQL က relational database တွေထဲမှာ အသုံးများပါတယ်။\n\nဝက်ဘ်စနစ်တွေနဲ့ တွဲသုံးလွယ်ပါတယ်။ အခြေခံ SQL က အခြား database ကိုလည်း ကူးသုံးနိုင်ပါတယ်။\n\nဒါကြောင့် အခြေခံသင်ခန်းစာအတွက် သင့်တော်ပါတယ်။",
          ["database"], C[1]),
        i("explain_code", "ဒီ MIN MAX query ကို ရှင်းပြပါ။",
          "ဒီ query က အငယ်ဆုံးနဲ့ အကြီးဆုံး အမှတ်ကို တစ်ကြောင်းတည်း ယူပါတယ်။\n\nMIN နဲ့ MAX က အုပ်စုမခွဲရင် table တစ်ခုလုံးပေါ် မူတည်ပါတယ်။\n\nဥပမာ ၄၀ နဲ့ ၉၉ ရနိုင်ပါတယ်။",
          ["query"], C[4],
          "SELECT MIN(mark), MAX(mark) FROM scores;"),
        i("debug_explain", "ဒီ string quote SQL ကို ပြင်ပါ။",
          "စာသားကို quote မပိတ်လို့ syntax error တက်ပါတယ်။\n\nSQL string ကို တစ်ဖက်တည်း ပိတ်ရပါတယ်။\n\nမှန်ကန်သော code:\nSELECT * FROM students WHERE name = 'Aung';",
          ["syntax", "query"], C[4],
          "SELECT * FROM students WHERE name = 'Aung;"),
        i("concept_qa", "Query optimization ဆိုတာ ဘာလဲ?",
          "Query optimization ဆိုတာ မေးခွန်းကို ပိုမြန်အောင် ပြင်ခြင်း ဖြစ်ပါတယ်။\n\nမလိုအပ်တဲ့ * ၊ index မရှိခြင်း၊ JOIN မှားခြင်းတွေက နှေးစေပါတယ်။ လိုအပ်တဲ့ column ပဲ ယူသင့်ပါတယ်။\n\nEXPLAIN နဲ့ စစ်ဆေးနိုင်ပါတယ်။",
          ["query", "index"], C[8]),
        i("explain_code", "ဒီ index create ကို ရှင်းပြပါ။",
          "ဒီ command က email ပေါ်မှာ index တည်ဆောက်ပါတယ်။\n\nemail နဲ့ ရှာရင် ပိုမြန်ပါတယ်။ နာမည် idx_email လို့ မှတ်ပါတယ်။\n\nထည့်ရေးချိန် နည်းနည်း ပိုကုန်နိုင်ပါတယ်။",
          ["index"], C[8],
          "CREATE INDEX idx_email ON users(email);"),
    ]
