from .common import item as i

CH = "Data structures & algorithms"


def samples():
    return [
        i("concept_qa", "DSA ဆိုတာ ဘာလဲ?",
          "Applications တွေ system တွေက တစ်ဖြည်းဖြည်းနဲ့ ကျယ်ပြန့်လာတဲ့ အချိန်၊ data တွေများပြားလာတဲ့အချိန်မှာ အဲ့ဒီ များပြားလာတဲ့ data တွေကို manage လုပ်ဖို့ဆိုတာကလဲ challenging တစ်ခုဖြစ်လာပါတယ်။\n\nmillion, billion, trillion ချီတဲ့ data တွေကို performance ကောင်းစွာ ဘယ်လို handle လုပ်မလဲဆိုတာက အရေးကြီးပါတယ်။\n\nဒါကြောင့်မို့လဲ data structures and algorithms ဆိုပြီးတော့ ဖြစ်ပေါ်လာတာပါ။",
          ["dsa"], CH),
        i("concept_qa", "Algorithm ဆိုတာ ဘာလဲ?",
          "Algorithms ဆိုတာက အရှင်းဆုံးပြောရရင် step by step procedure ပဲ။\n\nData structures and algorithms တွေကိုအသုံးပြုပြီးတော့ data တွေအများကြီးကို ကောင်းမွန်စွာ handle ပြုလုပ်လာနိုင်ပါတယ်။\n\nကျနော်တို့ လက်ရှိအသုံးပြုနေတဲ့ systems တွေ applications တွေအားလုံးက data structures တွေ algorithms တွေနဲ့ ဖွဲ့စည်းထားတာပဲဖြစ်ပါတယ်။",
          ["dsa"], CH),
        i("concept_qa", "Big O Notation ဆိုတာ ဘာလဲ?",
          "Big O Notation ဆိုတာက program/algorithm တစ်ခုရဲ့ performance run time ကိုဆိုလိုတာပါ၊ ဒီ algorithm တစ်ခု က ဘယ်လောက်မြန်လဲ၊ ဘယ်လောက်နှေးလဲစသည်ဖြင့်ပေါ့။\n\nတစ်နည်းအားဖြင့် ပြောရမယ်ဆိုရင် algorithm တစ်ခုရဲ့ ခက်ခဲမှု (complexity) လို့လဲပြောလို့ရပါတယ်။\n\nစာကြည့်တိုက်မှာ စာအုပ်လာငှားတဲ့ လူက နာမည်တပ်ပြောလိုက်ရင် အဲ့ စာအုပ်ကို လိုက်ရှာဖို့က အချိန်တော်တော်ယူနေရတယ်။",
          ["dsa"], CH),
        i("concept_qa", "Array ဆိုတာ ဘာလဲ?",
          "array ကတော့ အားလုံးနဲ့ လည်း မစိမ်းလောက်ဘူး ၊ data value တွေကို collection လုပ်ထားတဲ့ sequence လို့လဲပြောလို့ရတယ်။\n\nဆိုလိုချင်တာ က data တွေ store လုပ်ဖို့ ပြန်ပြီး retrieve လုပ်ဖို့အတွက် အဆင်ပြေ အောင်ဖန်တီးထားတဲ့ data structure တစ်ခုလို့ဆိုနိုင်တယ်။\n\nelement ဆိုတာကတော့ array ထဲမှာ သိမ်းထားတဲ့ data value။",
          ["array"], CH),
        i("concept_qa", "Array index ဆိုတာ ဘာလဲ?",
          "အဲ့ array ထဲမှာ သိမ်းထားတဲ့ element တစ်ခုခြင်းရဲ့ memory ထဲမှာ numeric key တစ်ခု တွဲပေးထားတယ်၊ အဲ့ဒီ key ကို index လို့ခေါ်တယ်။\n\nelement value ကို index key သုံးပြီး လှမ်းဆွဲထုတ်လို့ရတယ်။\n\nArray နဲ့ မသိမ်းဘဲ value တစ်ခု ခြင်းဆီ ကို variable တစ်ခုပေးပြီးလည်း သိမ်းလို့ရတယ်။",
          ["array", "index"], CH),
        i("concept_qa", "Linked list ဆိုတာ ဘာလဲ?",
          "Linked list ဆိုတာ ကကျ data node တွေကို sequence အတိုင်း link လုပ်ထားတာ။\n\nမြင်အောင် ပြောရမယ်ဆိုရင် list စစချင်းမှာ head ရှိမယ်၊ အဆုံးမှာ tail ရှိမယ်၊ ကြားထဲမှာ data node တွေနဲ့ သူတို့ကို ချိတ်ဆက်ထားတဲ့ link တွေရှိမယ်။\n\nLinked lists တွေကိုပြန်ခွဲကြည့်မယ်ဆို Singly linked list, Doubly linked list, Circular linked list ဆိုပြီးရှိတယ်။",
          ["dsa"], CH),
        i("concept_qa", "Singly linked list နဲ့ doubly linked list ဘာကွာလဲ?",
          "Singly linked list ကကျ တော့ data node တွေကြားမှာ ချိတ်ဆက်ထားတဲ့ link တွေက node တစ်ခုခြင်းဆီရဲ့ forward ကိုပဲ ချိတ်လို့ရတယ်၊ backward (previous node) ကို link ပြန်လုပ်ထားတာမရှိဘူး။\n\nDoubly linked list ကတော့ node တွေအကုန်လုံးကို forward ရော backward ရော link လုပ်ထားတယ်။\n\nဆိုတော့ ပိုပြီးတော့ အသုံးဝင် တယ်လို့ဆိုရမယ်။",
          ["dsa"], CH),
        i("concept_qa", "Stack ဆိုတာ ဘာလဲ?",
          "Stack ဆိုတာက သူ့ကို ပေးထားတဲ့နာမည် အတိုင်းပဲ အစုလိုက်ထပ်ထပ်ဆင့်ထားတဲ့ ပုံစံမျိုးကို ဆိုလိုတဲ့ structure တစ်ခုပဲ၊ LIFO (last in first out) or FILO(first in last out) ဆိုတဲ့ order အတိုင်းအလုပ်လုပ်တယ်။\n\nပြောရမယ်ဆိုရင် စာအုပ်တွေထပ်ပြီးတင်ထားတယ်၊ နောက်ဆုံးတင်တဲ့ တစ်အုပ်ကိုပဲ အရင်ပြန်ယူတယ်။\n\nstack ကို array နဲ့ပဲဖြစ်ဖြစ် linked list နဲ့ပဲဖြစ်ဖြစ် ဆောက်လို့ရတယ်။",
          ["stack"], CH),
        i("concept_qa", "Stack မှာ push နဲ့ pop ဘာလဲ?",
          "stack မှာ operations တွေအမျိုးမျိုးရှိပေမဲ့ အဓိက သုံးတာက တော့ push နဲ့ pop ပဲ။\n\npop ဆို ထုတ်မယ်၊ push လုပ်လုပ် pop လုပ်လုပ် အပေါ်ဆုံးက data value ကိုပဲ လုပ်လို့ရမယ်။\n\nထိပ်ဆုံး element ကို access လုပ်ဖို့ဆို peek ဆိုတာကိုသုံးတယ်။",
          ["stack"], CH),
        i("concept_qa", "Queue ဆိုတာ ဘာလဲ?",
          "stack နဲ့မတူတာကကျ stack က one ended ကိုပဲ data အသွင်းအထုတ်ရတယ်။\n\ninsert လုပ်ဖို့အတွက်ကို enqueue လို့ခေါ်ပြီးတော့ remove လုပ်ဖို့ကိုကျ dequeue လို့ခေါ်တယ်။\n\nqueue မှာတော့ FIFO(first in first out) ပဲ၊ အရင်ဝင်လာတဲ့ process က အရင်ပြန်ထွက်တယ်။",
          ["queue"], CH),
        i("concept_qa", "Stack နဲ့ queue ဘာကွာလဲ?",
          "stack တုန်းက LIFO (last in first out) structure အတိုင်း ဆိုပေမဲ့ queue မှာတော့ FIFO(first in first out) ပဲ။\n\nreal world example အနေနဲ့ starbucks မှာ ကော်ဖီ မှာဖို့တန်းစီ ပြီး စောင့်နေတဲ့ လူတွေမျိုး၊ အရင်ရောက်တဲ့ လူက အရင်မှာတယ်။\n\nStack လိုပဲ queue ကို array တွေ linked lists တွေသုံးပြီးတော့ ဆောက်လို့ရတယ်။",
          ["stack", "queue"], CH),
        i("concept_qa", "Sorting ဆိုတာ ဘာလဲ?",
          "sorting ရဲ့ အဓိက ရည်ရွယ်ချက်ကတော့ data တွေကို အစီအစဉ်တကျ နေရာချထားဖို့ပါပဲ။\n\nဘာကြောင့် sorting လုပ်ရလဲဆိုတော့ searching algorithm တွေပိုပြီးတော့ strong ဖြစ်စေဖို့ (ဥပမာ. Binary search)။\n\nSorting စီပြီးတဲ့အချိန်မှာ data value တွေက မစီခင်က sequence အတိုင်းရှိရင် stable sorting ဖြစ်ပါတယ်။",
          ["dsa"], CH),
        i("concept_qa", "Binary search ဆိုတာ ဘာလဲ?",
          "Binary search ကတော့ strong ဖြစ်တဲ့ searching algorithm တစ်ခုဖြစ်ပြီးတော့ divide & conquer algorithm အပေါ်မှီငြမ်းထားပြီးအလုပ်လုပ်ပါတယ်။\n\nသူအလုပ်လုပ်ပုံက data collection ထဲကနေ middle item ကိုလှမ်းထောက်တယ်၊ ရလာတဲ့ key နဲ့ ရှာမယ့် key ကိုတိုက်စစ်ပြီး ငယ်တယ်ဆို ဘယ်ဘက်ကိုရွေ့၊ ကြီးတယ်ဆို ညာဘက်ရွေးပြီး mid item ထပ်ရှာပါတယ်။\n\nဒါကြောင့်မို့လို့ data collection တွေက sorted form ဖြစ်နေရမယ်။",
          ["dsa"], CH),
        i("concept_qa", "Binary search ဘာကြောင့် sorted ဖြစ်ရမှာလဲ?",
          "Binary search algorithm အလုပ်လုပ်ဖို့ဆိုရင် data value တွေက sorted form နဲ့ရှိထားရပါတယ်။\n\nတူတာတွေ့ပြီဆို ရင်တော့ process ပြီးပြီ၊ မတွေ့သေးသမျှတော့ middle most node ကို ထောက်ထောက်ပြီးတော့ အလုပ်လုပ်သွားတယ်။\n\nmid = low + (high - low) / 2 ဒီ formula နဲ့ medium node ကို ရှာလို့ရပါတယ်။",
          ["dsa"], CH),
        i("concept_qa", "Tree ဆိုတာ ဘာလဲ?",
          "Data Structure ရဲ့ အပိုင်းမှာ tree ဆိုတာက တော်တော်လေးအရေးပါတယ်။\n\nalgorithm တော်တော်များများကို tree တွေနဲ့ represent လုပ်ထားကြတဲ့အတွက်ကြောင့်ဖြစ်ပါတယ်။\n\nNode တစ်ခုနဲ့ တစ်ခု ကို tree structure အတိုင်း တစ်ဆင့်ခြင်းဆီ ချိတ်ဆက်ထားတယ်။",
          ["tree"], CH),
        i("concept_qa", "Binary tree ဆိုတာ ဘာလဲ?",
          "binary tree လို့ပြောလိုက်ပြီဆိုတာနဲ့ Node တစ်ခုမှာ child node နှစ်ခု လို့ ပြေးမြင်ထားလို့ရပါတယ်။\n\nBinary tree/binary search tree အတူတူပါပဲ။\n\nချိတ်ဆက်ထားတဲ့ node တွေက circular ပုံစံဖြစ်သွားတယ်ဆို tree လို့ခေါ်လို့မရတော့ဘူး။",
          ["tree"], CH),
        i("concept_qa", "Hash table ဆိုတာ ဘာလဲ?",
          "Hash table ဆိုတာ hashing ဆိုတဲ့ technique တစ်ခုကိုသုံးထားပြီးတော့ key နဲ့ value ကို mapping (တွဲ) ထားပေးတဲ့ structure တစ်ခုလို့ ဆိုနိုင်ပါတယ်။\n\nfrequency value တွေကို သူ့ရဲ့ associated key တွေနဲ့ တွဲပြီးတော့လည်း သိမ်းပါတယ်။\n\nHash table မှာ key & value map လုပ်မသွားခင်မှာ hashing အရင်လုပ်ရပါတယ်။",
          ["hash"], CH),
        i("concept_qa", "Priority queue ဆိုတာ ဘာလဲ?",
          "Priority Queue ဆိုတာကတော့ ပုံမှန် regular queue data structure ကိုပဲ အခြေခံပြီးလုပ်ထားတဲ့ structure တစ်ခုပဲ။\n\nမတူပဲ ကွဲပြားသွားတာက Priority Queue မှာက သူ့ထဲမှာ ပါတဲ့ data node တစ်ခုခြင်းဆီ က priority order လေးတွေပါတယ်။\n\nprocess တော်တော်များများကလည်း ပုံစံအတူတူပဲ။",
          ["queue"], CH),
        i("concept_qa", "AVL tree ဆိုတာ ဘာလဲ?",
          "AVL tree ဆိုတာကတော့ binary tree ကို modify ထပ်လုပ်ထားတဲ့ balanced binary tree ကိုအခြေခံထားတဲ့ algorithm တစ်ခုပဲဖြစ်ပါတယ်။\n\nbinary tree ရဲ့ worst case တွေမှာ performance က linear time အထိ ပြန်နိမ့်ကျသွားလို့ balanced binary လိုအပ်ပါတယ်။\n\nဥပမာ 1, 2, 3, 4, 5, 6, 7 ကို binary tree နဲ့ စီထည့် လိုက်မယ်ဆို tree က right side ကိုပဲ တစ်ဖတ်သတ်ချည်းစီသွားလိုက်မယ်။",
          ["tree"], CH),
        i("concept_qa", "Divide and conquer ဆိုတာ ဘာလဲ?",
          "Binary search ကတော့ strong ဖြစ်တဲ့ searching algorithm တစ်ခုဖြစ်ပြီးတော့ divide & conquer algorithm အပေါ်မှီငြမ်းထားပြီးအလုပ်လုပ်ပါတယ်။\n\ndivide & conquer လိုမျိုး sub problem တွေခွဲချပြီး recursion လုပ်ပြီးပြန်ပေါင်းတယ်။\n\nDynamic programming approach ကလည်း greedy နဲ့ divide & conquer ပုံစံတွေနဲ့ဆင်ပါတယ်။",
          ["dsa"], CH),
        i("explain_code", "ဒီ mid formula ကို ရှင်းပြပါ။",
          "ပထမဆုံး အဆင့် အနေနဲ့ medium node ကို အရင်ရှာပါတယ်၊ ဒီ formula နဲ့ ရှာလို့ရပါတယ်။\n\nmid = low + (high - low) / 2\n\nBinary search က sorted collection ထဲက middle item ကိုလှမ်းထောက်ပါတယ်။",
          ["dsa"], CH,
          "mid = low + (high - low) // 2"),
        i("explain_code", "ဒီ binary_search code ကို ရှင်းပြပါ။",
          "Binary search က data collection ထဲကနေ middle item ကိုလှမ်းထောက်တယ်။\n\nmid = low + (high - low) / 2 နဲ့ medium ရှာပါတယ်။ ငယ်တယ်ဆို ဘယ်ဘက်၊ ကြီးတယ်ဆို ညာဘက် ရွေးပါတယ်။\n\narr က sorted ဖြစ်နေရမယ်။ target ကို တွေ့ရင် mid ပြန်ပါတယ်။",
          ["dsa"], CH,
          "def binary_search(arr, target):\n    low = 0\n    high = len(arr) - 1\n    mid = low + (high - low) // 2\n    return mid"),
        i("explain_code", "ဒီ stack push ကို ရှင်းပြပါ။",
          "push ဆိုရင် stack ထဲကို data လာထည့်မယ်။\n\nအပေါ်ဆုံးက data value ကိုပဲ လုပ်လို့ရမယ်။ LIFO အတိုင်း အလုပ်လုပ်တယ်။\n\nitems.append က push ဖြစ်ပါတယ်။",
          ["stack"], CH,
          "stack = []\nstack.append(3)\nprint(stack)"),
        i("explain_code", "ဒီ stack pop ကို ရှင်းပြပါ။",
          "pop ဆို ထုတ်မယ်။ နောက်ဆုံးတင်တဲ့ တစ်အုပ်ကိုပဲ အရင်ပြန်ယူတယ်။\n\nstack.pop() က အပေါ်ဆုံး value ထုတ်ပါတယ်။\n\nempty ဖြစ်နေရင် ထုတ်လို့မရပါ။",
          ["stack"], CH,
          "stack = [1, 2, 3]\nprint(stack.pop())"),
        i("explain_code", "ဒီ enqueue ကို ရှင်းပြပါ။",
          "insert လုပ်ဖို့အတွက်ကို enqueue လို့ခေါ်တယ်။\n\nqueue မှာ FIFO၊ အရင်ဝင်လာတဲ့ process က အရင်ပြန်ထွက်တယ်။\n\nappend က နောက်ဆုံးမှာ ထည့်ပါတယ်။",
          ["queue"], CH,
          "queue = []\nqueue.append(\"A\")\nprint(queue)"),
        i("explain_code", "ဒီ dequeue ကို ရှင်းပြပါ။",
          "remove လုပ်ဖို့ကိုကျ dequeue လို့ခေါ်တယ်။\n\nအရင်ရောက်တဲ့ လူက အရင်မှာတယ်။ pop(0) က ရှေ့ဆုံး ထုတ်ပါတယ်။\n\nqueue က array နဲ့ ဆောက်လို့ရတယ်။",
          ["queue"], CH,
          "queue = [\"A\", \"B\"]\nprint(queue.pop(0))"),
        i("explain_code", "ဒီ array index code ကို ရှင်းပြပါ။",
          "element value ကို index key သုံးပြီး လှမ်းဆွဲထုတ်လို့ရတယ်။\n\nnums[2] က တတိယ element ဖြစ်ပါတယ်။\n\narray က data value တွေကို collection လုပ်ထားတဲ့ sequence ပါ။",
          ["array", "index"], CH,
          "nums = [10, 20, 30]\nprint(nums[2])"),
        i("concept_qa", "Heap ဆိုတာ ဘာလဲ?",
          "Priority Queue တွေကို heap နဲ့ တွဲပြီး အလုပ်လုပ်တတ်ပါတယ်။\n\nBinary heap ကို priority queue ထဲမှာ သုံးပါတယ်။\n\nheap က tree ပုံစံနဲ့ ဦးစားပေး တန်ဖိုးကို အပေါ်တင်ပါတယ်။",
          ["heap"], CH),
        i("concept_qa", "Greedy algorithm ဆိုတာ ဘာလဲ?",
          "Dynamic programming approach က greedy နဲ့ divide & conquer ပုံစံတွေနဲ့ဆင်ပါတယ်။\n\nGreedy က လက်ရှိအဆင့်မှာ အကောင်းဆုံး ရွေးပြီး ရှေ့ဆက်ပါတယ်။\n\nsub problem တွေခွဲချတဲ့ ပုံစံနဲ့ ယှဉ်ကြည့်ရပါတယ်။",
          ["dsa"], CH),
        i("concept_qa", "Dynamic programming ဆိုတာ ဘာလဲ?",
          "Dynamic programming approach က greedy နဲ့ divide & conquer ပုံစံတွေနဲ့ဆင်ပါတယ်။\n\ndivide & conquer လိုမျိုး sub problem တွေခွဲချပြီး recursion လုပ်ပြီးပြန်ပေါင်းတယ်။\n\nပြန်ပေါင်းတဲ့အခါ အရင်တွက်ပြီးသား ရလဒ်ကို ပြန်သုံးပါတယ်။",
          ["dsa"], CH),
        i("concept_qa", "Open addressing ဆိုတာ ဘာလဲ?",
          "Open addressing ဆိုတာကလည်း hash table မှာ collision ဖြစ်တဲ့အခါကျ ဖြေရှင်းနိုင်တဲ့ solving technique တစ်ခုပဲဖြစ်ပါတယ်။\n\nlinear probing အကြောင်းက open addressing မှာသုံးတဲ့ function တစ်ခုဖြစ်ပါတယ်။\n\ncollision ဖြစ်ရင် နောက် slot ကို ဆက်ရှာပါတယ်။",
          ["hash"], CH),
        i("concept_qa", "Separate chaining ဆိုတာ ဘာလဲ?",
          "ရှင်းရှင်းပြောရင် separate chaining က linked list algorithm ပေါ်ကို မှီငြမ်းပြီးတော့ အလုပ်လုပ်ထားတယ်လို့လဲပြောလို့ရပါတယ်။\n\npriority queue မှာ hash table ကိုထည့်သုံးသလို separate chaining မှာလည်း linked list ကိုသုံးထားတယ်။\n\ncollision ဖြစ်တဲ့ key တွေကို list နဲ့ ချိတ်ပါတယ်။",
          ["hash"], CH),
        i("concept_qa", "Union Find ဆိုတာ ဘာလဲ?",
          "Union Find က set တွေကို ပေါင်းပြီး ဘယ်အုပ်စုထဲမှာလဲ စစ်တဲ့ structure ဖြစ်ပါတယ်။\n\ndata node တွေကို ချိတ်ပြီး group ခွဲပါတယ်။\n\ngraph နဲ့ connected component တွေမှာ သုံးတတ်ပါတယ်။",
          ["dsa"], CH),
        i("debug_explain", "ဒီ binary_search high မှားတာ ပြင်ပါ။",
          "high က len(arr) ထားရင် နောက်ဆုံး index ကျော်ပါတယ်။\n\nlen(arr) - 1 ထားရပါတယ်။\n\nမှန်ကန်သော code:\ndef binary_search(arr, target):\n    low = 0\n    high = len(arr) - 1\n    return low, high",
          ["dsa"], CH,
          "def binary_search(arr, target):\n    low = 0\n    high = len(arr)\n    return low, high"),
        i("debug_explain", "ဒီ stack pop ဗလာ ပြင်ပါ။",
          "Empty ဖြစ်နေတယ်ဆို ထုတ်လို့မရပါ။\n\nမထုတ်ခင် length စစ်ရပါတယ်။\n\nမှန်ကန်သော code:\nstack = []\nif stack:\n    print(stack.pop())",
          ["stack"], CH,
          "stack = []\nprint(stack.pop())"),
        i("concept_qa", "Static array နဲ့ dynamic array ဘာကွာလဲ?",
          "Static တွေ dynamic တွေ မပြောခင် မှာ array အကြောင်းကို အရင်ပြောရအောင်။\n\narray က data value တွေကို collection လုပ်ထားတဲ့ sequence ပါ။\n\nstack ကို fixed sized ရော dynamic size ရော ကြိုက်သလိုဆောက်လို့ရတယ်။",
          ["array"], CH),
        i("concept_qa", "Peek ဆိုတာ ဘာလဲ?",
          "ထိပ်ဆုံး ကို element ကို access လုပ်ဖို့ဆို peek ဆိုတာကိုသုံးတာတို့ ရှိတယ်။\n\npush နဲ့ pop လို ထည့်ထုတ်မလုပ်ဘဲ ကြည့်ရုံပါ။\n\nstack က ပြည့် နေပြီးလား empty ဖြစ်နေလားစစ်တဲ့ function တွေလဲရှိတယ်။",
          ["stack"], CH),
        i("concept_qa", "Enqueue နဲ့ dequeue ဘာလဲ?",
          "insert လုပ်ဖို့အတွက်ကို enqueue လို့ခေါ်ပြီးတော့ remove လုပ်ဖို့ကိုကျ dequeue လို့ခေါ်တယ်။\n\nအရင်ဝင်လာတဲ့ process က အရင်ပြန်ထွက်တယ်။\n\nqueue ကို array တွေ linked lists တွေသုံးပြီးတော့ ဆောက်လို့ရတယ်။",
          ["queue"], CH),
        i("explain_code", "ဒီ sorted check ကို ရှင်းပြပါ။",
          "Binary search အလုပ်လုပ်ဖို့ data value တွေက sorted form နဲ့ရှိထားရပါတယ်။\n\nvalues == sorted(values) က စီပြီးသားလား စစ်ပါတယ်။\n\nမစီရင် middle item တိုက်စစ်လို့ မမှန်ပါ။",
          ["dsa"], CH,
          "values = [2, 4, 6]\nprint(values == sorted(values))"),
        i("concept_qa", "Collision ဆိုတာ ဘာလဲ?",
          "hash table မှာ collision ဖြစ်တဲ့အခါကျ ဖြေရှင်းနိုင်တဲ့ solving technique တွေရှိပါတယ်။\n\nOpen addressing နဲ့ separate chaining က ဒီပြဿနာကို ကိုင်ပါတယ်။\n\nkey နှစ်ခုက တူညီတဲ့ slot ကို ကျပါတယ်။",
          ["hash"], CH),
    ]
