from .common import item as i

CH = "JavaScript အခြေခံ"


def samples():
    return [
        i("concept_qa", "JavaScript ဆိုတာ ဘာလဲ?",
          "JavaScript ဆိုတာ ဝက်ဘ်စာမျက်နှာကို အသက်ဝင်စေတဲ့ programming language ဖြစ်ပါတယ်။\n\nHTML က ဖွဲ့စည်းပုံ၊ CSS က အလှ၊ JavaScript က အပြုအမူ ဖြစ်ပါတယ်။ Browser ထဲမှာ တိုက်ရိုက် run နိုင်ပါတယ်။\n\nဥပမာ ခလုတ်နှိပ်ရင် စာပြောင်းအောင် လုပ်နိုင်ပါတယ်။",
          ["javascript"], CH),
        i("concept_qa", "let, const, var ဘာကွာလဲ?",
          "let က ပြင်လို့ရတဲ့ variable၊ const က ပြန်မသတ်မှတ်ရ၊ var က ဟောင်းတဲ့ ပုံစံ ဖြစ်ပါတယ်။\n\nconst ကို မပြောင်းချင်တဲ့ တန်ဖိုးမှာ သုံးသင့်ပါတယ်။ let က block ထဲမှာပဲ မြင်ရပါတယ်။\n\nယနေ့ခေတ်မှာ var ကို ရှောင်သင့်ပါတယ်။",
          ["variable"], CH),
        i("concept_qa", "DOM ဆိုတာ ဘာလဲ?",
          "DOM ဆိုတာ HTML ကို JavaScript က ကိုင်တွယ်နိုင်အောင် ပြထားတဲ့ သစ်ပင်ပုံစံ ဖြစ်ပါတယ်။\n\nElement ရွေး၊ စာပြင်၊ class ထည့် နိုင်ပါတယ်။ User လုပ်ဆောင်ချက်ကို တုံ့ပြန်ပါတယ်။\n\nဥပမာ getElementById နဲ့ ခေါင်းစဉ် ပြောင်းနိုင်ပါတယ်။",
          ["DOM"], CH),
        i("concept_qa", "Function ကို JavaScript မှာ ဘယ်လို ရေးသလဲ?",
          "function နာမည်() {} သို့မဟုတ် arrow function သုံးပါတယ်။\n\nParameter လက်ခံပြီး return ပြန်နိုင်ပါတယ်။ ခလုတ်နှိပ်တဲ့အခါ ခေါ်တတ်ပါတယ်။\n\nဥပမာ const add = (a, b) => a + b; ဖြစ်ပါတယ်။",
          ["function"], CH),
        i("concept_qa", "Array method map ဆိုတာ ဘာလဲ?",
          "map ဆိုတာ array ရဲ့ တန်ဖိုးတိုင်းကို ပြောင်းပြီး array အသစ် ပေးခြင်း ဖြစ်ပါတယ်။\n\nမူရင်း array ကို မဖျက်ပါ။ တစ်ခုချင်း ပြန်ပေးရပါတယ်။\n\nဥပမာ ဂဏန်းတွေကို နှစ်ဆ လုပ်နိုင်ပါတယ်။",
          ["array", "function"], CH),
        i("concept_qa", "Event listener ဆိုတာ ဘာလဲ?",
          "Event listener ဆိုတာ နှိပ်ခြင်း၊ ရိုက်ခြင်းလို အဖြစ်ကို နားထောင်ခြင်း ဖြစ်ပါတယ်။\n\nဖြစ်လာရင် function တစ်ခု ခေါ်ပါတယ်။ addEventListener သုံးပါတယ်။\n\nဥပမာ click မှာ alert ပြနိုင်ပါတယ်။",
          ["javascript"], CH),
        i("concept_qa", "JSON ဆိုတာ ဘာလဲ?",
          "JSON ဆိုတာ data ကို စာသားပုံစံနဲ့ ဖလှယ်တဲ့ ပုံစံ ဖြစ်ပါတယ်။\n\nObject နဲ့ array ကို စာအဖြစ် ပြောင်းနိုင်ပါတယ်။ API တွေမှာ အသုံးများပါတယ်။\n\nJSON.parse က စာကို object ပြန်လုပ်ပါတယ်။",
          ["JSON", "object"], CH),
        i("concept_qa", "Promise ဆိုတာ ဘာလဲ?",
          "Promise ဆိုတာ နောက်မှ ပြီးမယ့် အလုပ်ကို ကိုယ်စားပြုပါတယ်။\n\nthen နဲ့ အောင်မြင်မှု၊ catch နဲ့ အမှား ကိုင်ပါတယ်။ async await က ပိုဖတ်လွယ်ပါတယ်။\n\nဥပမာ server က data စောင့်တာ ဖြစ်ပါတယ်။",
          ["javascript"], CH),
        i("concept_qa", "Truthy နဲ့ falsy ဆိုတာ ဘာလဲ?",
          "Falsy က false၊ 0၊ \"\"၊ null၊ undefined၊ NaN ဖြစ်ပါတယ်။\n\nကျန်တာက truthy ဖြစ်ပါတယ်။ if မှာ အလိုအလျောက် မှန်/မှား သတ်မှတ်ပါတယ်။\n\nဗလာစာသားကို if ထဲထည့်ရင် မဝင်ပါ။",
          ["boolean", "condition"], CH),
        i("concept_qa", "Template literal ဆိုတာ ဘာလဲ?",
          "Template literal က backtick ` နဲ့ စာရေးပြီး ${} ထဲမှာ variable ထည့်ခြင်း ဖြစ်ပါတယ်။\n\nစာကြောင်းပေါင်းရ လွယ်ပါတယ်။ မျဉ်းပေါင်းလည်း ရပါတယ်။\n\nဥပမာ `Hello ${name}` ဖြစ်ပါတယ်။",
          ["string"], CH),
        i("explain_code", "ဒီ arrow function ကို ရှင်းပြပါ။",
          "ဒီ code က ကိန်းနှစ်လုံးပေါင်းတဲ့ function တို ဖြစ်ပါတယ်။\n\nconst add က နာမည်ဖြစ်ပါတယ်။ (a, b) က parameter ဖြစ်ပါတယ်။ a + b ကို တိုက်ရိုက် ပြန်ပါတယ်။\n\nadd(2, 3) က 5 ဖြစ်ပါတယ်။",
          ["function", "parameter"], CH,
          "const add = (a, b) => a + b;\nconsole.log(add(2, 3));"),
        i("explain_code", "ဒီ querySelector code ကို ရှင်းပြပါ။",
          "ဒီ code က ခေါင်းစဉ်စာသားကို ပြောင်းပါတယ်။\n\nquerySelector က ပထမ h1 ကို ရှာပါတယ်။ textContent က စာအသစ် တင်ပါတယ်။\n\nစာမျက်နှာပေါ်မှာ Welcome ဖြစ်သွားပါတယ်။",
          ["DOM"], CH,
          "const title = document.querySelector(\"h1\");\ntitle.textContent = \"Welcome\";"),
        i("explain_code", "ဒီ click listener ကို ရှင်းပြပါ။",
          "ဒီ code က ခလုတ်နှိပ်ရင် Clicked ပြပါတယ်။\n\ngetElementById က button ကို ရှာပါတယ်။ click ဖြစ်ရင် function အလုပ်လုပ်ပါတယ်။\n\nတစ်နှိပ်ချင်း console မှာ Clicked ထွက်ပါတယ်။",
          ["javascript"], CH,
          "const btn = document.getElementById(\"save\");\nbtn.addEventListener(\"click\", function () {\n  console.log(\"Clicked\");\n});"),
        i("explain_code", "ဒီ map code ကို ရှင်းပြပါ။",
          "ဒီ code က ဂဏန်းတိုင်းကို နှစ်ဆ လုပ်ပါတယ်။\n\nmap က array အသစ် ပြန်ပေးပါတယ်။ မူရင်း [1, 2, 3] မပျက်ပါ။\n\ndoubled က [2, 4, 6] ဖြစ်ပါတယ်။",
          ["array"], CH,
          "const nums = [1, 2, 3];\nconst doubled = nums.map(function (n) {\n  return n * 2;\n});\nconsole.log(doubled);"),
        i("explain_code", "ဒီ filter code ကို ရှင်းပြပါ။",
          "ဒီ code က ၁၀ နှင့်အထက် ဂဏန်းတွေကို ချန်ပါတယ်။\n\nfilter က မှန်တဲ့ တန်ဖိုးပဲ ထားပါတယ်။ ၅ က ထွက်ပါတယ်။\n\n[12, 20] ရပါတယ်။",
          ["array", "condition"], CH,
          "const scores = [5, 12, 20];\nconst passed = scores.filter(function (s) {\n  return s >= 10;\n});\nconsole.log(passed);"),
        i("explain_code", "ဒီ fetch then ကို ရှင်းပြပါ။",
          "ဒီ code က API က JSON ယူပါတယ်။\n\nfetch က request ပို့ပါတယ်။ ပထမ then က response ကို json ပြောင်းပါတယ်။ ဒုတိယ then က data သုံးပါတယ်။\n\nအမှားရှိရင် catch က ဖမ်းပါတယ်။",
          ["API", "JSON"], CH,
          "fetch(\"/api/user\")\n  .then(function (res) {\n    return res.json();\n  })\n  .then(function (data) {\n    console.log(data);\n  });"),
        i("explain_code", "ဒီ async await ကို ရှင်းပြပါ။",
          "ဒီ function က data ကို စောင့်ပြီးမှ ပြပါတယ်။\n\nasync က await သုံးခွင့်ပေးပါတယ်။ await fetch က အပြီးသတ်မှ ရှေ့ဆက်ပါတယ်။\n\nကုဒ်က အပေါ်ကနေ အောက်ကို ဖတ်ရ လွယ်ပါတယ်။",
          ["javascript", "API"], CH,
          "async function loadUser() {\n  const res = await fetch(\"/api/user\");\n  const data = await res.json();\n  console.log(data);\n}"),
        i("explain_code", "ဒီ JSON.parse ကို ရှင်းပြပါ။",
          "ဒီ code က JSON စာသားကို object ပြောင်းပါတယ်။\n\nparse မလုပ်ရင် စာသားသက်သက် ဖြစ်ပါတယ်။ ပြီးရင် name ကို ခေါ်လို့ရပါတယ်။\n\nAung ထွက်ပါတယ်။",
          ["JSON", "object"], CH,
          "const text = '{\"name\":\"Aung\"}';\nconst user = JSON.parse(text);\nconsole.log(user.name);"),
        i("explain_code", "ဒီ forEach ကို ရှင်းပြပါ။",
          "ဒီ code က သစ်သီးတိုင်းကို တစ်ကြောင်းစီ ပြပါတယ်။\n\nforEach က array ပေါ် လှည့်ပါတယ်။ တန်ဖိုးအသစ် မစုပါ။\n\napple နဲ့ mango ထွက်ပါတယ်။",
          ["array", "loop"], CH,
          "const fruits = [\"apple\", \"mango\"];\nfruits.forEach(function (fruit) {\n  console.log(fruit);\n});"),
        i("explain_code", "ဒီ ternary ကို ရှင်းပြပါ။",
          "ဒီ code က အသက်ပေါ်မူတည်ပြီး Adult သို့မဟုတ် Child ပေးပါတယ်။\n\n? : က if else တိုပုံ ဖြစ်ပါတယ်။ 20 က 18 နှင့်အထက်မို့ Adult ဖြစ်ပါတယ်။\n\nstatus ထဲမှာ Adult ရှိပါတယ်။",
          ["condition"], CH,
          "const age = 20;\nconst status = age >= 18 ? \"Adult\" : \"Child\";\nconsole.log(status);"),
        i("explain_code", "ဒီ spread array ကို ရှင်းပြပါ။",
          "ဒီ code က array နှစ်ခုကို ပေါင်းပါတယ်။\n\n... က အထဲက တန်ဖိုးတွေကို ဖြန့်ပါတယ်။ [1, 2, 3, 4] ရပါတယ်။\n\nမူရင်း array တွေ မပျက်ပါ။",
          ["array"], CH,
          "const a = [1, 2];\nconst b = [3, 4];\nconst all = [...a, ...b];\nconsole.log(all);"),
        i("explain_code", "ဒီ destructure ကို ရှင်းပြပါ။",
          "ဒီ code က object ထဲက name ကို တိုက်ရိုက် ယူပါတယ်။\n\n{} က key နဲ့ ကိုက်တဲ့ variable ထုတ်ပါတယ်။ user.name လို့ မရေးရပါ။\n\nMya ထွက်ပါတယ်။",
          ["object"], CH,
          "const user = { name: \"Mya\", age: 21 };\nconst { name } = user;\nconsole.log(name);"),
        i("explain_code", "ဒီ classList ကို ရှင်းပြပါ။",
          "ဒီ code က ခလုတ်ကို active class ပေါင်းထည့်ပါတယ်။\n\nclassList.add က CSS class ထည့်ပါတယ်။ ပုံစံပြောင်းနိုင်ပါတယ်။\n\nbutton ပေါ်မှာ active ရှိလာပါမယ်။",
          ["DOM", "css"], CH,
          "const btn = document.querySelector(\"button\");\nbtn.classList.add(\"active\");"),
        i("explain_code", "ဒီ preventDefault ကို ရှင်းပြပါ။",
          "ဒီ code က form မပို့ခင် စာမျက်နှာ ပြန်မရွှေ့အောင် တားပါတယ်။\n\nsubmit ဖြစ်ရင် ပုံမှန် refresh ဖြစ်တတ်ပါတယ်။ preventDefault က အဲဒါကို ရပ်ပါတယ်။\n\nJavaScript က data ကို ကိုယ်တိုင် ကိုင်နိုင်ပါတယ်။",
          ["javascript"], CH,
          "form.addEventListener(\"submit\", function (event) {\n  event.preventDefault();\n});"),
        i("explain_code", "ဒီ localStorage ကို ရှင်းပြပါ။",
          "ဒီ code က နာမည်ကို browser ထဲ သိမ်းပါတယ်။\n\nsetItem က သော့နဲ့ တန်ဖိုး သိမ်းပါတယ်။ refresh လုပ်ပြီး getItem နဲ့ ပြန်ယူနိုင်ပါတယ်။\n\nAung က သိမ်းထားပါတယ်။",
          ["javascript"], CH,
          "localStorage.setItem(\"name\", \"Aung\");\nconsole.log(localStorage.getItem(\"name\"));"),
        i("debug_explain", "ဒီ const ပြန်သတ်မှတ်တာကို ပြင်ပါ။",
          "const ကို ဒုတိယအကြိမ် သတ်မှတ်လို့မရပါ။\n\nပြင်ချင်ရင် let သုံးပါ။\n\nမှန်ကန်သော code:\nlet total = 10;\ntotal = 20;\nconsole.log(total);",
          ["variable", "syntax"], CH,
          "const total = 10;\ntotal = 20;"),
        i("debug_explain", "ဒီ querySelector null ကို ရှင်းပါ။",
          "sav မရှိလို့ null ရပြီး click ခေါ်လို့ error တက်ပါတယ်။\n\nid နာမည် မှန်အောင် ရေးရပါတယ်။\n\nမှန်ကန်သော code:\nconst btn = document.getElementById(\"save\");\nbtn.addEventListener(\"click\", function () {\n  console.log(\"ok\");\n});",
          ["DOM", "debug"], CH,
          "const btn = document.getElementById(\"sav\");\nbtn.addEventListener(\"click\", function () {\n  console.log(\"ok\");\n});"),
        i("debug_explain", "ဒီ == bug ကို ပြင်ပါ။",
          "== က အမျိုးအစား ပြောင်းပြီး နှိုင်းလို့ \"5\" နဲ့ 5 တူသွားပါတယ်။\n\nတိကျစစ်ချင်ရင် === သုံးပါ။\n\nမှန်ကန်သော code:\nconst value = \"5\";\nif (value === 5) {\n  console.log(\"same\");\n} else {\n  console.log(\"different\");\n}",
          ["operator", "condition"], CH,
          "const value = \"5\";\nif (value == 5) {\n  console.log(\"same\");\n}"),
        i("concept_qa", "undefined နဲ့ null ဘာကွာလဲ?",
          "undefined က တန်ဖိုး မပေးရသေးခြင်း၊ null က တမင် ဗလာထားခြင်း ဖြစ်ပါတယ်။\n\nvariable ကြေညာပြီး မထည့်ရင် undefined ဖြစ်ပါတယ်။ မရှိကြောင်း ပြချင်ရင် null ပေးပါတယ်။\n\nနှစ်ခုလုံး falsy ဖြစ်ပါတယ်။",
          ["variable"], CH),
        i("concept_qa", "Closure ဆိုတာ ဘာလဲ?",
          "Closure ဆိုတာ function က အပြင်က variable ကို မှတ်ထားနိုင်ခြင်း ဖြစ်ပါတယ်။\n\nခေါ်ပြီးရင်တောင် အဲဒီ တန်ဖိုး မပျောက်ပါ။ counter လို အရာမှာ သုံးပါတယ်။\n\nအတွင်း function က ပြင်ပ count ကို တိုးနိုင်ပါတယ်။",
          ["function"], CH),
        i("explain_code", "ဒီ closure counter ကို ရှင်းပြပါ။",
          "ဒီ code က ခေါ်တိုင်း ၁ တိုးတဲ့ counter ပေးပါတယ်။\n\ncount က အပြင်မှာ သိမ်းထားပါတယ်။ ပြန်ခေါ်တိုင်း မပျောက်ပါ။\n\nပထမ ၁၊ ဒုတိယ ၂ ထွက်ပါတယ်။",
          ["function"], CH,
          "function makeCounter() {\n  let count = 0;\n  return function () {\n    count = count + 1;\n    return count;\n  };\n}\nconst next = makeCounter();\nconsole.log(next());\nconsole.log(next());"),
        i("explain_code", "ဒီ setTimeout ကို ရှင်းပြပါ။",
          "ဒီ code က တစ်စက္ကန့်ကြာမှ Hello ပြပါတယ်။\n\nsetTimeout က စောင့်ပြီး function ခေါ်ပါတယ်။ 1000 က millisecond ဖြစ်ပါတယ်။\n\nချက်ချင်း မထွက်ပါ။",
          ["javascript"], CH,
          "setTimeout(function () {\n  console.log(\"Hello\");\n}, 1000);"),
        i("explain_code", "ဒီ array find ကို ရှင်းပြပါ။",
          "ဒီ code က id 2 ကို ရှာပါတယ်။\n\nfind က ပထမဆုံး ကိုက်တဲ့ object ပေးပါတယ်။ မတွေ့ရင် undefined ဖြစ်ပါတယ်။\n\nMya ရဲ့ object ထွက်ပါတယ်။",
          ["array", "object"], CH,
          "const users = [\n  { id: 1, name: \"Aung\" },\n  { id: 2, name: \"Mya\" }\n];\nconst found = users.find(function (u) {\n  return u.id === 2;\n});\nconsole.log(found.name);"),
        i("concept_qa", "Hoisting ဆိုတာ ဘာလဲ?",
          "Hoisting ဆိုတာ ကြေညာချက်တွေကို အပေါ်ဆွဲထားသလို အလုပ်လုပ်ခြင်း ဖြစ်ပါတယ်။\n\nvar က undefined ဖြစ်နိုင်ပါတယ်။ let နဲ့ const က အရင်သုံးရင် error တက်ပါတယ်။\n\nဒါကြောင့် အပေါ်မှာ ကြေညာသင့်ပါတယ်။",
          ["variable"], CH),
        i("explain_code", "ဒီ includes ကို ရှင်းပြပါ။",
          "ဒီ code က mango ပါမပါ စစ်ပါတယ်။\n\nincludes က ရှိရင် true ပေးပါတယ်။ mango ရှိလို့ true ထွက်ပါတယ်။\n\nindex မလိုပါ။",
          ["array"], CH,
          "const fruits = [\"apple\", \"mango\"];\nconsole.log(fruits.includes(\"mango\"));"),
        i("explain_code", "ဒီ Object.keys ကို ရှင်းပြပါ။",
          "ဒီ code က object ရဲ့ key နာမည်တွေကို list လုပ်ပါတယ်။\n\nkeys က array ပြန်ပေးပါတယ်။ name နဲ့ age ပါပါတယ်။\n\n['name', 'age'] ထွက်ပါတယ်။",
          ["object"], CH,
          "const user = { name: \"Su\", age: 19 };\nconsole.log(Object.keys(user));"),
        i("concept_qa", "Module export import က ဘာလဲ?",
          "Module က code ကို ဖိုင်ခွဲပြီး မျှဝေခြင်း ဖြစ်ပါတယ်။\n\nexport က ပို့၊ import က ယူပါတယ်။ ဖိုင်ရှည် မဖြစ်အောင် ကူပါတယ်။\n\nဥပမာ add function ကို math.js က ပို့နိုင်ပါတယ်။",
          ["function"], CH),
        i("explain_code", "ဒီ export default မဟုတ်တဲ့ function ကို ဘယ်လို နားလည်မလဲ?",
          "ဒီ code က add ကို အခြားဖိုင်က ယူသုံးနိုင်အောင် ပို့ပါတယ်။\n\nexport က နာမည်နဲ့ ပို့ပါတယ်။ import { add } လို့ ယူရပါတယ်။\n\n၂ နဲ့ ၃ ပေါင်းရင် ၅ ရပါတယ်။",
          ["function"], CH,
          "export function add(a, b) {\n  return a + b;\n}"),
        i("debug_explain", "ဒီ JSON.parse error ကို ရှင်းပါ။",
          "JSON မှာ key ကို double quote မသုံးလို့ parse မရပါ။\n\nမှန်ကန်တဲ့ JSON ပုံစံ သုံးရပါတယ်။\n\nမှန်ကန်သော code:\nconst user = JSON.parse('{\"name\":\"Aung\"}');\nconsole.log(user.name);",
          ["JSON", "syntax"], CH,
          "const user = JSON.parse(\"{name: 'Aung'}\");"),
        i("concept_qa", "Event bubbling ဆိုတာ ဘာလဲ?",
          "Event bubbling ဆိုတာ အတွင်း element က အဖြစ်က အပြင် parent ဆီ တက်သွားခြင်း ဖြစ်ပါတယ်။\n\nကလေးနှိပ်ရင် မိဘ listener လည်း ကြားနိုင်ပါတယ်။ မလိုရင် stopPropagation သုံးပါတယ်။\n\nစာရင်းထဲက item တွေမှာ အသုံးဝင်ပါတယ်။",
          ["javascript", "DOM"], CH),
        i("explain_code", "ဒီ innerHTML ကို ရှင်းပြပါ။",
          "ဒီ code က သေတ္တာထဲ HTML ထည့်ပါတယ်။\n\ninnerHTML က tag တွေကို ဖော်ပါတယ်။ <b> က စာလုံးမည်း ဖြစ်ပါတယ်။\n\nHello မည်းမည်း ပေါ်ပါတယ်။",
          ["DOM"], CH,
          "box.innerHTML = \"<b>Hello</b>\";"),
        i("concept_qa", "innerHTML ကို ဘာကြောင့် သတိထားရလဲ?",
          "User စာကို တိုက်ရိုက် innerHTML ထည့်ရင် မကောင်းတဲ့ script ဝင်နိုင်ပါတယ်။\n\ntextContent က စာသားသက်သက်မို့ ပိုလုံခြုံပါတယ်။ ယုံကြည်ရတဲ့ HTML မှသာ သုံးသင့်ပါတယ်။\n\nလုံခြုံရေးအတွက် အရေးကြီးပါတယ်။",
          ["DOM"], CH),
        i("explain_code", "ဒီ reduce ကို ရှင်းပြပါ။",
          "ဒီ code က ဂဏန်းအားလုံး ပေါင်းပါတယ်။\n\nreduce က စုစုပေါင်း တစ်ခု ထုတ်ပါတယ်။ စ ၀ ကနေ တစ်ခုချင်း ပေါင်းပါတယ်။\n\n၆ ရပါတယ်။",
          ["array"], CH,
          "const nums = [1, 2, 3];\nconst sum = nums.reduce(function (total, n) {\n  return total + n;\n}, 0);\nconsole.log(sum);"),
        i("explain_code", "ဒီ optional chaining ကို ရှင်းပြပါ။",
          "ဒီ code က address မရှိရင် error မတက်အောင် ခေါ်ပါတယ်။\n\n?. က မရှိရင် undefined ပေးပါတယ်။ city မရှိလို့ undefined ထွက်ပါတယ်။\n\nuser.address.city တိုက်ရိုက်ခေါ်ရင် ပျက်နိုင်ပါတယ်။",
          ["object"], CH,
          "const user = { name: \"Aung\" };\nconsole.log(user.address?.city);"),
        i("concept_qa", "NaN ဆိုတာ ဘာလဲ?",
          "NaN ဆိုတာ ဂဏန်းမဟုတ်တဲ့ တွက်ချက်မှု ရလဒ် ဖြစ်ပါတယ်။\n\n\"hi\" ကို ဂဏန်းလုပ်ရင် ဖြစ်တတ်ပါတယ်။ Number.isNaN နဲ့ စစ်ပါတယ်။\n\nNaN === NaN က false မို့ သတိထားရပါတယ်။",
          ["javascript"], CH),
        i("explain_code", "ဒီ Number.isNaN ကို ရှင်းပြပါ။",
          "ဒီ code က ပြောင်းလို့မရတဲ့ တန်ဖိုးကို ဖမ်းပါတယ်။\n\nNumber(\"hi\") က NaN ဖြစ်ပါတယ်။ isNaN က true ပေးပါတယ်။\n\nInvalid ထွက်ပါတယ်။",
          ["javascript"], CH,
          "const n = Number(\"hi\");\nif (Number.isNaN(n)) {\n  console.log(\"Invalid\");\n}"),
        i("explain_code", "ဒီ array push ကို ရှင်းပြပါ။",
          "ဒီ code က list အဆုံးမှာ mango ထည့်ပါတယ်။\n\npush က မူရင်း array ကို ပြင်ပါတယ်။ အရှည် ၃ ဖြစ်ပါတယ်။\n\n['apple', 'banana', 'mango'] ရပါတယ်။",
          ["array"], CH,
          "const fruits = [\"apple\", \"banana\"];\nfruits.push(\"mango\");\nconsole.log(fruits);"),
        i("debug_explain", "ဒီ for loop ရပ်ချက် မှားတာကို ပြင်ပါ။",
          "i > 3 ဆိုရင် စမှာ ၀ က ၃ ထက် မကြီးလို့ တစ်ခါမှ မဝင်ပါ။\n\nငယ်နေသ၍ လှည့်ချင်ရင် i < 3 သုံးပါ။\n\nမှန်ကန်သော code:\nfor (let i = 0; i < 3; i = i + 1) {\n  console.log(i);\n}",
          ["loop"], CH,
          "for (let i = 0; i > 3; i = i + 1) {\n  console.log(i);\n}"),
        i("concept_qa", "console.log ကို ဘာကြောင့် သုံးသလဲ?",
          "console.log က တန်ဖိုးကို developer tool မှာ ပြပါတယ်။\n\nမှားနေတဲ့ အဆင့်ကို ရှာဖို့ အထောက်အကူ ဖြစ်ပါတယ်။ သုံးသူမျက်နှာပြင်မှာ မပေါ်ပါ။\n\nDebug လုပ်တဲ့အခါ အရေးကြီးပါတယ်။",
          ["debug"], CH),
        i("explain_code", "ဒီ Date code ကို ရှင်းပြပါ။",
          "ဒီ code က ယနေ့ခုနှစ်ကို ပြပါတယ်။\n\nnew Date() က လက်ရှိအချိန် ယူပါတယ်။ getFullYear က ခုနှစ် ထုတ်ပါတယ်။\n\n2026 လို ဂဏန်း ထွက်ပါတယ်။",
          ["javascript"], CH,
          "const now = new Date();\nconsole.log(now.getFullYear());"),
        i("concept_qa", "Strict equality === ဘာကြောင့် ပိုကောင်းလဲ?",
          "=== က အမျိုးအစား မပြောင်းဘဲ တိတိကျကျ နှိုင်းပါတယ်။\n\n== က မျှော်လင့်မထားတဲ့ တူညီမှု ဖြစ်နိုင်ပါတယ်။ Bug နည်းစေပါတယ်။\n\n\"5\" နဲ့ 5 ကို မတူဘူးလို့ မြင်စေပါတယ်။",
          ["operator"], CH),
        i("explain_code", "ဒီ switch ကို ရှင်းပြပါ။",
          "ဒီ code က role ပေါ်မူတည်ပြီး စာပြပါတယ်။\n\nadmin ကိုက်လို့ Admin panel ထွက်ပါတယ်။ break က နောက် case မဆက်အောင် ရပ်ပါတယ်။\n\nမကိုက်ရင် default သုံးပါတယ်။",
          ["condition"], CH,
          "const role = \"admin\";\nswitch (role) {\n  case \"admin\":\n    console.log(\"Admin panel\");\n    break;\n  default:\n    console.log(\"User panel\");\n}"),
        i("explain_code", "ဒီ try catch ကို ရှင်းပြပါ။",
          "ဒီ code က JSON မှားရင် program မပျက်အောင် ဖမ်းပါတယ်။\n\nparse မရလို့ catch ဝင်ပါတယ်။ Invalid JSON ပြပါတယ်။\n\nအသုံးပြုသူကို ရှင်းပြနိုင်ပါတယ်။",
          ["debug", "JSON"], CH,
          "try {\n  JSON.parse(\"{bad\");\n} catch (error) {\n  console.log(\"Invalid JSON\");\n}"),
        i("concept_qa", "Callback ဆိုတာ ဘာလဲ?",
          "Callback ဆိုတာ အလုပ်ပြီးမှ ခေါ်ခိုင်းတဲ့ function ဖြစ်ပါတယ်။\n\nအချိန်ယူတဲ့ အလုပ်မှာ သုံးပါတယ်။ များလာရင် ဖတ်ရ ခက်နိုင်ပါတယ်။\n\nPromise က ဒီပြဿနာကို လျှော့ပေးပါတယ်။",
          ["function"], CH),
        i("explain_code", "ဒီ callback ဥပမာကို ရှင်းပြပါ။",
          "ဒီ code က ကြိုဆိုပြီးမှ ပြီးကြောင်း ခေါ်ပါတယ်။\n\ndone က နောက်မှ အလုပ်လုပ်တဲ့ function ဖြစ်ပါတယ်။ Hello Su ပြပြီး Done ထွက်ပါတယ်။\n\nအစဉ်အတိုင်း နှစ်ဆင့် ဖြစ်ပါတယ်။",
          ["function"], CH,
          "function greet(name, done) {\n  console.log(\"Hello \" + name);\n  done();\n}\ngreet(\"Su\", function () {\n  console.log(\"Done\");\n});"),
    ]
