from .common import item as i

CH = "Laravel အခြေခံ"


def samples():
    return [
        i("concept_qa", "Laravel ဆိုတာ ဘာလဲ?",
          "Laravel ဆိုတာ PHP ဝက်ဘ် framework ဖြစ်ပါတယ်။\n\nrouting၊ database၊ လုံခြုံရေးကို စနစ်တကျ ပေးပါတယ်။ MVC ပုံစံ လိုက်ပါတယ်။\n\nဝက်ဘ်အက်ပ်ကို မြန်မြန် စနိုင်ပါတယ်။",
          ["laravel"], CH),
        i("concept_qa", "Artisan ဆိုတာ ဘာလဲ?",
          "Artisan က Laravel ရဲ့ command line ကိရိယာ ဖြစ်ပါတယ်။\n\ncontroller၊ migration စတာတွေ ဖန်တီးနိုင်ပါတယ်။ ထပ်တလဲလဲ အလုပ်ကို လျှော့ပါတယ်။\n\nဥပမာ php artisan make:model Post ဖြစ်ပါတယ်။",
          ["laravel"], CH),
        i("concept_qa", "Route ဆိုတာ ဘာလဲ?",
          "Route က URL နဲ့ function/controller ကို ချိတ်ပေးပါတယ်။\n\nGET /users က စာရင်းပြနိုင်ပါတယ်။ နာမည်ပေးထားရင် view ကနေ ခေါ်ရ လွယ်ပါတယ်။\n\nweb.php ထဲမှာ ရေးတတ်ပါတယ်။",
          ["route"], CH),
        i("concept_qa", "Eloquent ဆိုတာ ဘာလဲ?",
          "Eloquent က Laravel ရဲ့ ORM ဖြစ်ပါတယ်။\n\nSQL ကို object ပုံစံနဲ့ ရေးစေပါတယ်။ User::all() လို ခေါ်နိုင်ပါတယ်။\n\nဆက်စပ်မှုကို hasMany လို သတ်မှတ်ပါတယ်။",
          ["Eloquent", "database"], CH),
        i("concept_qa", "Migration ဆိုတာ ဘာလဲ?",
          "Migration က database ဖွဲ့စည်းပုံကို code နဲ့ မှတ်ခြင်း ဖြစ်ပါတယ်။\n\nအဖွဲ့လိုက် တူညီအောင် မျှဝေနိုင်ပါတယ်။ ပြန်ဆုတ်လို့ရပါတယ်။\n\nphp artisan migrate နဲ့ အလုပ်လုပ်ပါတယ်။",
          ["migration"], CH),
        i("concept_qa", "Blade ဆိုတာ ဘာလဲ?",
          "Blade က Laravel ရဲ့ template ဘာသာ ဖြစ်ပါတယ်။\n\n{{ }} က စာကို လုံခြုံစွာ ပြပါတယ်။ @if၊ @foreach နဲ့ ထိန်းပါတယ်။\n\nlayout ကို @extends နဲ့ မျှဝေပါတယ်။",
          ["blade"], CH),
        i("concept_qa", "Middleware ဆိုတာ ဘာလဲ?",
          "Middleware က request မရောက်ခင် စစ်ဆေးတဲ့ အလွှာ ဖြစ်ပါတယ်။\n\nlogin ဖြစ်မှ ရှေ့ဆက်ခွင့်ပေးနိုင်ပါတယ်။ CSRF စစ်တာလည်း middleware ဖြစ်ပါတယ်။\n\nRoute မှာ တပ်ဆင်ပါတယ်။",
          ["middleware"], CH),
        i("concept_qa", "CSRF token ဘာကြောင့် လိုသလဲ?",
          "အခြားဆိုက်က user အစား form ပို့တာကို တားပါတယ်။\n\nBlade မှာ @csrf ထည့်ရပါတယ်။ token မကိုက်ရင် request ပယ်ပါတယ်။\n\nPOST form တိုင်းလိုလို လိုပါတယ်။",
          ["form", "middleware"], CH),
        i("explain_code", "ဒီ Route::get ကို ရှင်းပြပါ။",
          "ဒီ route က /hello ကို ဖွင့်ရင် Hello ပြပါတယ်။\n\nGET request ကို လက်ခံပါတယ်။ closure က တိုက်ရိုက် စာပြန်ပါတယ်။\n\nဘရောက်ဇာမှာ Hello ပေါ်ပါတယ်။",
          ["route"], CH,
          "Route::get('/hello', function () {\n    return 'Hello';\n});"),
        i("explain_code", "ဒီ controller route ကို ရှင်းပြပါ။",
          "ဒီ route က /posts ကို PostController@index နဲ့ ချိတ်ပါတယ်။\n\nစာရင်းပြတဲ့ method ကို ခေါ်ပါတယ်။ ကုဒ်ခွဲရ ရှင်းပါတယ်။\n\nposts စာမျက်နှာ ပွင့်ပါတယ်။",
          ["route"], CH,
          "Route::get('/posts', [PostController::class, 'index']);"),
        i("explain_code", "ဒီ Eloquent all ကို ရှင်းပြပါ။",
          "ဒီ code က posts အကုန် ယူပါတယ်။\n\nPost model က table နဲ့ ချိတ်ပါတယ်။ all() က collection ပြန်ပေးပါတယ်။\n\nview ဆီ ပို့ပြီး စာရင်းပြနိုင်ပါတယ်။",
          ["Eloquent"], CH,
          "public function index() {\n    $posts = Post::all();\n    return view('posts.index', compact('posts'));\n}"),
        i("explain_code", "ဒီ where first ကို ရှင်းပြပါ။",
          "ဒီ code က id 3 ကို ရှာပါတယ်။\n\nfirst() က တစ်ကြောင်းပဲ ယူပါတယ်။ မတွေ့ရင် null ဖြစ်နိုင်ပါတယ်။\n\nအဲဒီ post ကို ပြနိုင်ပါတယ်။",
          ["Eloquent", "query"], CH,
          "$post = Post::where('id', 3)->first();"),
        i("explain_code", "ဒီ create ကို ရှင်းပြပါ။",
          "ဒီ code က ပို့စ်အသစ် သိမ်းပါတယ်။\n\ncreate က fillable field တွေကို ထည့်ပါတယ်။ title နဲ့ body ကျပါတယ်။\n\nစာရင်းထဲ ပို့စ်အသစ် ပေါ်ပါတယ်။",
          ["Eloquent"], CH,
          "Post::create([\n    'title' => 'Hello',\n    'body' => 'My first post',\n]);"),
        i("explain_code", "ဒီ Blade loop ကို ရှင်းပြပါ။",
          "ဒီ template က ပို့စ်တိုင်းရဲ့ ခေါင်းစဉ် ပြပါတယ်။\n\n@foreach က list လှည့်ပါတယ်။ {{ }} က escape လုပ်ပါတယ်။\n\nခေါင်းစဉ်တွေ စာရင်းပေါ်ပါတယ်။",
          ["blade"], CH,
          "@foreach ($posts as $post)\n  <h2>{{ $post->title }}</h2>\n@endforeach"),
        i("explain_code", "ဒီ @csrf form ကို ရှင်းပြပါ။",
          "ဒီ form က ပို့စ်အသစ် ပို့ပါတယ်။\n\n@csrf က လုံခြုံရေး token ထည့်ပါတယ်။ POST က store route ကို သွားပါတယ်။\n\ntoken မပါရင် 419 error တက်နိုင်ပါတယ်။",
          ["blade", "form"], CH,
          "<form method=\"POST\" action=\"/posts\">\n  @csrf\n  <input name=\"title\">\n  <button>Save</button>\n</form>"),
        i("explain_code", "ဒီ migration up ကို ရှင်းပြပါ။",
          "ဒီ migration က posts table တည်ဆောက်ပါတယ်။\n\nid၊ title၊ timestamps ပါပါတယ်။ string က VARCHAR ဖြစ်ပါတယ်။\n\nmigrate လုပ်ရင် table ပေါ်ပါတယ်။",
          ["migration"], CH,
          "Schema::create('posts', function (Blueprint $table) {\n    $table->id();\n    $table->string('title');\n    $table->timestamps();\n});"),
        i("explain_code", "ဒီ validation ကို ရှင်းပြပါ။",
          "ဒီ code က title မဖြစ်မနေ ရှိရမယ်လို့ စစ်ပါတယ်။\n\nrequired က ဗလာမခံပါ။ မှားရင် ပြန်ပို့ပြီး error ပြပါတယ်။\n\nမှန်မှသာ ရှေ့ဆက်ပါတယ်။",
          ["form", "laravel"], CH,
          "$request->validate([\n    'title' => 'required|max:100',\n]);"),
        i("explain_code", "ဒီ auth middleware ကို ရှင်းပြပါ။",
          "ဒီ route က login ဝင်သူပဲ ကြည့်ခွင့်ရပါတယ်။\n\nmiddleware auth က မဝင်ရင် login ကို ပို့ပါတယ်။\n\ndashboard က ကာကွယ်ထားပါတယ်။",
          ["middleware", "route"], CH,
          "Route::get('/dashboard', function () {\n    return view('dashboard');\n})->middleware('auth');"),
        i("explain_code", "ဒီ hasMany ကို ရှင်းပြပါ။",
          "ဒီ relation က user တစ်ယောက်မှာ ပို့စ်အများ ရှိနိုင်ကြောင်း ပြပါတယ်။\n\nhasMany က one-to-many ဖြစ်ပါတယ်။ $user->posts နဲ့ ခေါ်နိုင်ပါတယ်။\n\nဆက်စပ် row တွေ ရပါတယ်။",
          ["Eloquent"], CH,
          "public function posts() {\n    return $this->hasMany(Post::class);\n}"),
        i("explain_code", "ဒီ belongsTo ကို ရှင်းပြပါ။",
          "ဒီ relation က ပို့စ်တစ်ခုက user တစ်ယောက်နဲ့ ဆိုင်ကြောင်း ပြပါတယ်။\n\n$post->user က ပိုင်ရှင်ကို ပေးပါတယ်။ foreign key က user_id ဖြစ်တတ်ပါတယ်။\n\nနာမည်ကို တွဲပြနိုင်ပါတယ်။",
          ["Eloquent", "foreign key"], CH,
          "public function user() {\n    return $this->belongsTo(User::class);\n}"),
        i("debug_explain", "ဒီ CSRF ပျောက်တဲ့ form ကို ပြင်ပါ။",
          "@csrf မထည့်လို့ POST က ပယ်ခံရနိုင်ပါတယ်။\n\nBlade form ထဲမှာ token ထည့်ရပါတယ်။\n\nမှန်ကန်သော code:\n<form method=\"POST\" action=\"/posts\">\n  @csrf\n  <input name=\"title\">\n</form>",
          ["form", "blade"], CH,
          "<form method=\"POST\" action=\"/posts\">\n  <input name=\"title\">\n</form>"),
        i("debug_explain", "ဒီ mass assignment ကို ပြင်ပါ။",
          "fillable မထားလို့ create က တန်ဖိုး မသိမ်းနိုင်ပါ။\n\nmodel မှာ fillable ကြေညာရပါတယ်။\n\nမှန်ကန်သော code:\nclass Post extends Model {\n    protected $fillable = ['title', 'body'];\n}",
          ["Eloquent"], CH,
          "Post::create(['title' => 'Hi', 'body' => 'Text']);"),
        i("concept_qa", "Service container ဆိုတာ ဘာလဲ?",
          "Service container က class တွေကို ဖန်တီးပေး၊ ဝေမျှပေးတဲ့ သေတ္တာ ဖြစ်ပါတယ်။\n\ndependency ကို အလိုအလျောက် ထည့်ပေးနိုင်ပါတယ်။ စမ်းသပ်ရ လွယ်ပါတယ်။\n\nLaravel ရဲ့ အူတိုင် ဖြစ်ပါတယ်။",
          ["laravel"], CH),
        i("concept_qa", ".env ဖိုင်က ဘာလုပ်သလဲ?",
          ".env က လျှို့ဝှက် ဆက်တင်တွေကို ပတ်ဝန်းကျင်အလိုက် သိမ်းပါတယ်။\n\nDB password၊ APP_KEY တို့ ပါပါတယ်။ git မှာ မတင်သင့်ပါ။\n\nconfig() ကနေ ဖတ်ပါတယ်။",
          ["laravel"], CH),
        i("explain_code", "ဒီ env read ကို ရှင်းပြပါ။",
          "ဒီ code က app နာမည်ကို .env က ယူပါတယ်။\n\nenv helper က APP_NAME ဖတ်ပါတယ်။ မရှိရင် Laravel မူရင်း သုံးနိုင်ပါတယ်။\n\nစာမျက်နှာခေါင်းမှာ ပြနိုင်ပါတယ်။",
          ["laravel"], CH,
          "$name = env('APP_NAME');"),
        i("explain_code", "ဒီ Route model binding ကို ရှင်းပြပါ။",
          "ဒီ method က URL ထဲက post ကို အလိုအလျောက် ရှာပေးပါတယ်။\n\nPost $post က id နဲ့ row ယူပါတယ်။ မတွေ့ရင် 404 ဖြစ်ပါတယ်။\n\nကုဒ်တိုပြီး ရှင်းပါတယ်။",
          ["route", "Eloquent"], CH,
          "public function show(Post $post) {\n    return view('posts.show', compact('post'));\n}"),
        i("explain_code", "ဒီ paginate ကို ရှင်းပြပါ။",
          "ဒီ code က တစ်မျက်နှာ ၁၀ ပို့စ် ခွဲပါတယ်။\n\npaginate က လမ်းညွှန်လင့်တွေ ပေးပါတယ်။ Blade မှာ links() ခေါ်ပါတယ်။\n\nစာရင်းရှည်ရင် အဆင်ပြေပါတယ်။",
          ["Eloquent"], CH,
          "$posts = Post::paginate(10);"),
        i("concept_qa", "Seeder ဆိုတာ ဘာလဲ?",
          "Seeder က စမ်းသပ် data ထည့်တဲ့ class ဖြစ်ပါတယ်။\n\nဖွံ့ဖြိုးချိန်မှာ ဥပမာ user တွေ လိုပါတယ်။ artisan db:seed နဲ့ ခေါ်ပါတယ်။\n\nလက်နဲ့ INSERT များများ မလုပ်ရပါ။",
          ["database"], CH),
        i("explain_code", "ဒီ factory create ကို ရှင်းပြပါ။",
          "ဒီ code က ဥပမာ user ၁၀ ယောက် ထုတ်ပါတယ်။\n\nfactory က အတုအယောင် data ပေးပါတယ်။ စမ်းသပ်မှု အတွက် မြန်ပါတယ်။\n\nusers table မှာ ၁၀ ကြောင်း ပေါ်ပါတယ်။",
          ["database"], CH,
          "User::factory()->count(10)->create();"),
        i("debug_explain", "ဒီ view မတွေ့တာကို ရှင်းပါ။",
          "view နာမည်နဲ့ ဖိုင်နေရာ မကိုက်လို့ error တက်ပါတယ်။\n\nresources/views/posts/index.blade.php ရှိရပါတယ်။\n\nမှန်ကန်သော code:\nreturn view('posts.index');",
          ["blade"], CH,
          "return view('post.index');"),
        i("concept_qa", "Queue ဆိုတာ ဘာလဲ?",
          "Queue က အချိန်ယူတဲ့ အလုပ်ကို နောက်မှ လုပ်ခိုင်းခြင်း ဖြစ်ပါတယ်။\n\nအီးမေးလ်ပို့တာကို request ထဲမှာ မစောင့်ရပါ။ job class ရေးပါတယ်။\n\nအသုံးပြုသူ စောင့်ချိန် လျော့ပါတယ်။",
          ["laravel"], CH),
        i("explain_code", "ဒီ Mail send ကို ရှင်းပြပါ။",
          "ဒီ code က user ဆီ အီးမေးလ် ပို့ပါတယ်။\n\nMail::to က လိပ်စာ ပေးပါတယ်။ WelcomeMail က ပုံစံ ဖြစ်ပါတယ်။\n\nစာပို့စာရင်းထဲ ရောက်ပါတယ်။",
          ["laravel"], CH,
          "Mail::to($user->email)->send(new WelcomeMail($user));"),
        i("explain_code", "ဒီ auth user ကို ရှင်းပြပါ။",
          "ဒီ code က လက်ရှိ login user ကို ယူပါတယ်။\n\nauth()->user() က session ကနေ ဖတ်ပါတယ်။ မဝင်ရင် null ဖြစ်နိုင်ပါတယ်။\n\nနာမည်ကို ပြနိုင်ပါတယ်။",
          ["laravel"], CH,
          "$user = auth()->user();\nreturn $user->name;"),
        i("concept_qa", "Policy ဆိုတာ ဘာလဲ?",
          "Policy က ဘယ်သူ ဘာလုပ်ခွင့်ရှိလဲ ဆုံးဖြတ်ပါတယ်။\n\nကိုယ့်ပို့စ်ကိုပဲ ပြင်ခွင့်ပေးနိုင်ပါတယ်။ controller ထဲမှာ authorize ခေါ်ပါတယ်။\n\nလုံခြုံရေးကို တစ်နေရာတည်းမှာ ထားပါတယ်။",
          ["laravel"], CH),
        i("explain_code", "ဒီ authorize ကို ရှင်းပြပါ။",
          "ဒီ code က ပို့စ်ပြင်ခွင့် ရှိမရှိ စစ်ပါတယ်။\n\nမရှိရင် 403 ဖြစ်ပါတယ်။ policy က ဆုံးဖြတ်ပါတယ်။\n\nခွင့်ရှိမှ update ဆက်လုပ်ပါတယ်။",
          ["laravel"], CH,
          "$this->authorize('update', $post);"),
        i("explain_code", "ဒီ with eager load ကို ရှင်းပြပါ။",
          "ဒီ code က ပို့စ်တွေနဲ့အတူ user ကို တစ်ခါတည်း ယူပါတယ်။\n\nN+1 query ကို လျှော့ပါတယ်။ with('user') က ဆက်စပ်မှု ကြိုခေါ်ပါတယ်။\n\nစာရင်းပြ မြန်ပါတယ်။",
          ["Eloquent"], CH,
          "$posts = Post::with('user')->get();"),
        i("debug_explain", "ဒီ N+1 ကို ဘယ်လို ပြင်မလဲ?",
          "loop ထဲမှာ $post->user ခေါ်ရင် query များပါတယ်။\n\nအရင် with နဲ့ ခေါ်ပါ။\n\nမှန်ကန်သော code:\n$posts = Post::with('user')->get();",
          ["Eloquent", "debug"], CH,
          "$posts = Post::all();\nforeach ($posts as $post) {\n    echo $post->user->name;\n}"),
        i("concept_qa", "Resource controller ဆိုတာ ဘာလဲ?",
          "Resource controller က index၊ store၊ update၊ destroy စတဲ့ စံ method တွေ ပါပါတယ်။\n\nREST ပုံစံ route တွေ အလိုအလျောက် ရပါတယ်။\n\nCRUD အတွက် အချိန်ကုန် သက်သာပါတယ်။",
          ["route"], CH),
        i("explain_code", "ဒီ resource route ကို ရှင်းပြပါ။",
          "ဒီစာကြောင်းက posts အတွက် CRUD route များ ထုတ်ပါတယ်။\n\n/posts၊ /posts/{post} စတာတွေ ရပါတယ်။ controller method တွေနဲ့ ကိုက်ပါတယ်။\n\nphp artisan route:list နဲ့ ကြည့်နိုင်ပါတယ်။",
          ["route"], CH,
          "Route::resource('posts', PostController::class);"),
        i("explain_code", "ဒီ soft delete ကို ရှင်းပြပါ။",
          "ဒီ code က row ကို တကယ်မဖျက်ဘဲ မှတ်ထားပါတယ်။\n\ndeleted_at ရှိရင် ဖျက်ပြီးသားလို့ မြင်ပါတယ်။ ပြန်ယူလို့ရပါတယ်။\n\nမှားဖျက်တာ ကယ်တင်နိုင်ပါတယ်။",
          ["Eloquent"], CH,
          "use SoftDeletes;"),
        i("concept_qa", "Vite ကို Laravel မှာ ဘာကြောင့် သုံးသလဲ?",
          "Vite က CSS/JS ကို မြန်မြန် တည်ဆောက်ပေးပါတယ်။\n\nဖွံ့ဖြိုးချိန်မှာ ပြောင်းတာ ချက်ချင်း မြင်ရပါတယ်။ Blade မှာ @vite ခေါ်ပါတယ်။\n\nခေတ်သစ် frontend အတွက် သင့်တော်ပါတယ်။",
          ["laravel"], CH),
        i("explain_code", "ဒီ request only ကို ရှင်းပြပါ။",
          "ဒီ code က title နဲ့ body ပဲ ယူပါတယ်။\n\nonly က မလိုအပ်တဲ့ field မဝင်အောင် ကာပါတယ်။ create ဆီ ပို့ပါတယ်။\n\nပိုလုံခြုံပါတယ်။",
          ["form", "laravel"], CH,
          "$data = $request->only(['title', 'body']);\nPost::create($data);"),
        i("debug_explain", "ဒီ 419 page ကို ဘယ်လို ကာကွယ်မလဲ?",
          "419 က CSRF မအောင်မြင်တာ များပါတယ်။\n\nform မှာ @csrf ထည့်ပါ။ ajax ဆိုရင် token header ပို့ပါ။\n\nမှန်ကန်သော code:\n<form method=\"POST\" action=\"/logout\">\n  @csrf\n  <button>Logout</button>\n</form>",
          ["middleware", "form"], CH,
          "<form method=\"POST\" action=\"/logout\">\n  <button>Logout</button>\n</form>"),
        i("concept_qa", "Tinker ဆိုတာ ဘာလဲ?",
          "Tinker က Laravel ကို command line မှာ စမ်းတဲ့ REPL ဖြစ်ပါတယ်။\n\nUser::count() လို အမြန် စစ်နိုင်ပါတယ်။ browser မဖွင့်ရပါ။\n\ndebug အတွက် အဆင်ပြေပါတယ်။",
          ["laravel"], CH),
        i("explain_code", "ဒီ latest order ကို ရှင်းပြပါ။",
          "ဒီ query က နောက်ဆုံးပို့စ် အရင် ပြပါတယ်။\n\nlatest() က created_at ကို ကြီးရာက စပါတယ်။ take(5) က ၅ ခုပဲ ယူပါတယ်။\n\nပင်မစာမျက်နှာအတွက် သုံးပါတယ်။",
          ["Eloquent"], CH,
          "$posts = Post::latest()->take(5)->get();"),
    ]
