from .common import item as i

CH = "PHP အခြေခံ"


def samples():
    return [
        i("concept_qa", "PHP ဆိုတာ ဘာလဲ?",
          "PHP ဆိုတာ server မှာ အလုပ်လုပ်တဲ့ ဝက်ဘ် programming language ဖြစ်ပါတယ်။\n\nHTML ထဲမှာ ရောရေးနိုင်ပါတယ်။ Database နဲ့ တွဲပြီး dynamic စာမျက်နှာ လုပ်ပါတယ်။\n\nဥပမာ login ပြီးမှ နာမည်ပြတဲ့ စာမျက်နှာ ရေးနိုင်ပါတယ်။",
          ["php"], CH),
        i("concept_qa", "PHP variable ကို ဘယ်လို ရေးသလဲ?",
          "PHP variable က $ နဲ့ စပါတယ်။\n\n$name = \"Aung\"; လို ရေးပါတယ်။ နာမည်က စာလုံး အsensitive ဖြစ်ပါတယ်။\n\nမကြေညာဘဲ သုံးရင် သတိပေးချက် ထွက်နိုင်ပါတယ်။",
          ["variable"], CH),
        i("concept_qa", "GET နဲ့ POST ဘာကွာလဲ?",
          "GET က လိပ်စာမှာ ပါသွားပြီး POST က ကိုယ်ထဲ ပို့ပါတယ်။\n\nရှာဖွေမှုကို GET၊ လျှို့ဝှက် သို့မဟုတ် များတဲ့ data ကို POST သုံးသင့်ပါတယ်။ Form method နဲ့ ရွေးပါတယ်။\n\nPassword ကို GET နဲ့ မပို့သင့်ပါ။",
          ["GET", "POST", "form"], CH),
        i("concept_qa", "Associative array ဆိုတာ ဘာလဲ?",
          "Associative array က နာမည် key နဲ့ တန်ဖိုး တွဲသိမ်းပါတယ်။\n\nဂဏန်း index မဟုတ်ပါ။ $user[\"name\"] လို ခေါ်ပါတယ်။\n\nForm data နဲ့ database row ကို ကိုယ်စားပြုရာမှာ အဆင်ပြေပါတယ်။",
          ["array"], CH),
        i("concept_qa", "Session ဆိုတာ ဘာလဲ?",
          "Session ဆိုတာ user တစ်ယောက်ရဲ့ ယာယီ အချက်အလက်ကို server မှာ မှတ်ခြင်း ဖြစ်ပါတယ်။\n\nLogin ပြီးကြောင်း မှတ်နိုင်ပါတယ်။ စာမျက်နှာ ပြောင်းလည်း မပျောက်ပါ။\n\n$_SESSION နဲ့ သုံးပါတယ်။",
          ["session"], CH),
        i("concept_qa", "Cookie ဆိုတာ ဘာလဲ?",
          "Cookie ဆိုတာ browser မှာ သေးငယ်တဲ့ အချက် သိမ်းခြင်း ဖြစ်ပါတယ်။\n\nSession ထက် ကြာကြာ နေနိုင်ပါတယ်။ လျှို့ဝှက်ချက် မထည့်သင့်ပါ။\n\nဥပမာ ဘာသာစကား ရွေးချယ်မှု မှတ်နိုင်ပါတယ်။",
          ["cookie"], CH),
        i("concept_qa", "include နဲ့ require ဘာကွာလဲ?",
          "နှစ်ခုလုံး တခြားဖိုင် ခေါ်ပါတယ်။ require က ဖိုင်မရှိရင် ရပ်ပါတယ်။\n\ninclude က သတိပေးပြီး ဆက်နိုင်ပါတယ်။ အရေးကြီး config ကို require သုံးသင့်ပါတယ်။\n\nheader.php ကို ခေါ်သုံးလို့ရပါတယ်။",
          ["php"], CH),
        i("concept_qa", "Prepared statement ဘာကြောင့် လိုသလဲ?",
          "Prepared statement က SQL ထဲကို user စာ တိုက်ရိုက် မထည့်အောင် ကာကွယ်ပါတယ်။\n\nSQL injection ကို လျှော့ပါတယ်။ placeholder နဲ့ တန်ဖိုး ခွဲပို့ပါတယ်။\n\nLogin form မှာ မဖြစ်မနေ သုံးသင့်ပါတယ်။",
          ["query"], CH),
        i("explain_code", "ဒီ echo code ကို ရှင်းပြပါ။",
          "ဒီ code က Hello Aung ကို browser မှာ ပြပါတယ်။\n\n$name ထဲမှာ Aung သိမ်းပါတယ်။ echo က စာထုတ်ပါတယ်။ . က စာပေါင်းပါတယ်။\n\nစာမျက်နှာပေါ်မှာ Hello Aung ပေါ်ပါတယ်။",
          ["variable", "string"], CH,
          "<?php\n$name = \"Aung\";\necho \"Hello \" . $name;"),
        i("explain_code", "ဒီ POST form ကို ရှင်းပြပါ။",
          "ဒီ code က form က ပို့တဲ့ နာမည်ကို ယူပါတယ်။\n\n$_POST[\"name\"] က name input ကို ဖတ်ပါတယ်။ htmlspecialchars က မကောင်းတဲ့ HTML ကို ချေပါတယ်။\n\nUser ရိုက်တဲ့ နာမည်ကို ပိုလုံခြုံစွာ ပြပါတယ်။",
          ["POST", "form"], CH,
          "<?php\n$name = htmlspecialchars($_POST[\"name\"]);\necho $name;"),
        i("explain_code", "ဒီ foreach ကို ရှင်းပြပါ။",
          "ဒီ code က သစ်သီးတိုင်းကို စာရင်းထုတ်ပါတယ်။\n\nforeach က array ပေါ် လှည့်ပါတယ်။ $fruit က တစ်လုံးချင်း ဖြစ်ပါတယ်။\n\napple နဲ့ mango ပေါ်ပါတယ်။",
          ["array", "loop"], CH,
          "<?php\n$fruits = [\"apple\", \"mango\"];\nforeach ($fruits as $fruit) {\n    echo $fruit;\n}"),
        i("explain_code", "ဒီ function ကို ရှင်းပြပါ။",
          "ဒီ function က ကိန်းနှစ်လုံး ပေါင်းပါတယ်။\n\n$a နဲ့ $b က parameter ဖြစ်ပါတယ်။ return က ရလဒ် ပြန်ပေးပါတယ်။\n\nadd(2, 3) က 5 ဖြစ်ပါတယ်။",
          ["function", "return"], CH,
          "<?php\nfunction add($a, $b) {\n    return $a + $b;\n}\necho add(2, 3);"),
        i("explain_code", "ဒီ session start ကို ရှင်းပြပါ။",
          "ဒီ code က login နာမည်ကို session မှာ သိမ်းပါတယ်။\n\nsession_start() က အရင်ခေါ်ရပါတယ်။ နောက်စာမျက်နှာမှာ $_SESSION[\"user\"] ကို ပြန်ဖတ်နိုင်ပါတယ်။\n\nAung က မှတ်ထားပါတယ်။",
          ["session"], CH,
          "<?php\nsession_start();\n$_SESSION[\"user\"] = \"Aung\";"),
        i("explain_code", "ဒီ isset check ကို ရှင်းပြပါ။",
          "ဒီ code က email ပို့လာမှ ဖတ်ပါတယ်။\n\nisset က key ရှိမရှိ စစ်ပါတယ်။ မရှိရင် error နည်းပါတယ်။\n\nForm မပို့ရင် ဒီ block မဝင်ပါ။",
          ["form", "POST"], CH,
          "<?php\nif (isset($_POST[\"email\"])) {\n    $email = $_POST[\"email\"];\n    echo $email;\n}"),
        i("explain_code", "ဒီ password_hash ကို ရှင်းပြပါ။",
          "ဒီ code က စကားဝှက်ကို တိုက်ရိုက် မသိမ်းဘဲ hash လုပ်ပါတယ်။\n\npassword_hash က ပြန်ဖတ်လို့မရအောင် ပြောင်းပါတယ်။ သိမ်းရင် ပိုလုံခြုံပါတယ်။\n\nမူရင်း secret မပေါ်ပါ။",
          ["php"], CH,
          "<?php\n$hash = password_hash(\"secret\", PASSWORD_DEFAULT);\necho $hash;"),
        i("explain_code", "ဒီ password_verify ကို ရှင်းပြပါ။",
          "ဒီ code က ရိုက်ထည့်တဲ့ စကားဝှက် မှန်မမှန် စစ်ပါတယ်။\n\nverify က hash နဲ့ တိုက်ပါတယ်။ မှန်ရင် OK ထွက်ပါတယ်။\n\nမူရင်းစကားဝှက်ကို database က ပြန်မထုတ်ပါ။",
          ["php"], CH,
          "<?php\n$ok = password_verify(\"secret\", $hash);\nif ($ok) {\n    echo \"OK\";\n}"),
        i("explain_code", "ဒီ explode ကို ရှင်းပြပါ။",
          "ဒီ code က စာကို ကော်မာမှာ ခွဲပါတယ်။\n\nexplode က array ပြန်ပေးပါတယ်။ သုံးလုံး ရပါတယ်။\n\nred, green, blue ခွဲထွက်ပါတယ်။",
          ["string", "array"], CH,
          "<?php\n$colors = explode(\",\", \"red,green,blue\");\nprint_r($colors);"),
        i("explain_code", "ဒီ implode ကို ရှင်းပြပါ။",
          "ဒီ code က array ကို စာတစ်ကြောင်း ပြန်ပေါင်းပါတယ်။\n\nimplode က ကြားမှာ - ထည့်ပါတယ်။\n\nred-green ထွက်ပါတယ်။",
          ["string", "array"], CH,
          "<?php\n$line = implode(\"-\", [\"red\", \"green\"]);\necho $line;"),
        i("explain_code", "ဒီ require file ကို ရှင်းပြပါ။",
          "ဒီ code က config ဖိုင်ကို မဖြစ်မနေ ခေါ်ပါတယ်။\n\nဖိုင်မရှိရင် script ရပ်ပါတယ်။ ဆက်တင် တစ်နေရာတည်းမှာ ထားလို့ရပါတယ်။\n\nDB_HOST ကို သုံးနိုင်ပါတယ်။",
          ["php"], CH,
          "<?php\nrequire \"config.php\";\necho DB_HOST;"),
        i("explain_code", "ဒီ header redirect ကို ရှင်းပြပါ။",
          "ဒီ code က login ပြီးရင် dashboard ကို ပို့ပါတယ်။\n\nheader Location က browser ကို ပြောင်းခိုင်းပါတယ်။ exit က နောက်ကုဒ် မဆက်အောင် ရပ်ပါတယ်။\n\nအသုံးပြုသူက dashboard ကို မြင်ပါတယ်။",
          ["php"], CH,
          "<?php\nheader(\"Location: dashboard.php\");\nexit;"),
        i("explain_code", "ဒီ empty check ကို ရှင်းပြပါ။",
          "ဒီ code က နာမည်ဗလာ ဟုတ်မဟုတ် စစ်ပါတယ်။\n\nempty က မရှိ၊ ၀၊ ဗလာစာ ကို မှန်တယ်လို့ မြင်ပါတယ်။ ဗလာဆို Name required ပြပါတယ်။\n\nဖောင်စစ်ရာမှာ သုံးပါတယ်။",
          ["form"], CH,
          "<?php\nif (empty($_POST[\"name\"])) {\n    echo \"Name required\";\n}"),
        i("explain_code", "ဒီ PDO query ကို ရှင်းပြပါ။",
          "ဒီ code က ကျောင်းသားတွေကို database က ယူပါတယ်။\n\nquery က SQL ခေါ်ပါတယ်။ fetchAll က row တွေ array လုပ်ပါတယ်။\n\nတစ်ယောက်ချင်း name ကို echo နိုင်ပါတယ်။",
          ["query", "database"], CH,
          "<?php\n$rows = $pdo->query(\"SELECT name FROM students\")->fetchAll();\nforeach ($rows as $row) {\n    echo $row[\"name\"];\n}"),
        i("explain_code", "ဒီ prepared execute ကို ရှင်းပြပါ။",
          "ဒီ code က id နဲ့ ကျောင်းသား တစ်ယောက် ရှာပါတယ်။\n\n? နေရာမှာ တန်ဖိုး ခွဲထည့်ပါတယ်။ SQL နဲ့ data မရောပါ။\n\nid 5 ရဲ့ row ထွက်ပါတယ်။",
          ["query"], CH,
          "<?php\n$stmt = $pdo->prepare(\"SELECT * FROM students WHERE id = ?\");\n$stmt->execute([5]);\n$student = $stmt->fetch();"),
        i("debug_explain", "ဒီ echo quote ကို ပြင်ပါ။",
          "string ကို ပိတ်မထားလို့ syntax error တက်ပါတယ်။\n\nကိုးကွက် နှစ်ဖက်တူအောင် ပိတ်ရပါတယ်။\n\nမှန်ကန်သော code:\n<?php\necho \"Hello\";",
          ["syntax", "string"], CH,
          "<?php\necho \"Hello;"),
        i("debug_explain", "ဒီ session သုံးတာကို ပြင်ပါ။",
          "session_start() မခေါ်မီ $_SESSION သုံးလို့ မှတ်မရပါ။\n\nအပေါ်ဆုံးမှာ start ခေါ်ရပါတယ်။\n\nမှန်ကန်သော code:\n<?php\nsession_start();\n$_SESSION[\"user\"] = \"Aung\";",
          ["session"], CH,
          "<?php\n$_SESSION[\"user\"] = \"Aung\";"),
        i("debug_explain", "ဒီ SQL injection ပုံစံကို ပြင်ပါ။",
          "User input ကို SQL ထဲ တိုက်ရိုက် ပေါင်းထည့်ထားပါတယ်။\n\nPrepared statement သုံးရပါတယ်။\n\nမှန်ကန်သော code:\n<?php\n$stmt = $pdo->prepare(\"SELECT * FROM users WHERE email = ?\");\n$stmt->execute([$email]);",
          ["query", "debug"], CH,
          "<?php\n$sql = \"SELECT * FROM users WHERE email = '\" . $email . \"'\";\n$pdo->query($sql);"),
        i("concept_qa", "$_SERVER ဆိုတာ ဘာလဲ?",
          "$_SERVER က request နဲ့ server အချက်အလက် ပါတဲ့ superglobal ဖြစ်ပါတယ်။\n\nREQUEST_METHOD၊ SCRIPT_NAME တို့ ကြည့်နိုင်ပါတယ်။ Form က GET လား POST လား သိနိုင်ပါတယ်။\n\nလုံခြုံရေးအတွက် တန်ဖိုးအားလုံးကို မယုံသင့်ပါ။",
          ["php"], CH),
        i("explain_code", "ဒီ REQUEST_METHOD စစ်တာကို ရှင်းပြပါ။",
          "ဒီ code က POST နဲ့ လာမှသာ သိမ်းပါတယ်။\n\nGET နဲ့ ဖွင့်ရင် မဝင်ပါ။ Form submit ကို ပိုင်းခြားပါတယ်။\n\nမလိုအပ်ဘဲ သိမ်းတာကို တားပါတယ်။",
          ["POST"], CH,
          "<?php\nif ($_SERVER[\"REQUEST_METHOD\"] === \"POST\") {\n    echo \"Saving\";\n}"),
        i("concept_qa", "htmlspecialchars ဘာကြောင့် သုံးသလဲ?",
          "User စာထဲက <script> ကို စာသားအဖြစ် ပြောင်းပါတယ်။\n\nXSS တိုက်ခိုက်မှုကို လျှော့ပါတယ်။ ပြန်ပြတဲ့ နေရာမှာ သုံးသင့်ပါတယ်။\n\nဘရောက်ဇာက code အဖြစ် မမောင်းပါ။",
          ["php"], CH),
        i("explain_code", "ဒီ count array ကို ရှင်းပြပါ။",
          "ဒီ code က array အရေအတွက် ပြပါတယ်။\n\ncount က ၃ ပေးပါတယ်။ ဗလာဟုတ်မဟုတ် စစ်ရာမှာ သုံးပါတယ်။\n\n3 ထွက်ပါတယ်။",
          ["array"], CH,
          "<?php\n$items = [\"a\", \"b\", \"c\"];\necho count($items);"),
        i("explain_code", "ဒီ in_array ကို ရှင်းပြပါ။",
          "ဒီ code က admin ပါမပါ စစ်ပါတယ်။\n\nပါလို့ Yes ထွက်ပါတယ်။ Role စစ်ရာမှာ သုံးပါတယ်။\n\nမပါရင် ဒီ if မဝင်ပါ။",
          ["array", "condition"], CH,
          "<?php\n$roles = [\"user\", \"admin\"];\nif (in_array(\"admin\", $roles)) {\n    echo \"Yes\";\n}"),
        i("explain_code", "ဒီ date function ကို ရှင်းပြပါ။",
          "ဒီ code က ဒီနေ့ရက်ကို ပြပါတယ်။\n\nY-m-d က ခုနှစ်-လ-ရက် ပုံစံ ဖြစ်ပါတယ်။\n\n2026-09-06 လို ထွက်နိုင်ပါတယ်။",
          ["function"], CH,
          "<?php\necho date(\"Y-m-d\");"),
        i("concept_qa", "Composer ဆိုတာ ဘာလဲ?",
          "Composer က PHP package တွေကို စီမံတဲ့ ကိရိယာ ဖြစ်ပါတယ်။\n\nလိုအပ်တဲ့ library ကို နာမည်နဲ့ ထည့်ပါတယ်။ autoload က class ခေါ်ရ လွယ်စေပါတယ်။\n\nLaravel လို framework မှာ မဖြစ်မနေ သုံးပါတယ်။",
          ["php"], CH),
        i("explain_code", "ဒီ namespace use ကို ရှင်းပြပါ။",
          "ဒီ code က App\\Mail class ကို တိုတို ခေါ်ပါတယ်။\n\nuse က နာမည်ရှည် မရေးရအောင် ကူပါတယ်။ Mail ကို တိုက်ရိုက် သုံးနိုင်ပါတယ်။\n\nပဋိပက္ခနည်းအောင် namespace ခွဲပါတယ်။",
          ["class"], CH,
          "<?php\nuse App\\Mail;\n$mail = new Mail();"),
        i("debug_explain", "ဒီ = နဲ့ == ရောတာကို ပြင်ပါ။",
          "if ထဲမှာ = က သတ်မှတ်ချက် ဖြစ်ပြီး အမြဲ အမှန်သလို ဖြစ်နိုင်ပါတယ်။\n\nနှိုင်းချင်ရင် === သုံးပါ။\n\nမှန်ကန်သော code:\n<?php\n$role = \"user\";\nif ($role === \"admin\") {\n    echo \"Admin\";\n}",
          ["condition", "operator"], CH,
          "<?php\n$role = \"user\";\nif ($role = \"admin\") {\n    echo \"Admin\";\n}"),
        i("concept_qa", "Type hint ဆိုတာ ဘာလဲ?",
          "Type hint က function က ဘာအမျိုးအစား လက်ခံမလဲ ကြေညာခြင်း ဖြစ်ပါတယ်။\n\nint, string, array တို့ သုံးနိုင်ပါတယ်။ မှားပို့ရင် error ပိုမြန်ပါတယ်။\n\nကုဒ်ကို ဖတ်ရ ရှင်းစေပါတယ်။",
          ["function"], CH),
        i("explain_code", "ဒီ type hint ကို ရှင်းပြပါ။",
          "ဒီ function က ကိန်းပြည့်ပဲ လက်ခံပါတယ်။\n\nint $n က စာသား မခံပါ။ ၃ ပို့ရင် ၆ ပြန်ပါတယ်။\n\nမှားအမျိုးအစားပို့ရင် TypeError တက်ပါတယ်။",
          ["function", "integer"], CH,
          "<?php\nfunction double(int $n): int {\n    return $n * 2;\n}\necho double(3);"),
        i("explain_code", "ဒီ try catch PDO ကို ရှင်းပြပါ။",
          "ဒီ code က database ချိတ်မရရင် ပြိုမကျအောင် ဖမ်းပါတယ်။\n\nPDOException က ချိတ်ဆက်အမှား ဖြစ်ပါတယ်။ အသုံးပြုသူကို ရှင်းတဲ့ စာပြပါတယ်။\n\nစကားဝှက်အသေးစိတ် မပြသင့်ပါ။",
          ["database", "debug"], CH,
          "<?php\ntry {\n    $pdo = new PDO($dsn, $user, $pass);\n} catch (PDOException $e) {\n    echo \"DB error\";\n}"),
        i("concept_qa", "Autoload ဆိုတာ ဘာလဲ?",
          "Autoload က class ကို သုံးတဲ့အခါ ဖိုင်အလိုအလျောက် ခေါ်ခြင်း ဖြစ်ပါတယ်။\n\nrequire များများ မရေးရပါ။ Composer PSR-4 က စံဖြစ်ပါတယ်။\n\nကုဒ်ခွဲရ လွယ်ပါတယ်။",
          ["class"], CH),
        i("explain_code", "ဒီ array key ကို ရှင်းပြပါ။",
          "ဒီ code က အသက်ကို associative array က ယူပါတယ်။\n\nage key က 20 ကို ပေးပါတယ်။ ဂဏန်း index မဟုတ်ပါ။\n\n20 ထွက်ပါတယ်။",
          ["array"], CH,
          "<?php\n$user = [\"name\" => \"Aung\", \"age\" => 20];\necho $user[\"age\"];"),
        i("explain_code", "ဒီ filter_var email ကို ရှင်းပြပါ။",
          "ဒီ code က email ပုံစံ မှန်မမှန် စစ်ပါတယ်။\n\nမှန်ရင် valid email ကို ပြန်ပေးပါတယ်။ မှားရင် false ဖြစ်ပါတယ်။\n\nfoo@bar.com က မှန်နိုင်ပါတယ်။",
          ["form"], CH,
          "<?php\n$email = filter_var(\"foo@bar.com\", FILTER_VALIDATE_EMAIL);\nif ($email) {\n    echo $email;\n}"),
        i("concept_qa", "csrf ကာကွယ်မှုကို PHP မှာ ဘာကြောင့် စဉ်းစားရလဲ?",
          "အခြားဆိုက်က user အစား form ပို့နိုင်ပါတယ်။\n\nToken တစ်ခုကို session မှာ မှတ်ပြီး form နဲ့ တိုက်ရင် ကာကွယ်နိုင်ပါတယ်။ Laravel က ဒါကို အလိုအလျောက် ကူပါတယ်။\n\nအရေးကြီး form မှာ လိုအပ်ပါတယ်။",
          ["form", "session"], CH),
        i("explain_code", "ဒီ ternary PHP ကို ရှင်းပြပါ။",
          "ဒီ code က login ဖြစ်ရင် နာမည်၊ မဟုတ်ရင် Guest ပြပါတယ်။\n\n?? က null ဖြစ်ရင် ညာဘက်ကို သုံးပါတယ်။\n\nuser မရှိရင် Guest ထွက်ပါတယ်။",
          ["condition"], CH,
          "<?php\necho $user ?? \"Guest\";"),
        i("debug_explain", "ဒီ notice undefined ကို ပြင်ပါ။",
          "$name ကို မသတ်မှတ်ဘဲ သုံးထားပါတယ်။\n\nအရင်တန်ဖိုး ပေးရပါတယ်။\n\nမှန်ကန်သော code:\n<?php\n$name = \"Mya\";\necho $name;",
          ["variable", "debug"], CH,
          "<?php\necho $name;"),
        i("concept_qa", "index.php ရဲ့ အခန်းကဏ္ဍက ဘာလဲ?",
          "index.php က ဖိုလ်ဒါဖွင့်ရင် ပုံမှန်ဝင်တဲ့ ဖိုင် ဖြစ်ပါတယ်။\n\nဝက်ဘ်ဆိုက် အစ ဖြစ်တတ်ပါတယ်။ Router မသုံးရင် ဒီကနေ စပါတယ်။\n\nလိပ်စာမှာ ဖိုင်နာမည် မပေးရင် ဒီဖိုင် လုပ်ပါတယ်။",
          ["php"], CH),
        i("explain_code", "ဒီ str_replace ကို ရှင်းပြပါ။",
          "ဒီ code က စာထဲက cat ကို dog လဲပါတယ်။\n\nstr_replace က ရှာပြီး အစားထိုးပါတယ်။\n\nI have a dog ထွက်ပါတယ်။",
          ["string"], CH,
          "<?php\necho str_replace(\"cat\", \"dog\", \"I have a cat\");"),
        i("explain_code", "ဒီ strlen ကို ရှင်းပြပါ။",
          "ဒီ code က စာလုံးရေ ရေတွက်ပါတယ်။\n\nAung မှာ လေးလုံးရှိပါတယ်။ ဖောင်အရှည်ကန့်သတ်ရာမှာ သုံးပါတယ်။\n\n4 ထွက်ပါတယ်။",
          ["string"], CH,
          "<?php\necho strlen(\"Aung\");"),
        i("explain_code", "ဒီ array_push ကို ရှင်းပြပါ။",
          "ဒီ code က list အဆုံးမှာ orange ထည့်ပါတယ်။\n\narray_push က မူရင်း array ကို တိုးပါတယ်။\n\nသုံးလုံး ရှိလာပါမယ်။",
          ["array"], CH,
          "<?php\n$fruits = [\"apple\", \"mango\"];\narray_push($fruits, \"orange\");\nprint_r($fruits);"),
        i("concept_qa", "echo နဲ့ return ဘာကွာလဲ?",
          "echo က browser ကို တိုက်ရိုက် ထုတ်ပါတယ်။ return က function ကနေ တန်ဖိုး ပြန်ပေးပါတယ်။\n\nတွက်ချက်မှုကို ပြန်သုံးချင်ရင် return လိုပါတယ်။\n\nနှစ်ခု ရောသုံးရင် ရလဒ် ရှုပ်နိုင်ပါတယ်။",
          ["return", "function"], CH),
        i("explain_code", "ဒီ class PHP ကို ရှင်းပြပါ။",
          "ဒီ code က User object ဖန်တီးပြီး နာမည် ပြပါတယ်။\n\nconstructor က နာမည် လက်ခံပါတယ်။ getName က ပြန်ပေးပါတယ်။\n\nSu ထွက်ပါတယ်။",
          ["class", "method"], CH,
          "<?php\nclass User {\n    private $name;\n    public function __construct($name) {\n        $this->name = $name;\n    }\n    public function getName() {\n        return $this->name;\n    }\n}\n$user = new User(\"Su\");\necho $user->getName();"),
        i("debug_explain", "ဒီ foreach syntax ကို ပြင်ပါ။",
          "as မပါလို့ foreach ပုံစံ မှားပါတယ်။\n\narray as item ပုံစံ ရေးရပါတယ်။\n\nမှန်ကန်သော code:\n<?php\nforeach ([1, 2] as $n) {\n    echo $n;\n}",
          ["loop", "syntax"], CH,
          "<?php\nforeach ([1, 2]) {\n    echo $n;\n}"),
        i("concept_qa", "php.ini က ဘာလဲ?",
          "php.ini က PHP ဆက်တင်ဖိုင် ဖြစ်ပါတယ်။\n\nerror ပြမပြ၊ upload အရွယ်အစား စတာတွေ ပြင်နိုင်ပါတယ်။ ပတ်ဝန်းကျင်အလိုက် တန်ဖိုး မတူနိုင်ပါတယ်။\n\nဖွံ့ဖြိုးချိန်မှာ error ပြသင့်ပါတယ်။",
          ["php"], CH),
        i("explain_code", "ဒီ error_reporting ကို ရှင်းပြပါ။",
          "ဒီ code က အမှားအားလုံးကို ပြခိုင်းပါတယ်။\n\nဖွံ့ဖြိုးချိန်မှာ bug မြင်ရ လွယ်ပါတယ်။ ထုတ်လုပ်ရေးမှာ ပိုတိကျစွာ ပိတ်သင့်ပါတယ်။\n\nသတိပေးချက်တွေ ပေါ်လာပါမယ်။",
          ["debug"], CH,
          "<?php\nerror_reporting(E_ALL);\nini_set(\"display_errors\", \"1\");"),
        i("concept_qa", "MVC ကို PHP မှာ ဘာကြောင့် သုံးသလဲ?",
          "MVC က မျက်နှာပြင်၊ စည်းကမ်း၊ data ကို ခွဲပါတယ်။\n\nဖိုင်မရှုပ်အောင် ကူပါတယ်။ Laravel က ဒီပုံစံကို လိုက်ပါတယ်။\n\nပြင်ရ လွယ်ပြီး အဖွဲ့လိုက် လုပ်ရ ပိုကောင်းပါတယ်။",
          ["php"], CH),
    ]
