from .common import item as i

CH = {
    1: "အခန်း ၁ ။ Programming ဆိုတာ",
    2: "အခန်း ၂ ။ Programming",
    3: "အခန်း ၃ ။ Object Oriented",
}


def samples():
    return [
        i("concept_qa", "Programming ဆိုတာ ဘာလဲ?",
          "Programming ဆိုတာ computer ကို အဆင့်ဆင့် ခိုင်းစေတဲ့ လုပ်ငန်းစဉ် ဖြစ်ပါတယ်။\n\nComputer ဟာ ကိုယ်တိုင် မစဉ်းစားနိုင်ပါဘူး။ Programmer က language တစ်ခုနဲ့ instruction တွေ ရေးမှသာ အလုပ်လုပ်ပါတယ်။\n\nဥပမာ print(\"Hello\") လို့ ရေးရင် screen ပေါ်မှာ Hello ထွက်လာအောင် ခိုင်းတာ ဖြစ်ပါတယ်။",
          ["programming"], CH[1]),
        i("concept_qa", "Python ဆိုတာ ဘာလဲ?",
          "Programmer တွေဟာ programming language တစ်ခုခု ကို အသုံးပြုပြီး app တွေကို ဖန်တီးကြပါတယ်။ Programming language ကို အသုံးပြုပြီး program တွေကို ရေးသားပြီး နောက်ဆုံး App အနေနဲ့ ထွက်လာတာပါ။\n\ncomputer နဲ့ programmer ကြားမှာ ဆက်သွယ်ပေးတဲ့ ဘာသာစကားပါ။ Computer ဟာ အလိုအလျောက် ဘာမှ မလုပ်နိုင်ပါဘူး။ Programmer ဟာ computer ကို ဒါလုပ် ဒါလုပ် စသည် ဖြင့် ခိုင်းစေရပါတယ်။\n\nPython ဟာ Object Oriented Programming Language တစ်ခုပါ။ Python မှာ function ကို ရေးတဲ့ အခါမှာတော့ def နဲ့ စတယ်။\n\nဒီ code လေးမှာ ဆိုရင် ကျွန်တော်တို့တွေ printHello ဆိုတဲ့ function လေး ရေးထားတာကို တွေ့နိုင်ပါတယ်။ Hello ကို ခဏခဏ print ရိုက်နေမယ့် အစား printHello ဆိုတဲ့ funtion လေးကို ခေါ်လိုက်တာနဲ့ HELLO ဆိုပြီး ထုတ်ပြပေးနေမှာပါ။",
          ["programming"], CH[1]),
        i("concept_qa", "Variable ဆိုတာ ဘာလဲ?",
          "Variable ဆိုတာ data ကို ခဏသိမ်းထားတဲ့ နာမည်ပေးထားသော memory နေရာ ဖြစ်ပါတယ်။\n\nဘယ်ဘက်မှာ နာမည်၊ ညာဘက်မှာ တန်ဖိုး ထည့်ပါတယ်။ Program ပိတ်လိုက်ရင် memory က ရှင်းသွားပါတယ်။\n\nဥပမာ name = \"Aung\" ဆိုရင် name ထဲမှာ Aung သိမ်းထားပါတယ်။",
          ["variable"], CH[1]),
        i("concept_qa", "Function ဆိုတာ ဘာလဲ?",
          "Function ဆိုတာ ထပ်ခါထပ်ခါ သုံးမယ့် အလုပ်ကို နာမည်ပေးပြီး စုရေးထားခြင်း ဖြစ်ပါတယ်။\n\nခေါ်လိုက်တိုင်း အထဲက code က ပြန်အလုပ်လုပ်ပါတယ်။ Data ပို့ချင်ရင် parameter ထည့်ပါတယ်။\n\nဥပမာ greet() ကို ခေါ်ရင် Hello ကို ထုတ်ပြနိုင်ပါတယ်။",
          ["function", "parameter"], CH[2]),
        i("concept_qa", "Loop ဆိုတာ ဘာလဲ?",
          "Loop ဆိုတာ တူညီတဲ့ အလုပ်ကို အကြိမ်ရေ သတ်မှတ်ချက်အတိုင်း ထပ်လုပ်ခြင်း ဖြစ်ပါတယ်။\n\nprint ကို ဆယ်ကြောင်း ရေးမယ့်အစား for သို့မဟုတ် while နဲ့ ထပ်ခေါ်ပါတယ်။ အကြိမ်ရေ မသိရင် condition နဲ့ ရပ်ပါတယ်။\n\nဥပမာ ၀ ကနေ ၉ အထိ ထုတ်ပြချင်ရင် loop တစ်ခုနဲ့ ရပါတယ်။",
          ["loop"], CH[2]),
        i("concept_qa", "Array ဆိုတာ ဘာလဲ?",
          "Array ဆိုတာ တန်ဖိုး အများကြီးကို အခန်းလိုက် သိမ်းတဲ့ variable ဖြစ်ပါတယ်။\n\nအခန်းကို ၀ က စရေတွက်ပါတယ်။ တစ်ခုချင်း ဝင်ထုတ်နိုင်သလို အရှည်ကိုလည်း တိုင်းနိုင်ပါတယ်။\n\nဥပမာ numbers = [3, 8, 1] မှာ ပထမအခန်းက 3 ဖြစ်ပါတယ်။",
          ["array", "variable"], CH[2]),
        i("concept_qa", "Class ဆိုတာ ဘာလဲ?",
          "Class ဆိုတာ object တည်ဆောက်ဖို့ ပုံစံခွက် ဖြစ်ပါတယ်။\n\nအထဲမှာ variable နဲ့ method တွေ ထည့်ပါတယ်။ Class ကနေ instance ခွဲထုတ်ပြီး သုံးပါတယ်။\n\nဥပမာ Animal class ကနေ dog object တစ်ကောင် ဖန်တီးနိုင်ပါတယ်။",
          ["class", "method", "variable"], CH[3]),
        i("concept_qa", "If condition ဆိုတာ ဘာလဲ?",
          "If condition ဆိုတာ အခြေအနေမှန်မှသာ code အချို့ကို လုပ်ခိုင်းခြင်း ဖြစ်ပါတယ်။\n\nမှားရင် else သို့မဟုတ် elif နဲ့ အခြားဘက် သွားပါတယ်။ နှိုင်းယှဉ်မှုက True သို့မဟုတ် False ဖြစ်ပါတယ်။\n\nဥပမာ အမှတ် ၅၀ နှင့်အထက်ဆို Pass လို့ ပြနိုင်ပါတယ်။",
          ["condition"], CH[2]),
        i("concept_qa", "String နဲ့ integer ဘာကွာလဲ?",
          "String က စာသား၊ integer က ကိန်းပြည့် ဖြစ်ပါတယ်။\n\nString ကို ကိုးကွက်နဲ့ ရေးပါတယ်။ Integer ကို သင်္ချာတွက်လို့ရပါတယ်။ နှစ်ခုကို တိုက်ရိုက် မပေါင်းသင့်ပါ။\n\nဥပမာ \"5\" + \"6\" က 56 ဖြစ်ပြီး 5 + 6 က 11 ဖြစ်ပါတယ်။",
          ["string", "integer"], CH[1]),
        i("concept_qa", "Input function က ဘာလုပ်သလဲ?",
          "input() က user ဆီက စာသား လက်ခံပါတယ်။\n\nပြန်ရတဲ့ တန်ဖိုးက string ဖြစ်ပါတယ်။ ကိန်းအဖြစ် သုံးချင်ရင် int() နဲ့ ပြောင်းရပါတယ်။\n\nဥပမာ age = int(input()) ဆိုရင် နံပါတ်ကို မှန်ကန်စွာ လက်ခံနိုင်ပါတယ်။",
          ["function", "string", "integer"], CH[2]),
        i("concept_qa", "Return ဆိုတာ ဘာလဲ?",
          "Return ဆိုတာ function ကနေ ရလဒ် ပြန်ပို့ခြင်း ဖြစ်ပါတယ်။\n\nprint က screen မှာ ပြရုံသာ ဖြစ်ပြီး return က ခေါ်တဲ့နေရာကို တန်ဖိုး ပေးပါတယ်။ Return ပြီးရင် function ရပ်ပါတယ်။\n\nဥပမာ add(2, 3) က 5 ကို ပြန်ပေးနိုင်ပါတယ်။",
          ["function", "return"], CH[2]),
        i("concept_qa", "Boolean ဆိုတာ ဘာလဲ?",
          "Boolean ဆိုတာ True သို့မဟုတ် False သာ ရှိတဲ့ တန်ဖိုး ဖြစ်ပါတယ်။\n\nCondition နဲ့ loop မှာ ဆုံးဖြတ်ချက် အတွက် သုံးပါတယ်။ နှိုင်းယှဉ်မှုရလဒ်က boolean ဖြစ်ပါတယ်။\n\nဥပမာ 5 > 3 က True ဖြစ်ပါတယ်။",
          ["boolean", "condition"], CH[1]),
        i("concept_qa", "Syntax error ဆိုတာ ဘာလဲ?",
          "Syntax error ဆိုတာ language ရဲ့ စည်းကမ်း မမှန်လို့ program မစနိုင်ခြင်း ဖြစ်ပါတယ်။\n\nကိုးကွက် ပျောက်ခြင်း၊ colon မပါခြင်းတွေက အဖြစ်များပါတယ်။ Runtime မရောက်ခင် compiler သို့မဟုတ် interpreter က ဖမ်းပါတယ်။\n\nဥပမာ print(\"hi) ဆိုရင် quote မပိတ်လို့ error တက်ပါတယ်။",
          ["syntax", "debug"], CH[2]),
        i("concept_qa", "Runtime error ဆိုတာ ဘာလဲ?",
          "Runtime error ဆိုတာ program စပြီးမှ ဖြစ်တဲ့ အမှား ဖြစ်ပါတယ်။\n\nSyntax မှန်ပေမယ့် ခွဲခြမ်း ၀၊ မရှိတဲ့ index ခေါ်ခြင်းတွေမှာ ဖြစ်ပါတယ်။ try except နဲ့ ကိုင်တွယ်နိုင်ပါတယ်။\n\nဥပမာ 10 / 0 က ZeroDivisionError တက်ပါတယ်။",
          ["runtime", "debug"], CH[2]),
        i("concept_qa", "Comment ဆိုတာ ဘာလဲ?",
          "Comment ဆိုတာ computer မဖတ်ဘဲ လူဖတ်ဖို့ ရေးတဲ့ မှတ်ချက် ဖြစ်ပါတယ်။\n\nPython မှာ # နဲ့ စပါတယ်။ ဘာကြောင့် ရေးတယ်ဆိုတာ ရှင်းအောင် သုံးပါတယ်။\n\nဥပမာ # user name လက်ခံမယ် လို့ ရေးထားနိုင်ပါတယ်။",
          ["programming"], CH[1]),
        i("concept_qa", "Operator ဆိုတာ ဘာလဲ?",
          "Operator ဆိုတာ တန်ဖိုးတွေကို တွက်ချက် သို့မဟုတ် နှိုင်းယှဉ်တဲ့ သင်္ကေတ ဖြစ်ပါတယ်။\n\nပေါင်း၊ နုတ်၊ ညီမျှ၊ ငယ်သည် စသည်ဖြင့် ရှိပါတယ်။ ရလဒ်က ဂဏန်း သို့မဟုတ် boolean ဖြစ်နိုင်ပါတယ်။\n\nဥပမာ 7 % 2 က လက်ကျန် 1 ကို ပေးပါတယ်။",
          ["operator"], CH[1]),
        i("explain_code", "ဒီ Python code က ဘာလုပ်သလဲ?",
          "ဒီ code က user ဆီက နာမည် လက်ခံပြီး ပြန်ပြပါတယ်။\n\ninput() က မေးခွန်းပြပြီး ရိုက်ထည့်တဲ့ စာကို username ထဲ သိမ်းပါတယ်။ print() က Your name is နဲ့အတူ နာမည်ကို ထုတ်ပါတယ်။\n\nဥပမာ Aung ရိုက်ရင် Your name is  Aung ထွက်ပါတယ်။",
          ["variable", "function"], CH[2],
          "username = input(\"What is your name ? : \")\nprint(\"Your name is \", username)"),
        i("explain_code", "ဒီ code မှာ i တန်ဖိုး ဘယ်လို ပြောင်းသလဲ?",
          "ဒီ code က အဆင့်နှစ်ဆင့်နဲ့ i ကို တွက်ပါတယ်။\n\nပထမကြောင်းမှာ 5 + 4 က 9 ဖြစ်ပြီး i ထဲ သိမ်းပါတယ်။ ဒုတိယကြောင်းမှာ အရင် i ကို 6 ထပ်ပေါင်းပြီး 15 ဖြစ်ပါတယ်။\n\nတစ်ကြောင်းပြီးမှ နောက်တစ်ကြောင်း အလုပ်လုပ်တာကြောင့် 15 ရပါတယ်။",
          ["variable", "operator"], CH[1],
          "i = 5 + 4\ni = i + 6"),
        i("explain_code", "ဒီ code က ကိန်းနှစ်လုံးကို ဘယ်လို ပေါင်းသလဲ?",
          "ဒီ code က ကိန်းနှစ်လုံး လက်ခံပြီး ပေါင်းလဒ် ပြပါတယ်။\n\nint(input()) က စာသားကို ကိန်းပြည့် ပြောင်းပါတယ်။ result ထဲမှာ ပေါင်းလဒ် သိမ်းပြီး print က ညီမျှခြင်းပုံစံနဲ့ ပြပါတယ်။\n\nဥပမာ 5 နဲ့ 6 ထည့်ရင် 5 + 6 = 11 ထွက်ပါတယ်။",
          ["integer", "function"], CH[1],
          "input1 = int(input(\"Please enter first number: \"))\ninput2 = int(input(\"Please enter second number: \"))\nresult = input1 + input2\nprint(input1, \"+\", input2, \"=\", result)"),
        i("explain_code", "len() ကို သုံးတဲ့ ဒီ code ကို ရှင်းပြပါ။",
          "ဒီ code က list ထဲမှာ ဘယ်နှစ်ခု ရှိလဲ တိုင်းပါတယ်။\n\nlist ထဲမှာ ဂဏန်း ၈ ခု ရှိပါတယ်။ len(list) က အရေအတွက် ၈ ကို ပေးပြီး print က ၈ ကို ပြပါတယ်။\n\nအကြီးဆုံး ဂဏန်း ရှာတာ မဟုတ်ပါ။ အရေအတွက်ပဲ တိုင်းတာ ဖြစ်ပါတယ်။",
          ["array", "function"], CH[2],
          "numbers = [1, 5, 2, 7, 8, 9, 200, 155]\nprint(len(numbers))"),
        i("explain_code", "ဒီ for loop က ဘာလုပ်သလဲ?",
          "ဒီ loop က ၀ ကနေ ၉ အထိ ပေါင်းပြီး စုစုပေါင်း ပြပါတယ်။\n\nrange(10) က ၀ မှ ၉ ထိ ပေးပါတယ်။ total ကို တစ်ခုချင်း ပေါင်းထည့်ပါတယ်။ ပြီးမှ print လုပ်ပါတယ်။\n\nရလဒ်က ၀ ကနေ ၉ ပေါင်းလဒ် ၄၅ ဖြစ်ပါတယ်။",
          ["loop"], CH[2],
          "total = 0\nfor x in range(10):\n    total = total + x\nprint(total)"),
        i("explain_code", "ဒီ if else code ကို ရှင်းပြပါ။",
          "ဒီ code က အမှတ်ပေါ်မူတည်ပြီး Pass သို့မဟုတ် Fail ပြပါတယ်။\n\nscore က ၇၅ ဖြစ်လို့ ၅၀ နှင့်အထက် ဖြစ်ပါတယ်။ ဒါကြောင့် if ဘက်က အလုပ်လုပ်ပြီး Pass ထွက်ပါတယ်။\n\nscore ကို ၄၀ ထားရင် Fail ထွက်ပါမယ်။",
          ["condition"], CH[2],
          "score = 75\nif score >= 50:\n    print(\"Pass\")\nelse:\n    print(\"Fail\")"),
        i("explain_code", "ဒီ function code ကို ရှင်းပြပါ။",
          "ဒီ function က နာမည် လက်ခံပြီး နှုတ်ဆက်စာ ပြန်ပေးပါတယ်။\n\ndef က function စပါတယ်။ name က parameter ဖြစ်ပါတယ်။ return က စာသားပေါင်းပြီး ပြန်ပို့ပါတယ်။\n\nmessage ထဲမှာ Hello, Mya ရှိပြီး print က အဲဒါကို ပြပါတယ်။",
          ["function", "parameter", "return"], CH[2],
          "def greet(name):\n    return \"Hello, \" + name\n\nmessage = greet(\"Mya\")\nprint(message)"),
        i("explain_code", "ဒီ while loop ကို ရှင်းပြပါ။",
          "ဒီ while loop က count က ၃ ထက်ငယ်နေသ၍ ထပ်လုပ်ပါတယ်။\n\nစမှာ count က ၀ ဖြစ်ပါတယ်။ ၀၊ ၁၊ ၂ ကို ပြပြီး တစ်ခါတိုင်း ၁ တိုးပါတယ်။ ၃ ရောက်ရင် ရပ်ပါတယ်။\n\nဒါကြောင့် ၀ ၁ ၂ သုံးကြောင်း ထွက်ပါတယ်။",
          ["loop"], CH[2],
          "count = 0\nwhile count < 3:\n    print(count)\n    count = count + 1"),
        i("explain_code", "ဒီ list index code ကို ရှင်းပြပါ။",
          "ဒီ code က list ရဲ့ ပထမဆုံး တန်ဖိုးကို ယူပါတယ်။\n\nIndex ၀ က ပထမအခန်း ဖြစ်ပါတယ်။ fruits[0] က apple ဖြစ်ပါတယ်။\n\nprint လုပ်ရင် apple ထွက်ပါတယ်။",
          ["array"], CH[2],
          "fruits = [\"apple\", \"banana\", \"mango\"]\nprint(fruits[0])"),
        i("explain_code", "ဒီ dictionary code ကို ရှင်းပြပါ။",
          "ဒီ code က key နဲ့ value တွဲသိမ်းပြီး အသက်ကို ထုတ်ပါတယ်။\n\nstudent[\"age\"] က 20 ကို ပေးပါတယ်။ နာမည်မဟုတ်ဘဲ age key ကို ခေါ်ပါတယ်။\n\nရလဒ်က 20 ဖြစ်ပါတယ်။",
          ["object"], CH[2],
          "student = {\"name\": \"Aung\", \"age\": 20}\nprint(student[\"age\"])"),
        i("explain_code", "ဒီ class code ကို ရှင်းပြပါ။",
          "ဒီ code က Dog class ကနေ object တစ်ခု ဖန်တီးပါတယ်။\n\n__init__ က နာမည် လက်ခံပြီး self.name ထဲ သိမ်းပါတယ်။ bark method က Woof ပြပါတယ်။\n\nBuddy ဆိုတဲ့ ခွေးအတွက် Woof ထွက်ပါတယ်။",
          ["class", "method"], CH[3],
          "class Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        print(\"Woof\")\n\npet = Dog(\"Buddy\")\npet.bark()"),
        i("explain_code", "ဒီ string concat code ကို ရှင်းပြပါ။",
          "ဒီ code က စာသားနှစ်ခုကို ပေါင်းပါတယ်။\n\nfirst နဲ့ last ကြားမှာ space ထည့်ပါတယ်။ full ထဲမှာ Aung Min ဖြစ်ပါတယ်။\n\nprint က Aung Min ကို ပြပါတယ်။",
          ["string"], CH[1],
          "first = \"Aung\"\nlast = \"Min\"\nfull = first + \" \" + last\nprint(full)"),
        i("explain_code", "ဒီ slice code ကို ရှင်းပြပါ။",
          "ဒီ code က list ရဲ့ ရှေ့နှစ်ခုကို ဖြတ်ယူပါတယ်။\n\n[0:2] က index ၀ နဲ့ ၁ ကို ယူပြီး ၂ ကို မယူပါ။ ရလဒ်က [10, 20] ဖြစ်ပါတယ်။\n\nမူရင်း list က မပျက်ပါ။",
          ["array"], CH[2],
          "data = [10, 20, 30, 40]\nprint(data[0:2])"),
        i("explain_code", "ဒီ try except code ကို ရှင်းပြပါ။",
          "ဒီ code က ကိန်းမဟုတ်တာ ရိုက်ရင် error မပျက်အောင် ကာကွယ်ပါတယ်။\n\nint() က abc ကို ပြောင်းလို့မရလို့ ValueError တက်ပါတယ်။ except က ဖမ်းပြီး Please enter a number ပြပါတယ်။\n\nနံပါတ် ရိုက်ရင် အောင်မြင်စွာ ပြောင်းပါတယ်။",
          ["debug", "integer"], CH[2],
          "text = \"abc\"\ntry:\n    number = int(text)\n    print(number)\nexcept ValueError:\n    print(\"Please enter a number\")"),
        i("explain_code", "ဒီ modulo code ကို ရှင်းပြပါ။",
          "ဒီ code က စုံဂဏန်း ဟုတ်မဟုတ် စစ်ပါတယ်။\n\n8 % 2 က လက်ကျန် ၀ ဖြစ်လို့ if က True ဖြစ်ပါတယ်။ Even ကို ပြပါတယ်။\n\n၇ ထားရင် Odd ထွက်ပါမယ်။",
          ["operator", "condition"], CH[1],
          "n = 8\nif n % 2 == 0:\n    print(\"Even\")\nelse:\n    print(\"Odd\")"),
        i("explain_code", "ဒီ nested loop ကို ရှင်းပြပါ။",
          "ဒီ code က ဂဏန်းတွဲ အချို့ကို ထုတ်ပါတယ်။\n\nအပြင် loop က i ကို ၁ နဲ့ ၂ ပေးပါတယ်။ အတွင်း loop က j ကို ၁ နဲ့ ၂ ပေးပါတယ်။\n\n1-1, 1-2, 2-1, 2-2 ဆိုပြီး လေးကြောင်း ထွက်ပါတယ်။",
          ["loop"], CH[2],
          "for i in range(1, 3):\n    for j in range(1, 3):\n        print(i, j)"),
        i("debug_explain", "ဒီ code မှာ ဘာမှားနေလဲ? ပြင်ပေးပါ။",
          "string quote နှစ်မျိုး ရောသုံးထားလို့ syntax error တက်ပါတယ်။\n\nစမှာ single quote၊ ပိတ်မှာ double quote ဖြစ်နေပါတယ်။ နှစ်ဖက်တူအောင် ပြင်ရပါတယ်။\n\nမှန်ကန်သော code:\ndef print_hello():\n    print(\"HELLO\")\n\nprint_hello()",
          ["syntax", "function", "string"], CH[2],
          "def print_hello():\n    print('HELLO\")\n\nprint_hello()"),
        i("debug_explain", "ဒီ code ဘာကြောင့် ၅၆ ထွက်သလဲ? ပြင်ပေးပါ။",
          "input() က string ပြန်တဲ့အတွက် ၅ နဲ့ ၆ ကို စာသားလို ပေါင်းပြီး ၅၆ ဖြစ်ပါတယ်။\n\nကိန်းပေါင်းချင်ရင် int() နဲ့ ပြောင်းရပါတယ်။\n\nမှန်ကန်သော code:\nx = int(input(\"Enter first value : \"))\ny = int(input(\"Enter second value : \"))\nprint(\"X + Y = \", x + y)",
          ["string", "integer"], CH[2],
          "x = input(\"Enter first value : \")\ny = input(\"Enter second value : \")\nprint(\"X + Y = \", x + y)"),
        i("debug_explain", "ဒီ function ဘာကြောင့် None ပြသလဲ?",
          "function ထဲမှာ print ပဲလုပ်ပြီး return မလုပ်လို့ None ရပါတယ်။\n\nတန်ဖိုး ပြန်လိုချင်ရင် return သုံးရပါတယ်။\n\nမှန်ကန်သော code:\ndef add(a, b):\n    return a + b\n\nprint(add(2, 3))",
          ["function", "return"], CH[2],
          "def add(a, b):\n    print(a + b)\n\nprint(add(2, 3))"),
        i("debug_explain", "ဒီ list code ဘာကြောင့် error တက်သလဲ?",
          "Index ၃ က မရှိပါ။ list မှာ ၀၊ ၁၊ ၂ သာ ရှိပါတယ်။\n\nနောက်ဆုံးအခန်းကို ယူချင်ရင် ၂ သို့မဟုတ် -1 သုံးပါ။\n\nမှန်ကန်သော code:\ncolors = [\"red\", \"green\", \"blue\"]\nprint(colors[2])",
          ["array", "debug"], CH[2],
          "colors = [\"red\", \"green\", \"blue\"]\nprint(colors[3])"),
        i("debug_explain", "ဒီ loop ဘာကြောင့် မရပ်သလဲ?",
          "count ကို မတိုးလို့ condition က အမြဲ True ဖြစ်နေပါတယ်။\n\nInfinite loop မဖြစ်အောင် loop ထဲမှာ count ကို ၁ တိုးရပါတယ်။\n\nမှန်ကန်သော code:\ncount = 0\nwhile count < 3:\n    print(count)\n    count = count + 1",
          ["loop"], CH[2],
          "count = 0\nwhile count < 3:\n    print(count)"),
        i("concept_qa", "Parameter နဲ့ argument ဘာကွာလဲ?",
          "Parameter က function သတ်မှတ်တဲ့ နာမည်၊ argument က ခေါ်တဲ့အခါ ပို့တဲ့ တန်ဖိုး ဖြစ်ပါတယ်။\n\ndef add(a, b) မှာ a နဲ့ b က parameter ဖြစ်ပါတယ်။ add(2, 3) မှာ 2 နဲ့ 3 က argument ဖြစ်ပါတယ်။\n\nနှစ်ခုလုံး ကိုက်ညီမှ မှန်ကန်စွာ အလုပ်လုပ်ပါတယ်။",
          ["parameter", "function"], CH[2]),
        i("concept_qa", "Indentation က ဘာကြောင့် အရေးကြီးလဲ?",
          "Python မှာ indentation က block ကို သတ်မှတ်ပါတယ်။\n\nကွင်းပိတ်မသုံးဘဲ နေရာချင်းနဲ့ if၊ loop၊ function ထဲကို ခွဲပါတယ်။ မှားရင် IndentationError တက်ပါတယ်။\n\nပုံမှန်အားဖြင့် space ၄ ခု သုံးပါတယ်။",
          ["syntax"], CH[1]),
        i("concept_qa", "None ဆိုတာ ဘာလဲ?",
          "None ဆိုတာ တန်ဖိုး မရှိကြောင်း ပြတဲ့ special value ဖြစ်ပါတယ်။\n\nFunction က return မလုပ်ရင် None ပြန်ပါတယ်။ ဗလာစာသား \"\" နဲ့ မတူပါ။\n\nဥပမာ result is None လို့ စစ်နိုင်ပါတယ်။",
          ["function", "return"], CH[2]),
        i("concept_qa", "List နဲ့ tuple ဘာကွာလဲ?",
          "List က ပြင်လို့ရပြီး tuple က ပြင်လို့မရပါ။\n\nList က []၊ tuple က () သုံးပါတယ်။ မပြောင်းချင်တဲ့ အချက်အလက်ကို tuple နဲ့ သိမ်းပါတယ်။\n\nဥပမာ point = (3, 4) က ပြင်မရပါ။",
          ["array"], CH[2]),
        i("concept_qa", "Scope ဆိုတာ ဘာလဲ?",
          "Scope ဆိုတာ variable ကို ဘယ်နေရာက မြင်လို့ရလဲ ဆိုတာ ဖြစ်ပါတယ်။\n\nFunction ထဲက variable ကို အပြင်က မမြင်ရပါ။ အပြင်က global ကို သတိထားပြီး သုံးရပါတယ်။\n\nဥပမာ function ထဲက x က အပြင် print နဲ့ မရပါ။",
          ["variable", "function"], CH[2]),
        i("explain_code", "ဒီ enumerate code ကို ရှင်းပြပါ။",
          "ဒီ code က index နဲ့ တန်ဖိုး တွဲပြီး ပြပါတယ်။\n\nenumerate က ၀ က စ index ပေးပါတယ်။ i က နေရာ၊ fruit က နာမည် ဖြစ်ပါတယ်။\n\n0 apple နဲ့ 1 mango ထွက်ပါတယ်။",
          ["array", "loop"], CH[2],
          "for i, fruit in enumerate([\"apple\", \"mango\"]):\n    print(i, fruit)"),
        i("explain_code", "ဒီ max code ကို ရှင်းပြပါ။",
          "ဒီ code က list ထဲက အကြီးဆုံး ဂဏန်းကို ရှာပါတယ်။\n\nmax() က တန်ဖိုးတွေထဲက အကြီးဆုံးကို ရွေးပါတယ်။ ၉ က အကြီးဆုံး ဖြစ်ပါတယ်။\n\nprint က ၉ ကို ပြပါတယ်။",
          ["array", "function"], CH[2],
          "values = [3, 9, 1, 7]\nprint(max(values))"),
        i("explain_code", "ဒီ file write code ကို ရှင်းပြပါ။",
          "ဒီ code က ဖိုင်ထဲကို စာရေးပါတယ်။\n\nwith open က ဖိုင်ဖွင့်ပြီး အဆုံးမှာ ပိတ်ပေးပါတယ်။ w mode က အသစ်ရေးပါတယ်။\n\nnote.txt ထဲမှာ Hello ရှိလာပါမယ်။",
          ["function"], CH[2],
          "with open(\"note.txt\", \"w\") as f:\n    f.write(\"Hello\")"),
        i("explain_code", "ဒီ list comprehension ကို ရှင်းပြပါ။",
          "ဒီ code က စုံဂဏန်းတွေကို list အသစ် လုပ်ပါတယ်။\n\nrange(5) က ၀ မှ ၄ ထိ ပေးပါတယ်။ x % 2 == 0 မှသာ ထည့်ပါတယ်။\n\nရလဒ်က [0, 2, 4] ဖြစ်ပါတယ်။",
          ["array", "loop", "condition"], CH[2],
          "evens = [x for x in range(5) if x % 2 == 0]\nprint(evens)"),
        i("explain_code", "ဒီ default parameter code ကို ရှင်းပြပါ။",
          "ဒီ function က နာမည် မပို့ရင် Guest ကို သုံးပါတယ်။\n\nhello() ခေါ်ရင် Guest ဖြစ်ပါတယ်။ hello(\"Su\") ခေါ်ရင် Su ဖြစ်ပါတယ်။\n\nDefault က မပို့မှသာ ဝင်ပါတယ်။",
          ["function", "parameter"], CH[2],
          "def hello(name=\"Guest\"):\n    print(\"Hi\", name)\n\nhello()\nhello(\"Su\")"),
        i("concept_qa", "Algorithm ဆိုတာ ဘာလဲ?",
          "Algorithm ဆိုတာ ပြဿနာတစ်ခုကို ဖြေရှင်းတဲ့ အဆင့်ဆင့် လမ်းညွှန် ဖြစ်ပါတယ်။\n\nCode မရေးခင် စဉ်းစားချက်ကို ရှင်းအောင် ရေးပါတယ်။ မှန်ကန်ရင် ဘယ် language နဲ့မဆို ရေးနိုင်ပါတယ်။\n\nဥပမာ ကိန်းနှစ်လုံးပေါင်းရန် လက်ခံ၊ ပေါင်း၊ ပြ သုံးဆင့် ရှိပါတယ်။",
          ["programming"], CH[1]),
        i("concept_qa", "Debugging ဆိုတာ ဘာလဲ?",
          "Debugging ဆိုတာ error ရှာပြီး ပြင်ခြင်း ဖြစ်ပါတယ်။\n\nError message ဖတ်ခြင်း၊ print နဲ့ တန်ဖိုးကြည့်ခြင်း၊ သေးငယ်အောင် ခွဲစစ်ခြင်း လုပ်ပါတယ်။\n\nဥပမာ မှားတဲ့ index ကို တွေ့ရင် မှန်ကန်တဲ့ နေရာ ပြောင်းပါတယ်။",
          ["debug"], CH[2]),
        i("concept_qa", "Module ဆိုတာ ဘာလဲ?",
          "Module ဆိုတာ function နဲ့ variable တွေကို ဖိုင်ခွဲ သိမ်းထားခြင်း ဖြစ်ပါတယ်။\n\nimport နဲ့ ခေါ်သုံးပါတယ်။ ကုဒ်ကို ပြန်သုံးရ လွယ်ပါတယ်။\n\nဥပမာ import math ပြီး math.sqrt(9) သုံးနိုင်ပါတယ်။",
          ["function"], CH[3]),
        i("explain_code", "ဒီ import math code ကို ရှင်းပြပါ။",
          "ဒီ code က စတုရန်းရင်း တွက်ပါတယ်။\n\nmath module က သင်္ချာ function တွေ ပေးပါတယ်။ sqrt(16) က 4.0 ဖြစ်ပါတယ်။\n\nprint က 4.0 ကို ပြပါတယ်။",
          ["function"], CH[3],
          "import math\nprint(math.sqrt(16))"),
        i("explain_code", "ဒီ f-string code ကို ရှင်းပြပါ။",
          "ဒီ code က variable ကို စာသားထဲ ထည့်ပါတယ်။\n\nf\"...{name}...\" က name နေရာမှာ Aung ထည့်ပါတယ်။\n\nMy name is Aung ထွက်ပါတယ်။",
          ["string", "variable"], CH[2],
          "name = \"Aung\"\nprint(f\"My name is {name}\")"),
        i("explain_code", "ဒီ sort code ကို ရှင်းပြပါ။",
          "ဒီ code က list ကို အငယ်ကနေ အကြီး စီပါတယ်။\n\nsort() က မူရင်း list ကို ပြင်ပါတယ်။ 1, 3, 8 အစဉ် ဖြစ်ပါတယ်။\n\nprint က [1, 3, 8] ပြပါတယ်။",
          ["array"], CH[2],
          "nums = [8, 1, 3]\nnums.sort()\nprint(nums)"),
        i("debug_explain", "ဒီ if code ဘာကြောင့် အမြဲ Yes ပြသလဲ?",
          "= က သတ်မှတ်ချက် ဖြစ်ပြီး နှိုင်းယှဉ်တာ မဟုတ်ပါ။\n\nညီမျှမှု စစ်ချင်ရင် == သုံးရပါတယ်။\n\nမှန်ကန်သော code:\nready = False\nif ready == True:\n    print(\"Yes\")\nelse:\n    print(\"No\")",
          ["condition", "operator"], CH[2],
          "ready = False\nif ready = True:\n    print(\"Yes\")"),
        i("debug_explain", "ဒီ dict code ဘာကြောင့် error တက်သလဲ?",
          "city key မရှိပါ။ name နဲ့ age သာ ရှိပါတယ်။\n\nမရှိတဲ့ key ခေါ်ရင် KeyError တက်ပါတယ်။ ရှိတဲ့ key သုံးပါ။\n\nမှန်ကန်သော code:\nuser = {\"name\": \"Su\", \"age\": 18}\nprint(user[\"name\"])",
          ["object", "debug"], CH[2],
          "user = {\"name\": \"Su\", \"age\": 18}\nprint(user[\"city\"])"),
        i("concept_qa", "Immutable ဆိုတာ ဘာလဲ?",
          "Immutable ဆိုတာ တည်ဆောက်ပြီးရင် ပြင်လို့မရတဲ့ data ဖြစ်ပါတယ်။\n\nString နဲ့ tuple က immutable ဖြစ်ပါတယ်။ ပြင်ချင်ရင် တန်ဖိုးအသစ် ထုတ်ရပါတယ်။\n\nဥပမာ name.upper() က စာအသစ် ပေးပြီး မူရင်း name မပြောင်းပါ။",
          ["string"], CH[2]),
        i("concept_qa", "Recursion ဆိုတာ ဘာလဲ?",
          "Recursion ဆိုတာ function က ကိုယ့်ကိုယ်ကို ခေါ်ခြင်း ဖြစ်ပါတယ်။\n\nရပ်တဲ့ အဆုံးအခြေအနေ ရှိမှသာ မဆုံးနိုင်အောင် မဖြစ်ပါ။ သေးငယ်တဲ့ ပြဿနာအဖြစ် ခွဲပါတယ်။\n\nဥပမာ factorial(n) က n * factorial(n-1) လို့ ခေါ်နိုင်ပါတယ်။",
          ["function"], CH[3]),
        i("explain_code", "ဒီ recursion code ကို ရှင်းပြပါ။",
          "ဒီ function က ၃ ရဲ့ factorial တွက်ပါတယ်။\n\nn == 1 ဖြစ်ရင် ၁ ပြန်ပါတယ်။ မဟုတ်ရင် n နဲ့ သေးတဲ့ factorial ကို မြှောက်ပါတယ်။ ၃*၂*၁ = ၆ ဖြစ်ပါတယ်။\n\nprint က ၆ ပြပါတယ်။",
          ["function", "return"], CH[3],
          "def factorial(n):\n    if n == 1:\n        return 1\n    return n * factorial(n - 1)\n\nprint(factorial(3))"),
        i("explain_code", "ဒီ set code ကို ရှင်းပြပါ။",
          "ဒီ code က ထပ်နေတဲ့ တန်ဖိုးတွေကို ဖယ်ပါတယ်။\n\nset က unique တန်ဖိုးသာ သိမ်းပါတယ်။ 1 က တစ်ကြိမ်သာ ကျန်ပါတယ်။\n\nprint က {1, 2, 3} ပုံစံနဲ့ ပြပါတယ်။",
          ["array"], CH[2],
          "items = [1, 2, 2, 3]\nprint(set(items))"),
        i("concept_qa", "Type conversion ဆိုတာ ဘာလဲ?",
          "Type conversion ဆိုတာ data အမျိုးအစား ပြောင်းခြင်း ဖြစ်ပါတယ်။\n\nint(), str(), float() တို့ သုံးပါတယ်။ မှားတဲ့ ပုံစံကို ပြောင်းရင် error တက်နိုင်ပါတယ်။\n\nဥပမာ int(\"10\") က 10 ဖြစ်ပါတယ်။",
          ["integer", "string"], CH[1]),
        i("explain_code", "ဒီ float division code ကို ရှင်းပြပါ။",
          "ဒီ code က ပိုင်းခြေပိုင်းဝေကို ဒဿမအပါ တွက်ပါတယ်။\n\nPython 3 မှာ / က float ရလဒ် ပေးပါတယ်။ 7 / 2 က 3.5 ဖြစ်ပါတယ်။\n\nကိန်းပြည့်ပိုင်းချင်ရင် // သုံးပါတယ်။",
          ["operator"], CH[1],
          "print(7 / 2)"),
        i("explain_code", "ဒီ floor division code ကို ရှင်းပြပါ။",
          "ဒီ code က ကိန်းပြည့်ပိုင်းခြေ ရလဒ် ပေးပါတယ်။\n\n// က ဒဿမကို ဖြတ်ပါတယ်။ 7 // 2 က 3 ဖြစ်ပါတယ်။\n\nလက်ကျန်လိုချင်ရင် % သုံးပါတယ်။",
          ["operator", "integer"], CH[1],
          "print(7 // 2)"),
        i("concept_qa", "Exception ဆိုတာ ဘာလဲ?",
          "Exception ဆိုတာ program မှာ မျှော်လင့်မထားတဲ့ အဖြစ်အပျက် ဖြစ်ပါတယ်။\n\nမဖမ်းရင် program ရပ်ပါတယ်။ try except နဲ့ ဖမ်းပြီး သုံးသူကို ရှင်းပြနိုင်ပါတယ်။\n\nဥပမာ ဖိုင်မရှိရင် FileNotFoundError တက်ပါတယ်။",
          ["debug", "runtime"], CH[2]),
        i("explain_code", "ဒီ break code ကို ရှင်းပြပါ။",
          "ဒီ loop က ၅ ကိုတွေ့တာနဲ့ ရပ်ပါတယ်။\n\nbreak က loop ကို ချက်ချင်း ထွက်ပါတယ်။ ၇ အထိ မဆက်ပါ။\n\n1 3 ပြီးရင် ရပ်ပြီး ၅ ကိုတောင် မပြပါ။ ဒီဥပမာမှာ ၅ မတိုင်ခင် 1 နဲ့ 3 ပဲ ပြပါတယ်။",
          ["loop"], CH[2],
          "for n in [1, 3, 5, 7]:\n    if n == 5:\n        break\n    print(n)"),
        i("explain_code", "ဒီ continue code ကို ရှင်းပြပါ။",
          "ဒီ loop က ၂ ကို ကျော်ပြီး ကျန်တာ ပြပါတယ်။\n\ncontinue က အဲဒီအကြိမ်ရဲ့ ကျန်code ကို ကျော်ပါတယ်။ loop က မရပ်ပါ။\n\n1 နဲ့ 3 ထွက်ပါတယ်။",
          ["loop", "condition"], CH[2],
          "for n in [1, 2, 3]:\n    if n == 2:\n        continue\n    print(n)"),
        i("concept_qa", "Object ဆိုတာ ဘာလဲ?",
          "Object ဆိုတာ class ကနေ ဖန်တီးထားတဲ့ တကယ့် အရာ ဖြစ်ပါတယ်။\n\nကိုယ်ပိုင် data နဲ့ method ရှိပါတယ်။ တစ်ခုနဲ့တစ်ခု တန်ဖိုး မတူနိုင်ပါ။\n\nဥပမာ Dog class ကနေ buddy နဲ့ luna ဆိုပြီး နှစ်ကောင် ရှိနိုင်ပါတယ်။",
          ["class", "object"], CH[3]),
        i("explain_code", "ဒီ inheritance code ကို ရှင်းပြပါ။",
          "ဒီ code က ကလေး class က မိဘ class ရဲ့ method ကို သုံးပါတယ်။\n\nCat က Animal ကို အမွေဆက်ပါတယ်။ speak ကို မရေးဘဲ meow က Animal.speak ကို ခေါ်နိုင်ပါတယ်။\n\nhello ထွက်ပါတယ်။",
          ["class", "method"], CH[3],
          "class Animal:\n    def speak(self):\n        print(\"hello\")\n\nclass Cat(Animal):\n    pass\n\nCat().speak()"),
        i("concept_qa", "Stack နဲ့ queue ဘာကွာလဲ?",
          "Stack က နောက်ဆုံးထည့်တာ အရင်ထွက်ပြီး queue က အရင်ထည့်တာ အရင်ထွက်ပါတယ်။\n\nStack က LIFO၊ queue က FIFO ဖြစ်ပါတယ်။ Function ခေါ်ဆိုမှုက stack နဲ့ တူပါတယ်။\n\nဥပမာ ပန်းကန်စည်းက stack၊ တန်းစီဝယ်တာက queue ဖြစ်ပါတယ်။",
          ["array"], CH[3]),
        i("explain_code", "ဒီ stack append pop ကို ရှင်းပြပါ။",
          "ဒီ code က stack လို နောက်ဆုံးက ပြန်ထုတ်ပါတယ်။\n\nappend က အပေါ်က ထည့်ပါတယ်။ pop က နောက်ဆုံး 30 ကို ယူပါတယ်။\n\nprint က 30 ပြပါတယ်။",
          ["array"], CH[3],
          "stack = [10, 20]\nstack.append(30)\nprint(stack.pop())"),
        i("debug_explain", "ဒီ colon ပျောက်တဲ့ code ကို ပြင်ပါ။",
          "if ကြောင်းအဆုံးမှာ : မပါလို့ syntax error တက်ပါတယ်။\n\nPython block စတဲ့ နေရာမှာ colon လိုပါတယ်။\n\nမှန်ကန်သော code:\nage = 18\nif age >= 18:\n    print(\"Adult\")",
          ["syntax", "condition"], CH[2],
          "age = 18\nif age >= 18\n    print(\"Adult\")"),
        i("concept_qa", "Pseudocode ဆိုတာ ဘာလဲ?",
          "Pseudocode ဆိုတာ language တိတိကျကျ မဟုတ်ဘဲ လူဖတ်ရလွယ်အောင် ရေးတဲ့ အဆင့်များ ဖြစ်ပါတယ်။\n\nစဉ်းစားချက် မှန်မမှန် အရင် စစ်နိုင်ပါတယ်။ ပြီးမှ တကယ့် code ပြောင်းပါတယ်။\n\nဥပမာ လက်ခံ၊ ပေါင်း၊ ပြ လို့ ရေးနိုင်ပါတယ်။",
          ["programming"], CH[1]),
        i("concept_qa", "Integer overflow ကို Python မှာ ဘယ်လိုမြင်လဲ?",
          "Python 3 ရဲ့ integer က အလိုအလျောက် ကြီးနိုင်ပါတယ်။\n\nဘာသာစကားအချို့မှာ ကန့်သတ် bit ရှိပါတယ်။ Python မှာ ကြီးတဲ့ ဂဏန်းကို သာမန်ကိန်းလို သုံးနိုင်ပါတယ်။\n\nဥပမာ 10 ** 50 ကို တိုက်ရိုက် တွက်နိုင်ပါတယ်။",
          ["integer"], CH[1]),
        i("explain_code", "ဒီ boolean and code ကို ရှင်းပြပါ။",
          "ဒီ code က အခြေအနေ နှစ်ခု လုံး မှန်မှ Yes ပြပါတယ်။\n\nand က နှစ်ခုစလုံး True ဖြစ်ရပါတယ်။ age က 20၊ has_id က True ဖြစ်လို့ Yes ထွက်ပါတယ်။\n\nတစ်ခုမှားရင် No ဖြစ်ပါမယ်။",
          ["boolean", "condition"], CH[2],
          "age = 20\nhas_id = True\nif age >= 18 and has_id:\n    print(\"Yes\")\nelse:\n    print(\"No\")"),
        i("explain_code", "ဒီ or condition ကို ရှင်းပြပါ။",
          "ဒီ code က တစ်ခုမှန်ရင် ဝင်ခွင့်ပေးပါတယ်။\n\nis_member က False ဖြစ်ပေမယ့် is_staff က True ဖြစ်လို့ Allow ထွက်ပါတယ်။\n\nနှစ်ခုလုံး False မှ Deny ဖြစ်ပါတယ်။",
          ["boolean", "condition"], CH[2],
          "is_member = False\nis_staff = True\nif is_member or is_staff:\n    print(\"Allow\")\nelse:\n    print(\"Deny\")"),
        i("concept_qa", "Variable နာမည် ရှင်းရှင်းထားရင် ဘာကောင်းလဲ?",
          "Variable နာမည် ရှင်းရင် code ဖတ်ရ လွယ်ပါတယ်။\n\nx1 ထက် student_age က အဓိပ္ပာယ် ပိုပေးပါတယ်။ နောင်ပြင်ရင် အချိန်ကုန် သက်သာပါတယ်။\n\nကောင်းတဲ့ နာမည်က သင်ယူသူနဲ့ အဖွဲ့အတွက် အထောက်အကူ ဖြစ်ပါတယ်။",
          ["variable"], CH[1]),
        i("explain_code", "ဒီ replace code ကို ရှင်းပြပါ။",
          "ဒီ code က စာထဲက စကားလုံး ပြောင်းပါတယ်။\n\nreplace က cat ကို dog နဲ့ လဲပါတယ်။ မူရင်း text က မပြောင်းဘဲ စာအသစ် ရပါတယ်။\n\nI have a dog ထွက်ပါတယ်။",
          ["string"], CH[2],
          "text = \"I have a cat\"\nprint(text.replace(\"cat\", \"dog\"))"),
        i("explain_code", "ဒီ split code ကို ရှင်းပြပါ။",
          "ဒီ code က စာကို space မှာ ခွဲပြီး list လုပ်ပါတယ်။\n\nsplit() က စကားလုံး တစ်လုံးချင်း ခွဲပါတယ်။ သုံးလုံး ရပါတယ်။\n\nprint က ['I', 'love', 'Python'] ပြပါတယ်။",
          ["string", "array"], CH[2],
          "line = \"I love Python\"\nprint(line.split())"),
        i("debug_explain", "ဒီ range loop ဘာကြောင့် ၅ ထိ မရောက်သလဲ?",
          "range(5) က ၀ မှ ၄ ထိသာ ပေးပါတယ်။ ၅ ကို မပါဝင်ပါ။\n\n၁ မှ ၅ ထိ လိုချင်ရင် range(1, 6) သုံးပါ။\n\nမှန်ကန်သော code:\nfor i in range(1, 6):\n    print(i)",
          ["loop"], CH[2],
          "for i in range(5):\n    print(i)"),
        i("concept_qa", "IDE ဆိုတာ ဘာလဲ?",
          "IDE ဆိုတာ code ရေး၊ run၊ error ကြည့်နိုင်တဲ့ ကိရိယာစု ဖြစ်ပါတယ်။\n\nEditor၊ terminal၊ debugger ပေါင်းထားပါတယ်။ စတင်သင်သူတွေ အတွက် အဆင်ပြေပါတယ်။\n\nဥပမာ VS Code သို့မဟုတ် PyCharm သုံးနိုင်ပါတယ်။",
          ["programming"], CH[1]),
        i("concept_qa", "Compiler နဲ့ interpreter ဘာကွာလဲ?",
          "Compiler က အကုန်ပြောင်းပြီးမှ run ပြီး interpreter က တစ်ကြောင်းချင်း ဖတ် run ပါတယ်။\n\nPython က interpreter ပုံစံ ဖြစ်ပါတယ်။ C လို language က compile အရင်လုပ်ပါတယ်။\n\nဒါကြောင့် Python ကို စမ်းရ လွယ်ပါတယ်။",
          ["compile", "runtime"], CH[1]),
        i("explain_code", "ဒီ None check code ကို ရှင်းပြပါ။",
          "ဒီ code က တန်ဖိုး ရှိမရှိ စစ်ပါတယ်။\n\ndata က None ဖြစ်လို့ Empty ပြပါတယ်။ တန်ဖိုးရှိရင် Ready ဖြစ်ပါမယ်။\n\nis None က None ကို တိတိကျကျ စစ်ပါတယ်။",
          ["condition"], CH[2],
          "data = None\nif data is None:\n    print(\"Empty\")\nelse:\n    print(\"Ready\")"),
        i("explain_code", "ဒီ zip code ကို ရှင်းပြပါ။",
          "ဒီ code က နာမည်နဲ့ အမှတ်ကို တွဲပါတယ်။\n\nzip က တူညီတဲ့ နေရာအလိုက် จับคู่ပါတယ်။ Aung 80၊ Mya 90 ဖြစ်ပါတယ်။\n\nနှစ်ကြောင်း ထွက်ပါတယ်။",
          ["array", "loop"], CH[2],
          "names = [\"Aung\", \"Mya\"]\nmarks = [80, 90]\nfor name, mark in zip(names, marks):\n    print(name, mark)"),
        i("concept_qa", "Bug ဆိုတာ ဘာလဲ?",
          "Bug ဆိုတာ program မှာ မှားယွင်းစွာ အလုပ်လုပ်စေတဲ့ အမှား ဖြစ်ပါတယ်။\n\nSyntax မှန်ပေမယ့် ရလဒ်မှားနိုင်ပါတယ်။ စမ်းသပ်ပြီးမှ တွေ့တတ်ပါတယ်။\n\nဥပမာ ပေါင်းချင်တာကို နုတ်မိရင် logic bug ဖြစ်ပါတယ်။",
          ["debug"], CH[2]),
        i("debug_explain", "ဒီ logic bug ကို ရှင်းပြီး ပြင်ပါ။",
          "ပေါင်းချင်ပေမယ့် နုတ်ထားလို့ ရလဒ် မှားပါတယ်။\n\nSyntax မမှားပေမယ့် အဓိပ္ပာယ် မှားပါတယ်။ + သုံးရပါတယ်။\n\nမှန်ကန်သော code:\ndef add(a, b):\n    return a + b\n\nprint(add(10, 4))",
          ["debug", "function"], CH[2],
          "def add(a, b):\n    return a - b\n\nprint(add(10, 4))"),
        i("concept_qa", "Python ကို ဘာကြောင့် စတင်သင်ကြလဲ?",
          "Python က စာကြောင်းတိုတိုနဲ့ အလုပ်များများ လုပ်နိုင်လို့ စတင်သင်ရ လွယ်ပါတယ်။\n\nဝက်ဘ်၊ ဒေတာ၊ အလိုအလျောက်လုပ်ငန်း စတဲ့ နယ်ပယ်တွေမှာလည်း သုံးပါတယ်။ Error message က ဖတ်ရ လွယ်တဲ့အခါများပါတယ်။\n\nprint နဲ့ စမ်းကြည့်ရုံနဲ့ ရလဒ် မြင်နိုင်ပါတယ်။",
          ["programming"], CH[1]),
        i("concept_qa", "print function က ဘာလုပ်သလဲ?",
          "print() က screen ပေါ်မှာ တန်ဖိုး ပြတဲ့ function ဖြစ်ပါတယ်။\n\nကွင်းထဲထည့်တဲ့ စာသား၊ ကိန်း၊ variable ကို ထုတ်ပြပါတယ်။ Program က ဘာဖြစ်နေလဲ ကြည့်ချင်ရင် သုံးပါတယ်။\n\nဥပမာ print(3 + 4) က 7 ပြပါတယ်။",
          ["function"], CH[2]),
        i("concept_qa", "List နဲ့ dictionary ဘာကွာလဲ?",
          "List က အစဉ်လိုက် တန်ဖိုးတွေ သိမ်းပြီး dictionary က key နဲ့ value တွဲသိမ်းပါတယ်။\n\nList မှာ index ၀ က စရေတွက်ပါတယ်။ Dictionary မှာ နာမည်လို key နဲ့ ရှာပါတယ်။\n\nဥပမာ scores[\"Aung\"] က Aung ရဲ့ အမှတ်ကို တိုက်ရိုက် ပေးပါတယ်။",
          ["array", "object"], CH[2]),
        i("concept_qa", "for loop နဲ့ while loop ဘာကွာလဲ?",
          "for loop က အရေအတွက် သို့မဟုတ် စာရင်းအလိုက် လှည့်ပြီး while က အခြေအနေ မှန်နေသ၍ လှည့်ပါတယ်။\n\nအကြိမ်ရေ သိရင် for သုံးရ လွယ်ပါတယ်။ မသိရင် while သုံးပါတယ်။ ရပ်တဲ့ အခြေအနေ မရှိရင် while က မဆုံးနိုင်ပါ။\n\nဥပမာ range(5) က for နဲ့ ငါးကြိမ် လုပ်နိုင်ပါတယ်။",
          ["loop"], CH[2]),
        i("concept_qa", "def က ဘာအတွက်လဲ?",
          "def က Python မှာ function စရေးတဲ့ keyword ဖြစ်ပါတယ်။\n\nနာမည်၊ parameter၊ ပြီးရင် block ထဲက အလုပ်တွေ ရေးပါတယ်။ ခေါ်လိုက်မှသာ အထဲက code အလုပ်လုပ်ပါတယ်။\n\nဥပမာ def greet(): ဆိုပြီး နှုတ်ဆက် function စနိုင်ပါတယ်။",
          ["function"], CH[2]),
        i("concept_qa", "elif ဆိုတာ ဘာလဲ?",
          "elif က if မမှန်ရင် နောက်အခြေအနေကို စစ်တာ ဖြစ်ပါတယ်။\n\nif၊ elif၊ else ကို အပေါ်ကနေ အောက်ကို စစ်ပါတယ်။ ပထမမှန်တာ တစ်ခုပဲ လုပ်ပါတယ်။\n\nဥပမာ အမှတ် ၈၀ နှင့်အထက် Distinction၊ ၅၀ နှင့်အထက် Pass လို့ ခွဲနိုင်ပါတယ်။",
          ["condition"], CH[2]),
        i("concept_qa", "try except က ဘာကြောင့် လိုသလဲ?",
          "try except က error တက်ရင် program မပျက်အောင် ဖမ်းတဲ့ နည်း ဖြစ်ပါတယ်။\n\ntry ထဲမှာ စမ်းလုပ်ပြီး except ထဲမှာ အသုံးပြုသူကို ရှင်းပြနိုင်ပါတယ်။ မဖမ်းရင် runtime မှာ ရပ်သွားပါတယ်။\n\nဥပမာ int(\"abc\") က ValueError ဖြစ်နိုင်ပါတယ်။",
          ["debug", "runtime"], CH[2]),
        i("concept_qa", "import က ဘာလုပ်သလဲ?",
          "import က တခြား ဖိုင် သို့မဟုတ် module ထဲက ကုဒ်ကို ခေါ်သုံးစေပါတယ်။\n\nရေးပြီးသား function တွေ ပြန်မရေးရအောင် သုံးပါတယ်။ math၊ random လို standard module တွေ ရှိပါတယ်။\n\nဥပမာ import math ပြီး math.pi ကို သုံးနိုင်ပါတယ်။",
          ["function"], CH[3]),
        i("concept_qa", "slicing ဆိုတာ ဘာလဲ?",
          "slicing ဆိုတာ list သို့မဟုတ် string ရဲ့ အပိုင်းတစ်ခုကို ဖြတ်ယူခြင်း ဖြစ်ပါတယ်။\n\n[start:end] မှာ end က မပါဝင်ပါ။ မူရင်း တန်ဖိုးက မပျက်ပါ။\n\nဥပမာ \"Python\"[0:2] က Py ဖြစ်ပါတယ်။",
          ["array", "string"], CH[2]),
        i("concept_qa", "append က ဘာလုပ်သလဲ?",
          "append() က list ရဲ့ နောက်ဆုံးမှာ တန်ဖိုး ထည့်ပါတယ်။\n\nမူရင်း list ကို ပြင်ပါတယ်။ အရှည်က တစ်ခု တိုးပါတယ်။\n\nဥပမာ nums = [1, 2] ပြီး nums.append(3) ဆိုရင် [1, 2, 3] ဖြစ်ပါတယ်။",
          ["array"], CH[2]),
        i("concept_qa", "ဖိုင် ဖတ်ရေးတာ Python မှာ ဘယ်လိုလုပ်သလဲ?",
          "open() နဲ့ ဖိုင်ဖွင့်ပြီး read သို့မဟုတ် write လုပ်ပါတယ်။\n\nwith open သုံးရင် ဖိုင်ကို အလိုအလျောက် ပိတ်ပေးပါတယ်။ mode က r က ဖတ်၊ w က ရေး ဖြစ်ပါတယ်။\n\nဥပမာ f.read() က ဖိုင်ထဲက စာကို ယူပါတယ်။",
          ["function"], CH[2]),
        i("concept_qa", "range function က ဘာပေးသလဲ?",
          "range() က ကိန်းစဉ် တစ်ခု ထုတ်ပေးပါတယ်။\n\nrange(n) က ၀ မှ n-1 ထိ ပေးပါတယ်။ စ၊ ဆုံး၊ ခြေလှမ်း သတ်မှတ်နိုင်ပါတယ်။\n\nဥပမာ range(1, 4) က 1, 2, 3 ပေးပါတယ်။",
          ["loop"], CH[2]),
        i("concept_qa", "len function က ဘာတိုင်းသလဲ?",
          "len() က စာရင်း၊ စာသား၊ သို့မဟုတ် အခြား စုထဲမှာ ဘယ်နှစ်ခု ရှိလဲ တိုင်းပါတယ်။\n\nအကြီးဆုံး တန်ဖိုး မဟုတ်ပါ။ အရေအတွက်သာ ဖြစ်ပါတယ်။\n\nဥပမာ len(\"hi\") က 2 ဖြစ်ပါတယ်။",
          ["function", "array"], CH[2]),
        i("concept_qa", "class နဲ့ instance ဘာကွာလဲ?",
          "class က ပုံစံခွက် ဖြစ်ပြီး instance က အဲဒီပုံစံကနေ လုပ်ထားတဲ့ object ဖြစ်ပါတယ်။\n\nclass ထဲမှာ data နဲ့ method သတ်မှတ်ပါတယ်။ instance တစ်ခုချင်းမှာ ကိုယ်ပိုင် တန်ဖိုး ရှိနိုင်ပါတယ်။\n\nဥပမာ Dog class ကနေ buddy နဲ့ luna နှစ်ကောင် ဖန်တီးနိုင်ပါတယ်။",
          ["class", "object"], CH[3]),
        i("concept_qa", "self ဆိုတာ ဘာလဲ?",
          "self က method ထဲမှာ ကိုယ့် object ကို ရည်ညွှန်းတဲ့ ပထမ parameter ဖြစ်ပါတယ်။\n\ninstance ရဲ့ variable ကို self.name လို သုံးပါတယ်။ ခေါ်တဲ့အခါ သင်ကိုယ်တိုင် မပို့ရပါ။\n\nဥပမာ pet.name ကို method ထဲမှာ self.name လို့ ကြည့်ပါတယ်။",
          ["class", "method"], CH[3]),
        i("concept_qa", "dictionary ဆိုတာ ဘာလဲ?",
          "dictionary ဆိုတာ key နဲ့ value တွဲပြီး သိမ်းတဲ့ စု ဖြစ်ပါတယ်။\n\n{} နဲ့ ရေးပါတယ်။ ရှာချင်တဲ့ နာမည်ကို key အဖြစ် သုံးပါတယ်။ မရှိတဲ့ key ခေါ်ရင် KeyError တက်နိုင်ပါတယ်။\n\nဥပမာ {\"age\": 20} မှာ age က key ဖြစ်ပါတယ်။",
          ["object"], CH[2]),
        i("concept_qa", "set ဆိုတာ ဘာလဲ?",
          "set ဆိုတာ ထပ်နေတဲ့ တန်ဖိုး မထားတဲ့ စု ဖြစ်ပါတယ်။\n\nအစဉ် မသေချာပါ။ unique တန်ဖိုးပဲ လိုချင်ရင် သုံးပါတယ်။\n\nဥပမာ set([1, 1, 2]) က {1, 2} ဖြစ်ပါတယ်။",
          ["array"], CH[2]),
        i("concept_qa", "f-string ဆိုတာ ဘာလဲ?",
          "f-string က စာသားထဲမှာ variable ကို တိုက်ရိုက် ထည့်တဲ့ နည်း ဖြစ်ပါတယ်။\n\nf\"...{name}...\" လို့ ရေးပါတယ်။ + နဲ့ ပေါင်းတာထက် ဖတ်ရ လွယ်ပါတယ်။\n\nဥပမာ name = \"Mya\" ဆိုရင် f\"Hi {name}\" က Hi Mya ဖြစ်ပါတယ်။",
          ["string", "variable"], CH[2]),
        i("concept_qa", "Boolean operator ဆိုတာ ဘာလဲ?",
          "Boolean operator က True False တွေကို ပေါင်းစစ်တဲ့ and၊ or၊ not ဖြစ်ပါတယ်။\n\nand က နှစ်ခုလုံး မှန်ရပါတယ်။ or က တစ်ခုမှန်ရင် ရပါတယ်။ not က ပြောင်းပြန် လုပ်ပါတယ်။\n\nဥပမာ age >= 18 and has_id ဆိုရင် နှစ်ခုစလုံး ကြည့်ပါတယ်။",
          ["boolean", "operator"], CH[1]),
        i("concept_qa", "IndexError ဆိုတာ ဘာလဲ?",
          "IndexError ဆိုတာ မရှိတဲ့ နေရာကို list ကနေ ခေါ်လို့ ဖြစ်တဲ့ runtime error ဖြစ်ပါတယ်။\n\nအရှည် ၃ ခုရှိရင် index က ၀၊ ၁၊ ၂ သာ ရပါတယ်။ နောက်ဆုံးကို -1 နဲ့လည်း ယူနိုင်ပါတယ်။\n\nဥပမာ items[3] က သုံးလုံးပဲ ရှိရင် မှားပါတယ်။",
          ["array", "debug"], CH[2]),
        i("concept_qa", "KeyError ဆိုတာ ဘာလဲ?",
          "KeyError ဆိုတာ dictionary ထဲမှာ မရှိတဲ့ key ကို ခေါ်လို့ ဖြစ်ပါတယ်။\n\nin နဲ့ အရင်စစ်နိုင်ပါတယ်။ get() သုံးရင် မရှိရင် None ပြန်နိုင်ပါတယ်။\n\nဥပမာ user[\"city\"] က city မထည့်ရင် error တက်ပါတယ်။",
          ["object", "debug"], CH[2]),
        i("concept_qa", "ValueError ဆိုတာ ဘာလဲ?",
          "ValueError ဆိုတာ အမျိုးအစား မှန်ပေမယ့် တန်ဖိုးက ပြောင်းလို့မရတဲ့အခါ ဖြစ်ပါတယ်။\n\nint(\"abc\") လို စာကို ကိန်းပြောင်းရင် တက်တတ်ပါတယ်။ try except နဲ့ ဖမ်းနိုင်ပါတယ်။\n\nuser ထည့်တာ မှားရင် ရှင်းတဲ့ စာပြန်ပြသင့်ပါတယ်။",
          ["debug", "integer"], CH[2]),
        i("concept_qa", "mutable ဆိုတာ ဘာလဲ?",
          "mutable ဆိုတာ ဖန်တီးပြီးနောက် ပြင်လို့ရတဲ့ data ဖြစ်ပါတယ်။\n\nlist နဲ့ dictionary က mutable ဖြစ်ပါတယ်။ string က မပြင်ရပါ။\n\nဥပမာ nums.append(1) က မူရင်း list ကို ပြောင်းပါတယ်။",
          ["array"], CH[2]),
        i("concept_qa", "keyword ဆိုတာ ဘာလဲ?",
          "keyword ဆိုတာ Python က ကြိုသတ်မှတ်ထားတဲ့ စကားလုံး ဖြစ်ပါတယ်။\n\nif၊ def၊ return တို့ကို variable နာမည်အဖြစ် မသုံးရပါ။ Interpreter က အဓိပ္ပာယ် ပေးပြီးသား ဖြစ်ပါတယ်။\n\nဥပမာ class = 1 လို့ ရေးလို့ မရပါ။",
          ["syntax"], CH[1]),
        i("concept_qa", "script ဆိုတာ ဘာလဲ?",
          "script ဆိုတာ အပေါ်ကနေ အောက်ကို run တဲ့ ပရိုဂရမ် ဖိုင် ဖြစ်ပါတယ်။\n\nPython ဖိုင်က .py နဲ့ ဆုံးပါတယ်။ terminal ကနေ python file.py လို့ ခေါ်ပါတယ်။\n\nဥပမာ hello.py ထဲက print က ဖိုင် run တဲ့အခါ ထွက်ပါတယ်။",
          ["programming"], CH[1]),
        i("concept_qa", "REPL ဆိုတာ ဘာလဲ?",
          "REPL ဆိုတာ ရိုက်၊ ဖတ်၊ အလုပ်လုပ်၊ ပြ ပြန်လုပ်တဲ့ စမ်းသပ် မျက်နှာပြင် ဖြစ်ပါတယ်။\n\npython လို့ ရိုက်ဝင်ပြီး တစ်ကြောင်းချင်း စမ်းနိုင်ပါတယ်။ သင်ယူစမှာ အဆင်ပြေပါတယ်။\n\nဥပမာ 2 + 2 ရိုက်ရင် 4 ချက်ချင်း မြင်ပါတယ်။",
          ["programming"], CH[1]),
        i("explain_code", "ဒီ dict keys code ကို ရှင်းပြပါ။",
          "ဒီ code က dictionary ထဲက key တွေကို ပြပါတယ်။\n\nkeys() က name နဲ့ age ကို ပေးပါတယ်။ for က တစ်ခုချင်း print လုပ်ပါတယ်။\n\nနှစ်ကြောင်း ထွက်ပါတယ်။",
          ["object", "loop"], CH[2],
          "info = {\"name\": \"Su\", \"age\": 21}\nfor key in info.keys():\n    print(key)"),
        i("explain_code", "ဒီ dict get code ကို ရှင်းပြပါ။",
          "ဒီ code က မရှိတဲ့ key ကို ဘေးကင်းစွာ ယူပါတယ်။\n\nget(\"city\", \"Yangon\") က city မရှိလို့ Yangon ပြန်ပါတယ်။ KeyError မတက်ပါ။\n\nprint က Yangon ပြပါတယ်။",
          ["object", "function"], CH[2],
          "user = {\"name\": \"Su\"}\nprint(user.get(\"city\", \"Yangon\"))"),
        i("explain_code", "ဒီ list pop code ကို ရှင်းပြပါ။",
          "ဒီ code က နောက်ဆုံး တန်ဖိုးကို ထုတ်ယူပါတယ်။\n\npop() က 30 ကို ယူပြီး list ထဲက ဖယ်ပါတယ်။ ကျန်တာက [10, 20] ဖြစ်ပါတယ်။\n\nprint က 30 ပြပါတယ်။",
          ["array"], CH[2],
          "nums = [10, 20, 30]\nprint(nums.pop())"),
        i("explain_code", "ဒီ insert code ကို ရှင်းပြပါ။",
          "ဒီ code က list ရဲ့ အလယ်မှာ တန်ဖိုး ထည့်ပါတယ်။\n\ninsert(1, \"b\") က index ၁ နေရာမှာ b ထည့်ပါတယ်။ နောက်ကဟာတွေ ရွေ့ပါတယ်။\n\nရလဒ်က ['a', 'b', 'c'] ဖြစ်ပါတယ်။",
          ["array"], CH[2],
          "letters = [\"a\", \"c\"]\nletters.insert(1, \"b\")\nprint(letters)"),
        i("explain_code", "ဒီ join code ကို ရှင်းပြပါ။",
          "ဒီ code က list ထဲက စာတွေကို တစ်ကြောင်းတည်း ပေါင်းပါတယ်။\n\n\"-\".join က ကြားမှာ မျဉ်းတို ထည့်ပါတယ်။ A-B-C ဖြစ်ပါတယ်။\n\nprint က A-B-C ပြပါတယ်။",
          ["string", "array"], CH[2],
          "parts = [\"A\", \"B\", \"C\"]\nprint(\"-\".join(parts))"),
        i("explain_code", "ဒီ strip code ကို ရှင်းပြပါ။",
          "ဒီ code က ရှေ့နောက် space တွေ ဖယ်ပါတယ်။\n\nstrip() က အလယ်စာကို မထိပါ။ user ရိုက်တဲ့ အပိုနေရာ ရှင်းဖို့ သုံးပါတယ်။\n\nprint က hi ပြပါတယ်။",
          ["string"], CH[2],
          "text = \"  hi  \"\nprint(text.strip())"),
        i("explain_code", "ဒီ lower code ကို ရှင်းပြပါ။",
          "ဒီ code က စာလုံးအကြီးကို အသေး ပြောင်းပါတယ်။\n\nlower() က နှိုင်းယှဉ်ရ လွယ်အောင် သုံးပါတယ်။ Hello က hello ဖြစ်ပါတယ်။\n\nမူရင်း text က မပြောင်းပါ။",
          ["string"], CH[2],
          "text = \"Hello\"\nprint(text.lower())"),
        i("explain_code", "ဒီ in check code ကို ရှင်းပြပါ။",
          "ဒီ code က စာရင်းထဲမှာ တန်ဖိုး ရှိမရှိ စစ်ပါတယ်။\n\n\"mango\" in fruits က True ဖြစ်လို့ Found ပြပါတယ်။ မရှိရင် Missing ဖြစ်ပါမယ်။\n\nin က membership စစ်ပါတယ်။",
          ["array", "condition"], CH[2],
          "fruits = [\"apple\", \"mango\"]\nif \"mango\" in fruits:\n    print(\"Found\")\nelse:\n    print(\"Missing\")"),
        i("explain_code", "ဒီ elif code ကို ရှင်းပြပါ။",
          "ဒီ code က အမှတ်အလိုက် အဆင့် ခွဲပါတယ်။\n\nscore က ၈၅ ဖြစ်လို့ ပထမ if မှန်ပြီး A ပြပါတယ်။ elif နဲ့ else မရောက်ပါ။\n\n၄၀ ဆိုရင် C ထွက်ပါမယ်။",
          ["condition"], CH[2],
          "score = 85\nif score >= 80:\n    print(\"A\")\nelif score >= 50:\n    print(\"B\")\nelse:\n    print(\"C\")"),
        i("explain_code", "ဒီ while countdown ကို ရှင်းပြပါ။",
          "ဒီ loop က ၃ ကနေ ၁ အထိ ရေတွက်ဆင်းပါတယ်။\n\nn က ၃၊ ၂၊ ၁ ပြပြီး တစ်ခါတိုင်း ၁ လျော့ပါတယ်။ ၀ ရောက်ရင် ရပ်ပါတယ်။\n\nသုံးကြောင်း ထွက်ပါတယ်။",
          ["loop"], CH[2],
          "n = 3\nwhile n > 0:\n    print(n)\n    n = n - 1"),
        i("explain_code", "ဒီ nested if ကို ရှင်းပြပါ။",
          "ဒီ code က အသက်နဲ့ ကတ် နှစ်ခုစလုံး စစ်ပါတယ်။\n\nage က ၂၀ ဖြစ်လို့ အပြင် if ဝင်ပါတယ်။ has_card က True ဖြစ်လို့ OK ထွက်ပါတယ်။\n\nကတ်မရှိရင် No card ဖြစ်ပါမယ်။",
          ["condition", "boolean"], CH[2],
          "age = 20\nhas_card = True\nif age >= 18:\n    if has_card:\n        print(\"OK\")\n    else:\n        print(\"No card\")\nelse:\n    print(\"Too young\")"),
        i("explain_code", "ဒီ list copy code ကို ရှင်းပြပါ။",
          "ဒီ code က list မိတ္တူ လုပ်ပြီး ပြင်ပါတယ်။\n\n[:] က စာရင်းအသစ် ကူးပါတယ်။ b.append(3) က a ကို မထိပါ။\n\na က [1, 2] ဖြစ်ပြီး b က [1, 2, 3] ဖြစ်ပါတယ်။",
          ["array"], CH[2],
          "a = [1, 2]\nb = a[:]\nb.append(3)\nprint(a)\nprint(b)"),
        i("explain_code", "ဒီ tuple unpack ကို ရှင်းပြပါ။",
          "ဒီ code က တွဲထားတဲ့ တန်ဖိုးတွေကို ခွဲထုတ်ပါတယ်။\n\nx မှာ 3၊ y မှာ 4 ရပါတယ်။ tuple က ပြင်လို့မရပါ။\n\nprint က 3 4 ပြပါတယ်။",
          ["array", "variable"], CH[2],
          "point = (3, 4)\nx, y = point\nprint(x, y)"),
        i("explain_code", "ဒီ random choice code ကို ရှင်းပြပါ။",
          "ဒီ code က စာရင်းထဲက တစ်ခု ကျပန်း ရွေးပါတယ်။\n\nrandom.choice က colors ထဲက တစ်ခု ပေးပါတယ်။ run တိုင်း မတူနိုင်ပါ။\n\nprint က red၊ green သို့မဟုတ် blue ပြပါတယ်။",
          ["function", "array"], CH[3],
          "import random\ncolors = [\"red\", \"green\", \"blue\"]\nprint(random.choice(colors))"),
        i("explain_code", "ဒီ file read code ကို ရှင်းပြပါ။",
          "ဒီ code က ဖိုင်ထဲက စာကို ဖတ်ပါတယ်။\n\nr mode က ဖတ်ရန် ဖွင့်ပါတယ်။ read() က အကြောင်းအရာ တစ်ခုလုံး ယူပါတယ်။\n\nnote.txt ထဲမှာ ရှိသမျှ print ထွက်ပါတယ်။",
          ["function"], CH[2],
          "with open(\"note.txt\", \"r\") as f:\n    print(f.read())"),
        i("explain_code", "ဒီ startswith code ကို ရှင်းပြပါ။",
          "ဒီ code က စာက Py နဲ့ စမစ စစ်ပါတယ်။\n\nstartswith(\"Py\") က True ဖြစ်လို့ Yes ပြပါတယ်။ စာလုံးအကြီးအသေး တူရပါတယ်။\n\njava ဆိုရင် No ဖြစ်ပါမယ်။",
          ["string", "condition"], CH[2],
          "name = \"Python\"\nif name.startswith(\"Py\"):\n    print(\"Yes\")\nelse:\n    print(\"No\")"),
        i("explain_code", "ဒီ dict update ကို ရှင်းပြပါ။",
          "ဒီ code က အသက် တန်ဖိုး ပြင်ပါတယ်။\n\nage key ရှိပြီးသားမို့ 18 က 19 ဖြစ်ပါတယ်။ key အသစ်ဆို ထည့်ပါမယ်။\n\nprint က 19 ပြပါတယ်။",
          ["object"], CH[2],
          "user = {\"name\": \"Aung\", \"age\": 18}\nuser[\"age\"] = 19\nprint(user[\"age\"])"),
        i("explain_code", "ဒီ sum code ကို ရှင်းပြပါ။",
          "ဒီ code က list ထဲက ဂဏန်းတွေ ပေါင်းပါတယ်။\n\nsum() က 1 + 2 + 3 = 6 ပေးပါတယ်။ ကိုယ်တိုင် loop မရေးရပါ။\n\nprint က 6 ပြပါတယ်။",
          ["array", "function"], CH[2],
          "nums = [1, 2, 3]\nprint(sum(nums))"),
        i("explain_code", "ဒီ min code ကို ရှင်းပြပါ။",
          "ဒီ code က အငယ်ဆုံး ဂဏန်း ရှာပါတယ်။\n\nmin() က 2 ကို ရွေးပါတယ်။ max နဲ့ ဆန့်ကျင်ဘက် ဖြစ်ပါတယ်။\n\nprint က 2 ပြပါတယ်။",
          ["array", "function"], CH[2],
          "nums = [9, 2, 7]\nprint(min(nums))"),
        i("explain_code", "ဒီ count code ကို ရှင်းပြပါ။",
          "ဒီ code က a ဘယ်နှစ်ခါ ပါလဲ ရေတွက်ပါတယ်။\n\ncount(\"a\") က ၃ ကြိမ် တွေ့ပါတယ်။ မရှိရင် ၀ ပြန်ပါတယ်။\n\nprint က 3 ပြပါတယ်။",
          ["string", "function"], CH[2],
          "text = \"banana\"\nprint(text.count(\"a\"))"),
        i("explain_code", "ဒီ list multiply ကို ရှင်းပြပါ။",
          "ဒီ code က သုည သုံးလုံးရှိတဲ့ list လုပ်ပါတယ်။\n\n[0] * 3 က တူညီတဲ့ တန်ဖိုး ထပ်ပါတယ်။ index သုံးခု ရပါတယ်။\n\nprint က [0, 0, 0] ပြပါတယ်။",
          ["array"], CH[2],
          "zeros = [0] * 3\nprint(zeros)"),
        i("explain_code", "ဒီ not condition ကို ရှင်းပြပါ။",
          "ဒီ code က ready မဟုတ်ရင် Wait ပြပါတယ်။\n\nnot False က True ဖြစ်လို့ Wait ထွက်ပါတယ်။ ready True ဖြစ်ရင် Go ဖြစ်ပါမယ်။\n\nnot က boolean ပြောင်းပြန် လုပ်ပါတယ်။",
          ["boolean", "condition"], CH[2],
          "ready = False\nif not ready:\n    print(\"Wait\")\nelse:\n    print(\"Go\")"),
        i("explain_code", "ဒီ string index ကို ရှင်းပြပါ။",
          "ဒီ code က ပထမဆုံး စာလုံး ယူပါတယ်။\n\nword[0] က P ဖြစ်ပါတယ်။ string ကို index နဲ့ ဖတ်လို့ရပါတယ်။\n\nprint က P ပြပါတယ်။",
          ["string"], CH[2],
          "word = \"Python\"\nprint(word[0])"),
        i("explain_code", "ဒီ negative index ကို ရှင်းပြပါ။",
          "ဒီ code က နောက်ဆုံး တန်ဖိုး ယူပါတယ်။\n\n-1 က နောက်ကနေ ပထမနေရာ ဖြစ်ပါတယ်။ 40 ရပါတယ်။\n\nprint က 40 ပြပါတယ်။",
          ["array"], CH[2],
          "data = [10, 20, 30, 40]\nprint(data[-1])"),
        i("explain_code", "ဒီ pass class ကို ရှင်းပြပါ။",
          "ဒီ code က ဗလာ class ထားပါတယ်။\n\npass က ဘာမှ မလုပ်တဲ့ နေရာဖြည့် ဖြစ်ပါတယ်။ syntax အတွက် block လိုအပ်ပါတယ်။\n\nEmpty() ခေါ်ရုံနဲ့ error မတက်ပါ။",
          ["class", "syntax"], CH[3],
          "class Empty:\n    pass\n\nEmpty()"),
        i("debug_explain", "ဒီ append မှားသုံးတာ ပြင်ပါ။",
          "append က list မှာပဲ သုံးရပါတယ်။ string မှာ မရပါ။\n\nစာပေါင်းချင်ရင် + သို့မဟုတ် f-string သုံးပါ။\n\nမှန်ကန်သော code:\nname = \"Aung\"\nprint(name + \" Min\")",
          ["string", "array", "debug"], CH[2],
          "name = \"Aung\"\nname.append(\" Min\")\nprint(name)"),
        i("debug_explain", "ဒီ immutable string ကို ပြင်ပါ။",
          "string ရဲ့ index ကို တိုက်ရိုက် ပြင်လို့မရပါ။\n\nစာအသစ် ပြန်ပေါင်းပြီး သိမ်းရပါတယ်။\n\nမှန်ကန်သော code:\nword = \"cat\"\nword = \"b\" + word[1:]\nprint(word)",
          ["string", "debug"], CH[2],
          "word = \"cat\"\nword[0] = \"b\"\nprint(word)"),
        i("debug_explain", "ဒီ for variable မှားတာ ပြင်ပါ။",
          "loop variable က n ဖြစ်ပေမယ့် print က i ကို သုံးထားလို့ NameError တက်ပါတယ်။\n\nတူညီတဲ့ နာမည် သုံးရပါတယ်။\n\nမှန်ကန်သော code:\nfor n in range(3):\n    print(n)",
          ["loop", "debug"], CH[2],
          "for n in range(3):\n    print(i)"),
        i("debug_explain", "ဒီ dict key quote ပြင်ပါ။",
          "age က variable မဟုတ်ဘဲ key စာသား ဖြစ်ရပါတယ်။\n\nquote မပါရင် NameError တက်ပါတယ်။\n\nမှန်ကန်သော code:\nuser = {\"age\": 18}\nprint(user[\"age\"])",
          ["object", "syntax"], CH[2],
          "user = {\"age\": 18}\nprint(user[age])"),
        i("debug_explain", "ဒီ float ကို int ပေါင်းမှားတာ ပြင်ပါ။",
          "input က string ဖြစ်လို့ တိုက်ရိုက် ပေါင်းရင် စာပေါင်း ဖြစ်နိုင်ပါတယ်။ ကိန်းချင်ရင် float() သုံးပါ။\n\nဒဿမ ပါနိုင်လို့ int မဟုတ်ဘဲ float က ပိုလုံခြုံပါတယ်။\n\nမှန်ကန်သော code:\na = float(input())\nb = float(input())\nprint(a + b)",
          ["string", "integer"], CH[2],
          "a = input()\nb = input()\nprint(a + b)"),
        i("debug_explain", "ဒီ list မျှဝေမှု ပြင်ပါ။",
          "b = a က မိတ္တူ မဟုတ်ဘဲ list တစ်ခုတည်းကို ညွှန်းပါတယ်။\n\nb ပြင်ရင် a ပါ ပြောင်းပါတယ်။ ကူးချင်ရင် copy သို့မဟုတ် [:] သုံးပါ။\n\nမှန်ကန်သော code:\na = [1, 2]\nb = a[:]\nb.append(3)\nprint(a)",
          ["array", "debug"], CH[2],
          "a = [1, 2]\nb = a\nb.append(3)\nprint(a)"),
        i("debug_explain", "ဒီ return indent ပြင်ပါ။",
          "return က for နဲ့ အတူတူ အဆင့်မှာ ရှိလို့ ပထမအကြိမ်မှာပဲ ရပ်ပါတယ်။\n\nပေါင်းပြီးမှ ပြန်ချင်ရင် loop အပြင်မှာ return ထားပါ။\n\nမှန်ကန်သော code:\ndef total(nums):\n    s = 0\n    for n in nums:\n        s = s + n\n    return s\n\nprint(total([1, 2, 3]))",
          ["function", "loop", "syntax"], CH[2],
          "def total(nums):\n    s = 0\n    for n in nums:\n        s = s + n\n        return s\n\nprint(total([1, 2, 3]))"),
        i("concept_qa", "package ဆိုတာ ဘာလဲ?",
          "package ဆိုတာ module ဖိုင်တွေကို ဖိုလ်ဒါလို စုထားခြင်း ဖြစ်ပါတယ်။\n\nကြီးတဲ့ ပရိုဂရမ်ကို အပိုင်းခွဲပါတယ်။ import package.module လို့ ခေါ်နိုင်ပါတယ်။\n\nဥပမာ စံ library ထဲမှာလည်း package တွေ ရှိပါတယ်။",
          ["function"], CH[3]),
        i("concept_qa", "virtual environment ဆိုတာ ဘာလဲ?",
          "virtual environment ဆိုတာ ပရောဂျက်တစ်ခုအတွက် သီးသန့် package နေရာ ဖြစ်ပါတယ်။\n\nတခြား ပရောဂျက်နဲ့ version မရောအောင် ကာကွယ်ပါတယ်။ pip install က အဲဒီထဲမှာပဲ ဝင်ပါတယ်။\n\nဥပမာ python -m venv .venv နဲ့ ဖန်တီးနိုင်ပါတယ်။",
          ["programming"], CH[3]),
        i("concept_qa", "pip ဆိုတာ ဘာလဲ?",
          "pip ဆိုတာ Python package တွေ ထည့်၊ ဖယ်တဲ့ ကိရိယာ ဖြစ်ပါတယ်။\n\nရေးပြီးသား library ကို ပြန်မရေးရအောင် သုံးပါတယ်။ requirements.txt နဲ့ စာရင်း သိမ်းနိုင်ပါတယ်။\n\nဥပမာ pip install requests လို့ သုံးပါတယ်။",
          ["programming"], CH[3]),
        i("concept_qa", "comment နဲ့ docstring ဘာကွာလဲ?",
          "comment က တစ်ကြောင်း မှတ်ချက် ဖြစ်ပြီး docstring က function သို့မဟုတ် module ကို ရှင်းပြတဲ့ စာ ဖြစ်ပါတယ်။\n\n# နဲ့ စတာ comment ပါ။ သုံးလုံး quote က docstring ပါ။ help() က docstring ကို ပြနိုင်ပါတယ်။\n\nဥပမာ def add(a, b): နောက်မှာ ရှင်းပြစာ ထားနိုင်ပါတယ်။",
          ["function", "programming"], CH[2]),
        i("concept_qa", "truthy နဲ့ falsy ဆိုတာ ဘာလဲ?",
          "if မှာ သုံးရင် တန်ဖိုးအချို့ကို True သို့မဟုတ် False လို သဘောထားပါတယ်။\n\n0၊ ဗလာစာ၊ ဗလာ list၊ None က falsy ဖြစ်တတ်ပါတယ်။ တန်ဖိုးရှိတဲ့ list က truthy ဖြစ်ပါတယ်။\n\nဥပမာ if items: ဆိုရင် ဗလာမဟုတ်မှ ဝင်ပါတယ်။",
          ["boolean", "condition"], CH[2]),
        i("concept_qa", "stack trace ဆိုတာ ဘာလဲ?",
          "stack trace ဆိုတာ error တက်တဲ့အခါ ဘယ် function က ဘယ်နေရာက ခေါ်လဲ ပြတဲ့ စာရင်း ဖြစ်ပါတယ်။\n\nအောက်ဆုံးက အမှားဖြစ်တဲ့ ကြောင်း ဖြစ်တတ်ပါတယ်။ ဖတ်တတ်ရင် debug မြန်ပါတယ်။\n\nဥပမာ ဖိုင်နာမည်နဲ့ ကြောင်းနံပါတ် ပါပါတယ်။",
          ["debug", "runtime"], CH[2]),
        i("concept_qa", "unit test ဆိုတာ ဘာလဲ?",
          "unit test ဆိုတာ function တစ်ခုချင်း မှန်မမှန် အလိုအလျောက် စစ်တဲ့ ကုဒ် ဖြစ်ပါတယ်။\n\nလက်နဲ့ print ကြည့်တာထက် ပြန်စစ်ရ လွယ်ပါတယ်။ assert နဲ့ မျှော်လင့်တဲ့ ရလဒ် တိုက်ပါတယ်။\n\nဥပမာ add(2, 3) က 5 ဖြစ်ရမယ် လို့ စစ်နိုင်ပါတယ်။",
          ["function", "debug"], CH[3]),
        i("explain_code", "ဒီ assert code ကို ရှင်းပြပါ။",
          "ဒီ code က ပေါင်းလဒ် မှန်မမှန် စစ်ပါတယ်။\n\nassert က မှန်ရင် ဆက်သွားပါတယ်။ မှားရင် AssertionError တက်ပါတယ်။ 2 + 3 က 5 ဖြစ်လို့ အောင်ပါတယ်။\n\nprint က ok ပြပါတယ်။",
          ["debug", "function"], CH[3],
          "assert 2 + 3 == 5\nprint(\"ok\")"),
        i("explain_code", "ဒီ list slice step ကို ရှင်းပြပါ။",
          "ဒီ code က တစ်လှမ်းခြား တန်ဖိုး ယူပါတယ်။\n\n[::2] က ၀၊ ၂၊ ၄ နေရာတွေ ယူပါတယ်။ 1, 3, 5 ရပါတယ်။\n\nprint က [1, 3, 5] ပြပါတယ်။",
          ["array"], CH[2],
          "nums = [1, 2, 3, 4, 5]\nprint(nums[::2])"),
        i("explain_code", "ဒီ reversed loop ကို ရှင်းပြပါ။",
          "ဒီ loop က နောက်ကနေ ရှေ့ ပြန်လှည့်ပါတယ်။\n\nreversed က မူရင်း list ကို မပြင်ပါ။ 3၊ 2၊ 1 ထွက်ပါတယ်။\n\nသုံးကြောင်း ပြပါတယ်။",
          ["loop", "array"], CH[2],
          "for n in reversed([1, 2, 3]):\n    print(n)"),
        i("explain_code", "ဒီ any code ကို ရှင်းပြပါ။",
          "ဒီ code က တစ်ခုခု မှန်ရင် True ပေးပါတယ်။\n\nany က 5 က ၄ ထက်ကြီးလို့ True ဖြစ်ပါတယ်။ အကုန်ငယ်ရင် False ဖြစ်ပါမယ်။\n\nprint က True ပြပါတယ်။",
          ["boolean", "array"], CH[2],
          "nums = [1, 5, 2]\nprint(any(n > 4 for n in nums))"),
        i("explain_code", "ဒီ all code ကို ရှင်းပြပါ။",
          "ဒီ code က အကုန် မှန်မှ True ပေးပါတယ်။\n\nall က 1၊ 2၊ 3 အားလုံး ၀ ထက်ကြီးလို့ True ဖြစ်ပါတယ်။ တစ်ခု ၀ ဆို False ဖြစ်ပါမယ်။\n\nprint က True ပြပါတယ်။",
          ["boolean", "array"], CH[2],
          "nums = [1, 2, 3]\nprint(all(n > 0 for n in nums))"),
        i("explain_code", "ဒီ dict items ကို ရှင်းပြပါ။",
          "ဒီ code က key နဲ့ value တွဲပြီး ပြပါတယ်။\n\nitems() က တွဲတွေ ပေးပါတယ်။ name Aung နဲ့ age 20 ထွက်ပါတယ်။\n\nနှစ်ကြောင်း ပြပါတယ်။",
          ["object", "loop"], CH[2],
          "user = {\"name\": \"Aung\", \"age\": 20}\nfor key, value in user.items():\n    print(key, value)"),
        i("explain_code", "ဒီ nested list ကို ရှင်းပြပါ။",
          "ဒီ code က စာရင်းထဲက စာရင်းကနေ တန်ဖိုး ယူပါတယ်။\n\ngrid[1] က [3, 4] ဖြစ်ပါတယ်။ grid[1][0] က 3 ဖြစ်ပါတယ်။\n\nprint က 3 ပြပါတယ်။",
          ["array"], CH[2],
          "grid = [[1, 2], [3, 4]]\nprint(grid[1][0])"),
        i("explain_code", "ဒီ is vs == ကို ရှင်းပြပါ။",
          "ဒီ code က None ကို is နဲ့ စစ်ပါတယ်။\n\n== က တန်ဖိုးတူမတူ၊ is က object တူမတူ ကြည့်ပါတယ်။ None စစ်ရင် is သုံးသင့်ပါတယ်။\n\nprint က same ပြပါတယ်။",
          ["condition"], CH[2],
          "data = None\nif data is None:\n    print(\"same\")"),
        i("explain_code", "ဒီ global keyword ကို ရှင်းပြပါ။",
          "ဒီ function က အပြင်က count ကို ပြင်ပါတယ်။\n\nglobal မပါရင် အထဲက variable အသစ် ဖြစ်ပါတယ်။ global count ကြောင့် ၁ တိုးပြီး ၁ ဖြစ်ပါတယ်။\n\nprint က 1 ပြပါတယ်။",
          ["variable", "function"], CH[2],
          "count = 0\n\ndef bump():\n    global count\n    count = count + 1\n\nbump()\nprint(count)"),
        i("explain_code", "ဒီ lambda code ကို ရှင်းပြပါ။",
          "ဒီ code က တိုတောင်းတဲ့ function နဲ့ နှစ်ဆ တွက်ပါတယ်။\n\nlambda x: x * 2 က double နာမည်နဲ့ သိမ်းပါတယ်။ 5 ထည့်ရင် 10 ရပါတယ်။\n\nprint က 10 ပြပါတယ်။",
          ["function"], CH[2],
          "double = lambda x: x * 2\nprint(double(5))"),
        i("explain_code", "ဒီ map code ကို ရှင်းပြပါ။",
          "ဒီ code က list ထဲက ဂဏန်းတွေကို string ပြောင်းပါတယ်။\n\nmap က တစ်ခုချင်း str ခေါ်ပါတယ်။ list() က ပြန်စုပါတယ်။\n\nprint က ['1', '2', '3'] ပြပါတယ်။",
          ["function", "array"], CH[2],
          "nums = [1, 2, 3]\nprint(list(map(str, nums)))"),
        i("explain_code", "ဒီ filter code ကို ရှင်းပြပါ။",
          "ဒီ code က စုံဂဏန်းပဲ ကျန်အောင် စစ်ပါတယ်။\n\nfilter က x % 2 == 0 မှန်တာပဲ ထားပါတယ်။ 2 နဲ့ 4 ရပါတယ်။\n\nprint က [2, 4] ပြပါတယ်။",
          ["array", "function", "condition"], CH[2],
          "nums = [1, 2, 3, 4]\nprint(list(filter(lambda x: x % 2 == 0, nums)))"),
        i("concept_qa", "Python 2 နဲ့ Python 3 ဘာကွာလဲ?",
          "Python 3 က လက်ရှိ သုံးသင့်တဲ့ ဗားရှင်း ဖြစ်ပြီး print က function ဖြစ်ပါတယ်။\n\nPython 2 မှာ print က statement ဖြစ်ခဲ့ပါတယ်။ စာဝိုင်း encoding က Python 3 မှာ ပိုရှင်းပါတယ်။\n\nဥပမာ print(\"hi\") က Python 3 ပုံစံ ဖြစ်ပါတယ်။",
          ["programming", "syntax"], CH[1]),
        i("concept_qa", "dynamic typing ဆိုတာ ဘာလဲ?",
          "dynamic typing ဆိုတာ variable ရဲ့ အမျိုးအစားကို run တဲ့အချိန်မှ ဆုံးဖြတ်ခြင်း ဖြစ်ပါတယ်။\n\nPython မှာ x = 1 ပြီး x = \"hi\" လို့ ပြောင်းနိုင်ပါတယ်။ type ကို ကြိုမချည်ရပါ။\n\nမှားရောသုံးရင် runtime မှာမှ ပေါ်တတ်ပါတယ်။",
          ["variable"], CH[1]),
        i("concept_qa", "statement နဲ့ expression ဘာကွာလဲ?",
          "expression က တန်ဖိုး ထုတ်ပေးပြီး statement က အလုပ်တစ်ခု လုပ်ခိုင်းပါတယ်။\n\n3 + 4 က expression ဖြစ်ပါတယ်။ print(3) က statement ဖြစ်ပါတယ်။ if က statement ဖြစ်ပါတယ်။\n\nexpression ကို variable ထဲ သိမ်းလို့ရပါတယ်။",
          ["programming"], CH[1]),
        i("explain_code", "ဒီ type check code ကို ရှင်းပြပါ။",
          "ဒီ code က တန်ဖိုးက int ဟုတ်မဟုတ် စစ်ပါတယ်။\n\ntype(n) is int က True ဖြစ်လို့ yes ပြပါတယ်။ စာသားဆိုရင် no ဖြစ်ပါမယ်။\n\nprint က yes ပြပါတယ်။",
          ["integer", "condition"], CH[1],
          "n = 7\nif type(n) is int:\n    print(\"yes\")\nelse:\n    print(\"no\")"),
        i("explain_code", "ဒီ round code ကို ရှင်းပြပါ။",
          "ဒီ code က ဒဿမကို အနီးစပ် ဂဏန်း ပြောင်းပါတယ်။\n\nround(3.7) က 4 ဖြစ်ပါတယ်။ ဒဿမနေရာ အရေအတွက်လည်း ပေးနိုင်ပါတယ်။\n\nprint က 4 ပြပါတယ်။",
          ["integer", "function"], CH[1],
          "print(round(3.7))"),
        i("explain_code", "ဒီ abs code ကို ရှင်းပြပါ။",
          "ဒီ code က တန်ဖိုးရဲ့ ပကတိတန်ဖိုး ယူပါတယ်။\n\nabs(-5) က 5 ဖြစ်ပါတယ်။ အပေါင်းအနုတ် မကြည့်ဘဲ အရွယ်အစား လိုချင်ရင် သုံးပါတယ်။\n\nprint က 5 ပြပါတယ်။",
          ["function"], CH[1],
          "print(abs(-5))"),
        i("explain_code", "ဒီ pow code ကို ရှင်းပြပါ။",
          "ဒီ code က နှစ်ထပ်ကိန်း တွက်ပါတယ်။\n\npow(2, 3) က 8 ဖြစ်ပါတယ်။ ** နဲ့လည်း ရေးနိုင်ပါတယ်။\n\nprint က 8 ပြပါတယ်။",
          ["function", "operator"], CH[1],
          "print(pow(2, 3))"),
        i("debug_explain", "ဒီ keyword variable ပြင်ပါ။",
          "class က keyword ဖြစ်လို့ variable နာမည် မဖြစ်နိုင်ပါ။\n\nတခြား နာမည် ပေးရပါတယ်။\n\nမှန်ကန်သော code:\nclass_name = \"Dog\"\nprint(class_name)",
          ["syntax", "variable"], CH[1],
          "class = \"Dog\"\nprint(class)"),
        i("debug_explain", "ဒီ tuple ပြင်မှားတာ ပြင်ပါ။",
          "tuple က immutable ဖြစ်လို့ index ကနေ ပြင်လို့မရပါ။\n\nပြင်ချင်ရင် list ပြောင်းပါ။\n\nမှန်ကန်သော code:\npoint = [3, 4]\npoint[0] = 5\nprint(point)",
          ["array", "debug"], CH[2],
          "point = (3, 4)\npoint[0] = 5\nprint(point)"),
        i("concept_qa", "whitespace က Python မှာ ဘာအရေးကြီးလဲ?",
          "whitespace က block ခွဲတဲ့အတွက် အဓိပ္ပာယ် ပါပါတယ်။\n\nspace နဲ့ tab ရောသုံးရင် IndentationError တက်တတ်ပါတယ်။ တစ်ဖိုင်လုံး တူအောင် သုံးပါ။\n\nပုံမှန်အားဖြင့် space ၄ ခု သုံးပါတယ်။",
          ["syntax"], CH[1]),
        i("concept_qa", "standard library ဆိုတာ ဘာလဲ?",
          "standard library ဆိုတာ Python နဲ့ အတူပါလာတဲ့ module တွေ ဖြစ်ပါတယ်။\n\nmath၊ json၊ datetime လို ကိရိယာတွေ pip မထည့်ဘဲ import လို့ရပါတယ်။ ပြန်မရေးရအောင် သုံးပါ။\n\nဥပမာ import datetime နဲ့ နေ့စွဲ ယူနိုင်ပါတယ်။",
          ["function"], CH[3]),
        i("explain_code", "ဒီ datetime code ကို ရှင်းပြပါ။",
          "ဒီ code က ဒီနေ့ ရက်ကို ယူပါတယ်။\n\ndatetime.date.today() က စနစ်ရက်ကို ပေးပါတယ်။ print က ရက်စွဲ ပြပါတယ်။\n\nrun တဲ့နေ့အလိုက် တန်ဖိုး ပြောင်းပါတယ်။",
          ["function"], CH[3],
          "import datetime\nprint(datetime.date.today())"),
        i("explain_code", "ဒီ json dumps ကို ရှင်းပြပါ။",
          "ဒီ code က dictionary ကို JSON စာ ပြောင်းပါတယ်။\n\ndumps က ပို့လို့ရတဲ့ စာကြောင်း လုပ်ပါတယ်။ name နဲ့ Aung ပါပါတယ်။\n\nprint က JSON စာကြောင်း ပြပါတယ်။",
          ["object", "string"], CH[3],
          "import json\nprint(json.dumps({\"name\": \"Aung\"}))"),
        i("concept_qa", "JSON ဆိုတာ ဘာလဲ?",
          "JSON ဆိုတာ data ဖလှယ်တဲ့ စာသားပုံစံ ဖြစ်ပါတယ်။\n\nkey နဲ့ value တွဲတွေ သုံးပါတယ်။ Python dictionary နဲ့ တူပါတယ်။ ဖိုင် သို့မဟုတ် ကွန်ရက်ကနေ ဖတ်တတ်ပါတယ်။\n\nဥပမာ object ပုံစံနဲ့ ရေးပါတယ်။",
          ["object"], CH[3]),
        i("explain_code", "ဒီ end print ကို ရှင်းပြပါ။",
          "ဒီ code က နှစ်ခုကို တစ်ကြောင်းတည်း ပြပါတယ်။\n\nend ကို space ပေးထားလို့ နောက်ကြောင်းမပြောင်းပါ။ Hi နဲ့ there က ကပ်ပါတယ်။\n\nHi there ထွက်ပါတယ်။",
          ["function", "string"], CH[2],
          "print(\"Hi\", end=\" \")\nprint(\"there\")"),
        i("explain_code", "ဒီ sep print ကို ရှင်းပြပါ။",
          "ဒီ code က တန်ဖိုးတွေကြားမှာ မျဉ်းတို ထည့်ပါတယ်။\n\nsep က 1-2-3 ဖြစ်ပါတယ်။ ပုံမှန်က space ဖြစ်ပါတယ်။\n\nprint က 1-2-3 ပြပါတယ်။",
          ["function"], CH[2],
          "print(1, 2, 3, sep=\"-\")"),
        i("debug_explain", "ဒီ zero division ကို ပြင်ပါ။",
          "b က ၀ ဖြစ်လို့ ခွဲလို့မရပါ။ ZeroDivisionError တက်ပါတယ်။\n\nမခွဲခင် ၀ ဟုတ်မဟုတ် စစ်ပါ။\n\nမှန်ကန်သော code:\na = 10\nb = 0\nif b == 0:\n    print(\"Cannot divide\")\nelse:\n    print(a / b)",
          ["runtime", "debug"], CH[2],
          "a = 10\nb = 0\nprint(a / b)"),
        i("concept_qa", "off-by-one error ဆိုတာ ဘာလဲ?",
          "off-by-one ဆိုတာ တစ်ခု ပိုရေတွက်ခြင်း သို့မဟုတ် နည်းရေတွက်ခြင်း ဖြစ်ပါတယ်။\n\nrange(5) က ၅ ထိမရောက်တာ မေ့ရင် ဖြစ်တတ်ပါတယ်။ list အရှည်နဲ့ နောက်ဆုံး index က n-1 ဖြစ်ပါတယ်။\n\nဥပမာ ၁ မှ ၅ ထိ လိုရင် range(1, 6) သုံးရပါတယ်။",
          ["loop", "debug"], CH[2]),
        i("concept_qa", "Python မှာ main guard က ဘာကြောင့် သုံးသလဲ?",
          "if __name__ == \"__main__\" က ဖိုင်ကို တိုက်ရိုက် run မှသာ အလုပ်လုပ်စေပါတယ်။\n\nတခြားဖိုင်က import လုပ်ရင် အဲဒီ block မဝင်ပါ။ script နဲ့ module ခွဲချင်ရင် သုံးပါတယ်။\n\nဥပမာ test ခေါ်တဲ့အခါ print အပို မထွက်အောင် ကာကွယ်ပါတယ်။",
          ["programming"], CH[3]),
        i("explain_code", "ဒီ main guard code ကို ရှင်းပြပါ။",
          "ဒီ code က ဖိုင်ကို တိုက်ရိုက် run မှ hi ပြပါတယ်။\n\n__name__ က __main__ ဖြစ်ရင် ဝင်ပါတယ်။ import လုပ်ရင် မဝင်ပါ။\n\npython file.py လုပ်ရင် hi ထွက်ပါတယ်။",
          ["programming"], CH[3],
          "def hello():\n    print(\"hi\")\n\nif __name__ == \"__main__\":\n    hello()"),
    ]
