from .common import item as i

CH = "Professional Web Developer"


def samples():
    return [
        i("concept_qa", "HTML CSS JavaScript ဘာကွာလဲ?",
          "HTML က ဖွဲ့စည်းပုံ၊ CSS က အလှ၊ JavaScript က အပြုအမူ ဖြစ်ပါတယ်။\n\nသုံးခုပေါင်းမှ ဝက်ဘ်စာမျက်နှာ ပြည့်စုံပါတယ်။ တစ်ခုချင်း တာဝန် ခွဲပါတယ်။\n\nခလုတ်ရှိတာ HTML၊ အရောင်က CSS၊ နှိပ်တုံ့ပြန်တာ JavaScript ဖြစ်ပါတယ်။",
          ["programming"], CH),
        i("concept_qa", "Frontend နဲ့ backend ဘာကွာလဲ?",
          "Frontend က သုံးသူမြင်တဲ့ ဘရောက်ဇာဘက်၊ backend က server နဲ့ database ဘက် ဖြစ်ပါတယ်။\n\nReact က frontend၊ Laravel က backend ဖြစ်နိုင်ပါတယ်။ API က နှစ်ခုကို ဆက်ပါတယ်။\n\nအလုပ်ခွဲမှ စီမံရ လွယ်ပါတယ်။",
          ["API"], CH),
        i("concept_qa", "HTTP request ဆိုတာ ဘာလဲ?",
          "HTTP request က ဘရောက်ဇာက server ဆီ ပို့တဲ့ တောင်းဆိုမှု ဖြစ်ပါတယ်။\n\nလိပ်စာ၊ method၊ header ပါပါတယ်။ server က response ပြန်ပါတယ်။\n\nစာမျက်နှာဖွင့်တာက GET request ဖြစ်ပါတယ်။",
          ["HTTP"], CH),
        i("concept_qa", "Git ဆိုတာ ဘာလဲ?",
          "Git က code အပြောင်းအလဲကို မှတ်တဲ့ version control ဖြစ်ပါတယ်။\n\nပြန်ဆုတ်နိုင်ပါတယ်။ အဖွဲ့လိုက် မတိုက်အောင် ကူပါတယ်။\n\ncommit တစ်ခုချင်းက မှတ်တိုင် ဖြစ်ပါတယ်။",
          ["programming"], CH),
        i("concept_qa", "Environment variable ဘာကြောင့် သုံးသလဲ?",
          "စကားဝှက်နဲ့ ဆက်တင်ကို code ထဲ မရေးအောင် ခွဲထုတ်ပါတယ်။\n\nစက်အလိုက် တန်ဖိုး မတူနိုင်ပါတယ်။ လုံခြုံရေး ပိုကောင်းပါတယ်။\n\n.env ဖိုင်က ဥပမာ ဖြစ်ပါတယ်။",
          ["programming"], CH),
        i("concept_qa", "MVC ဆိုတာ ဘာလဲ?",
          "MVC က Model၊ View၊ Controller ခွဲတဲ့ ပုံစံ ဖြစ်ပါတယ်။\n\nView က မျက်နှာပြင်၊ Model က data၊ Controller က စည်းကမ်း ဖြစ်ပါတယ်။ ရှုပ်ထွေးမှု လျော့ပါတယ်။\n\nLaravel က ဒီပုံစံကို လိုက်ပါတယ်။",
          ["programming"], CH),
        i("explain_code", "ဒီ HTML form ကို ရှင်းပြပါ။",
          "ဒီ form က နာမည်ကို server ဆီ POST ပို့ပါတယ်။\n\naction က URL၊ method က ပို့ပုံ ဖြစ်ပါတယ်။ input name က သော့ ဖြစ်ပါတယ်။\n\nSave နှိပ်ရင် /save ကို သွားပါတယ်။",
          ["form", "POST"], CH,
          "<form action=\"/save\" method=\"post\">\n  <input name=\"name\">\n  <button>Save</button>\n</form>"),
        i("explain_code", "ဒီ CSS class ကို ရှင်းပြပါ။",
          "ဒီ CSS က .title ကို အလယ်တင်ပါတယ်။\n\nclass=title ရှိတဲ့ ဒြပ်စင်ကို သက်ရောက်ပါတယ်။ text-align က အလယ် ဖြစ်ပါတယ်။\n\nခေါင်းစဉ် အလယ်ရောက်ပါတယ်။",
          ["css"], CH,
          ".title { text-align: center; }"),
        i("explain_code", "ဒီ semantic HTML ကို ရှင်းပြပါ။",
          "ဒီ markup က ဆောင်းပါး အဓိပ္ပာယ် ပေးပါတယ်။\n\narticle နဲ့ h1 က ဖွဲ့စည်းပုံ ရှင်းပါတယ်။ ရှာဖွေရေးနဲ့ ဖတ်စက် အတွက် ကောင်းပါတယ်။\n\ndiv ထက် အဓိပ္ပာယ် ပိုရှိပါတယ်။",
          ["programming"], CH,
          "<article>\n  <h1>News</h1>\n  <p>Today</p>\n</article>"),
        i("explain_code", "ဒီ git commit ကို ရှင်းပြပါ။",
          "ဒီ command နှစ်ခုက ပြောင်းလဲမှုကို မှတ်ပါတယ်။\n\nadd က စင်ပေါ်တင်ပါတယ်။ commit က မှတ်တိုင် ရိုက်ပါတယ်။\n\nစာတိုက ဘာလုပ်တယ်ဆိုတာ ပြောပါတယ်။",
          ["programming"], CH,
          "git add .\ngit commit -m \"Add login form\""),
        i("explain_code", "ဒီ npm install ကို ရှင်းပြပါ။",
          "ဒီ command က package တွေကို သွင်းပါတယ်။\n\npackage.json ကို ဖတ်ပါတယ်။ node_modules ထဲ ဆင်းပါတယ်။\n\nပရောဂျက် စ run နိုင်ပါတယ်။",
          ["programming"], CH,
          "npm install"),
        i("debug_explain", "ဒီ broken HTML ကို ပြင်ပါ။",
          "h1 ကို ပိတ်မထားလို့ ဖွဲ့စည်းပုံ မှားပါတယ်။\n\ntag နှစ်ဖက် ပိတ်ရပါတယ်။\n\nမှန်ကန်သော code:\n<h1>Home</h1>",
          ["syntax"], CH,
          "<h1>Home"),
        i("debug_explain", "ဒီ CSS selector မှားတာကို ပြင်ပါ။",
          "HTML မှာ class=title ဖြစ်ပေမယ့် CSS က #title သုံးထားပါတယ်။\n\n# က id၊ . က class ဖြစ်ပါတယ်။\n\nမှန်ကန်သော code:\n.title { color: red; }",
          ["css"], CH,
          "#title { color: red; }"),
        i("concept_qa", "Accessibility ဆိုတာ ဘာလဲ?",
          "Accessibility က လူတိုင်း သုံးနိုင်အောင် ဝက်ဘ်ကို ပြုလုပ်ခြင်း ဖြစ်ပါတယ်။\n\nalt စာ၊ label၊ ကီးဘုတ်နဲ့ သုံးနိုင်မှု ပါဝင်ပါတယ်။ ဥပဒေနဲ့ ကျင့်ဝတ် နှစ်ခုလုံး ရှိပါတယ်။\n\nပုံမှာ alt မထည့်ရင် ဖတ်စက် မသိပါ။",
          ["programming"], CH),
        i("explain_code", "ဒီ alt text ကို ရှင်းပြပါ။",
          "ဒီ img က ပုံမပေါ်ရင် သို့မဟုတ် ဖတ်စက်အတွက် ရှင်းပြချက် ပေးပါတယ်။\n\nalt က ခွေးပုံဆိုတာ ပြောပါတယ်။ ဗလာမထားသင့်ပါ။\n\nအဓိပ္ပာယ် ပြည့်ပါတယ်။",
          ["programming"], CH,
          "<img src=\"dog.jpg\" alt=\"A brown dog\">"),
        i("concept_qa", "HTTPS ဘာကြောင့် လိုသလဲ?",
          "HTTPS က ဒေတာကို လမ်းမှာ ဖုံးအုပ်ပါတယ်။\n\nစကားဝှက် ခိုးယူရ ခက်ပါတယ်။ ဘရောက်ဇာက လုံခြုံတယ်လို့ ပြပါတယ်။\n\nlogin ရှိတဲ့ ဆိုက်မှာ မဖြစ်မနေ သုံးသင့်ပါတယ်။",
          ["HTTP"], CH),
        i("concept_qa", "Caching ဝက်ဘ်မှာ ဘာလုပ်သလဲ?",
          "Cache က ဖိုင်ကို ပြန်သုံးစေပါတယ်။\n\nCSS/JS ကို ထပ်မဆွဲရပါ။ မြန်ပါတယ်။ ဗားရှင်းပြောင်းရင် cache ချိုးရနိုင်ပါတယ်။\n\nပထမအကြိမ်ထက် နောက်အကြိမ် ပိုမြန်ပါတယ်။",
          ["HTTP"], CH),
        i("explain_code", "ဒီ meta viewport ကို ရှင်းပြပါ။",
          "ဒီ tag က ဖုန်းမှာ စာမျက်နှာ အကျယ်ကို မှန်အောင် ချိန်ပါတယ်။\n\nမထည့်ရင် စာသေးပြီး ဇွန်းချဲ့ရပါတယ်။ responsive ရဲ့ အခြေခံ ဖြစ်ပါတယ်။\n\nမိုဘိုင်းမှာ ဖတ်ရ လွယ်ပါတယ်။",
          ["responsive"], CH,
          "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"),
        i("concept_qa", "SEO ဆိုတာ ဘာလဲ?",
          "SEO က ရှာဖွေရေးမှာ တွေ့လွယ်အောင် ပြုလုပ်ခြင်း ဖြစ်ပါတယ်။\n\nခေါင်းစဉ်၊ ဖော်ပြချက်၊ အဓိပ္ပာယ်ရှိ HTML က ကူပါတယ်။ အကြောင်းအရာ ကောင်းရင် ပိုအရေးကြီးပါတယ်။\n\nသုံးသူ ရှာတွေ့မှ ဆိုက် ရောက်ပါတယ်။",
          ["programming"], CH),
        i("explain_code", "ဒီ title tag ကို ရှင်းပြပါ။",
          "ဒီ title က တက်ဘ်နဲ့ ရှာဖွေရေးမှာ ပေါ်တဲ့ နာမည် ဖြစ်ပါတယ်။\n\nစာမျက်နှာတိုင်း ရှင်းသင့်ပါတယ်။ Home - Shop လို ရေးနိုင်ပါတယ်။\n\nသုံးသူ မှတ်မိ လွယ်ပါတယ်။",
          ["programming"], CH,
          "<title>Home - Shop</title>"),
        i("debug_explain", "ဒီ missing viewport ကို ဘာကြောင့် ဖြည့်သလဲ?",
          "viewport မပါရင် ဖုန်းမှာ desktop ပုံစံ သေးသေး ပေါ်ပါတယ်။\n\nmeta viewport ထည့်ပါ။\n\nမှန်ကန်သော code:\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
          ["responsive"], CH,
          "<head>\n  <title>Shop</title>\n</head>"),
        i("concept_qa", "Deploy ဆိုတာ ဘာလဲ?",
          "Deploy က ရေးထားတဲ့ အက်ပ်ကို အင်တာနက်ပေါ် တင်ခြင်း ဖြစ်ပါတယ်။\n\nserver၊ domain၊ HTTPS ပြင်ရပါတယ်။ local မှာ အလုပ်လုပ်တာနဲ့ မတူနိုင်ပါ။\n\nသုံးသူတွေ ဝင်ကြည့်နိုင်ပါတယ်။",
          ["programming"], CH),
        i("concept_qa", "404 page ဘာကြောင့် ပြင်ဆင်သင့်လဲ?",
          "မရှိတဲ့ လိပ်စာ ဖွင့်ရင် သုံးသူ မလမ်းမပျောက်အောင် ရှင်းပြသင့်ပါတယ်။\n\nပင်မကို ပြန်လင့် ပေးပါ။ ဗလာအမှား မထားသင့်ပါ။\n\nအတွေ့အကြုံ ပိုကောင်းပါတယ်။",
          ["HTTP"], CH),
        i("explain_code", "ဒီ 404 link ကို ရှင်းပြပါ။",
          "ဒီစာက မတွေ့ကြောင်းနဲ့ ပင်မပြန်လင့် ပေးပါတယ်။\n\nHome နှိပ်ရင် / ကို သွားပါတယ်။ သုံးသူ လမ်းမပျောက်ပါ။\n\nရိုးရှင်းတဲ့ 404 ဖြစ်ပါတယ်။",
          ["HTTP"], CH,
          "<h1>Page not found</h1>\n<a href=\"/\">Home</a>"),
        i("concept_qa", "Code review ဘာကြောင့် လုပ်သလဲ?",
          "အခြားသူ ဖတ်ပေးရင် အမှားနဲ့ ရှင်းလင်းမှု ပိုမြင်ပါတယ်။\n\nအဖွဲ့စံ ညီပါတယ်။ တစ်ယောက်တည်း မမြင်တာ တွေ့တတ်ပါတယ်။\n\nအရည်အသွေး မြင့်စေပါတယ်။",
          ["programming"], CH),
        i("explain_code", "ဒီ package.json scripts ကို ရှင်းပြပါ။",
          "ဒီ script က npm start နဲ့ dev server ဖွင့်ပါတယ်။\n\nနာမည်တိုနဲ့ ရှည်တဲ့ command ကို မှတ်ပါတယ်။ အဖွဲ့သားအားလုံး တူညီစွာ ခေါ်နိုင်ပါတယ်။\n\nstart တစ်ခုတည်း မှတ်ရပါတယ်။",
          ["programming"], CH,
          "\"scripts\": { \"start\": \"node server.js\" }"),
    ]
