from .common import item as i

CH = "React အခြေခံ"


def samples():
    return [
        i("concept_qa", "React ဆိုတာ ဘာလဲ?",
          "React ဆိုတာ user interface တည်ဆောက်တဲ့ JavaScript library ဖြစ်ပါတယ်။\n\nComponent ခွဲပြီး ပြန်သုံးပါတယ်။ Data ပြောင်းရင် မျက်နှာပြင်ကို ထိရောက်စွာ ပြန်ဆွဲပါတယ်။\n\nဥပမာ ခလုတ်နဲ့ စာရင်းကို component ခွဲရေးနိုင်ပါတယ်။",
          ["react", "component"], CH),
        i("concept_qa", "Component ဆိုတာ ဘာလဲ?",
          "Component ဆိုတာ UI အပိုင်းငယ်တစ်ခု ဖြစ်ပါတယ်။\n\nfunction အနေနဲ့ ရေးပြီး JSX ပြန်ပေးပါတယ်။ ကြီးတဲ့ စာမျက်နှာကို ပေါင်းစည်းပါတယ်။\n\nဥပမာ Header, Footer ခွဲနိုင်ပါတယ်။",
          ["component"], CH),
        i("concept_qa", "JSX ဆိုတာ ဘာလဲ?",
          "JSX ဆိုတာ JavaScript ထဲမှာ HTML ပုံစံ ရေးခြင်း ဖြစ်ပါတယ်။\n\nBrowser က တိုက်ရိုက် မဖတ်ပါ။ compile ပြီး JavaScript ဖြစ်ပါတယ်။ class အစား className သုံးပါတယ်။\n\nဖတ်ရ လွယ်ပြီး UI ကို ရှင်းစေပါတယ်။",
          ["react"], CH),
        i("concept_qa", "Props ဆိုတာ ဘာလဲ?",
          "Props ဆိုတာ မိဘ component က ကလေးဆီ ပို့တဲ့ data ဖြစ်ပါတယ်။\n\nဖတ်ရုံသာ ဖြစ်ပြီး ကလေးက တိုက်ရိုက် မပြင်သင့်ပါ။ ပြန်သုံးတဲ့ component ကို ကွဲပြားစေပါတယ်။\n\nဥပမာ <User name=\"Aung\" /> ဖြစ်ပါတယ်။",
          ["props", "component"], CH),
        i("concept_qa", "State ဆိုတာ ဘာလဲ?",
          "State ဆိုတာ component ထဲမှာ ပြောင်းလဲနိုင်တဲ့ data ဖြစ်ပါတယ်။\n\nပြောင်းရင် UI ထပ်ဆွဲပါတယ်။ useState နဲ့ သုံးပါတယ်။\n\nဥပမာ နှိပ်ရေကို မှတ်နိုင်ပါတယ်။",
          ["state", "hook"], CH),
        i("concept_qa", "useEffect ဆိုတာ ဘာလဲ?",
          "useEffect ဆိုတာ render ပြီး အပိုအလုပ်လုပ်ခြင်း ဖြစ်ပါတယ်။\n\nData ခေါ်ခြင်း၊ timer၊ subscription အတွက် သုံးပါတယ်။ dependency array နဲ့ ဘယ်တော့ run မလဲ ထိန်းပါတယ်။\n\n[] ထည့်ရင် တစ်ကြိမ်ပဲ run ပါတယ်။",
          ["hook"], CH),
        i("concept_qa", "Key prop ဘာကြောင့် လိုသလဲ?",
          "Key က list ထဲက item တစ်ခုချင်းကို ခွဲခြားပေးပါတယ်။\n\nReact က ဘယ်ဟာ ပြောင်းတယ်ဆိုတာ မြန်မြန် သိပါတယ်။ index ကို key လုပ်ရင် ပြင်ရင် မှားနိုင်ပါတယ်။\n\nid လို တည်ငြိမ်တဲ့ တန်ဖိုး သုံးသင့်ပါတယ်။",
          ["react"], CH),
        i("concept_qa", "Controlled input ဆိုတာ ဘာလဲ?",
          "Controlled input က တန်ဖိုးကို state က ပိုင်ခြင်း ဖြစ်ပါတယ်။\n\nvalue နဲ့ onChange တွဲသုံးပါတယ်။ ဖောင်စစ်ရ လွယ်ပါတယ်။\n\nရိုက်တိုင်း state အသစ် ဖြစ်ပါတယ်။",
          ["state", "form"], CH),
        i("explain_code", "ဒီ function component ကို ရှင်းပြပါ။",
          "ဒီ component က Hello Aung ပြပါတယ်။\n\nWelcome က function component ဖြစ်ပါတယ်။ props.name ကို JSX ထဲ ထည့်ပါတယ်။\n\nစာမျက်နှာပေါ်မှာ Hello Aung ပေါ်ပါတယ်။",
          ["component", "props"], CH,
          "function Welcome(props) {\n  return <h1>Hello {props.name}</h1>;\n}"),
        i("explain_code", "ဒီ useState ကို ရှင်းပြပါ။",
          "ဒီ code က ခလုတ်နှိပ်ရင် ၁ တိုးပါတယ်။\n\ncount က လက်ရှိတန်ဖိုး၊ setCount က ပြောင်းတဲ့ function ဖြစ်ပါတယ်။ နှိပ်ရင် UI အသစ် ဖြစ်ပါတယ်။\n\nစ ၀ ကနေ တက်ပါတယ်။",
          ["state", "hook"], CH,
          "function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => setCount(count + 1)}>{count}</button>\n  );\n}"),
        i("explain_code", "ဒီ list render ကို ရှင်းပြပါ။",
          "ဒီ code က နာမည်တိုင်းအတွက် <li> ဆွဲပါတယ်။\n\nmap က element စာရင်း ပြန်ပေးပါတယ်။ key က id ဖြစ်ပါတယ်။\n\nAung နဲ့ Mya စာရင်းပေါ်ပါတယ်။",
          ["array", "component"], CH,
          "function Names() {\n  const users = [\n    { id: 1, name: \"Aung\" },\n    { id: 2, name: \"Mya\" }\n  ];\n  return (\n    <ul>\n      {users.map((u) => (\n        <li key={u.id}>{u.name}</li>\n      ))}\n    </ul>\n  );\n}"),
        i("explain_code", "ဒီ useEffect fetch ကို ရှင်းပြပါ။",
          "ဒီ code က စစချင်း user ကို API က ယူပါတယ်။\n\n[] ကြောင့် တစ်ကြိမ်ပဲ ခေါ်ပါတယ်။ data ရရင် setUser လုပ်ပါတယ်။\n\nနာမည်ပေါ်လာပါတယ်။",
          ["hook", "API"], CH,
          "useEffect(() => {\n  fetch(\"/api/user\")\n    .then((res) => res.json())\n    .then((data) => setUser(data));\n}, []);"),
        i("explain_code", "ဒီ controlled input ကို ရှင်းပြပါ။",
          "ဒီ input က state နဲ့ ချိတ်ထားပါတယ်။\n\nရိုက်တိုင်း setName ခေါ်ပါတယ်။ value={name} က မျက်နှာပြင်နဲ့ data တူစေပါတယ်။\n\nဖောင်မှာ နာမည်ကို ထိန်းနိုင်ပါတယ်။",
          ["state", "form"], CH,
          "function NameForm() {\n  const [name, setName] = useState(\"\");\n  return (\n    <input value={name} onChange={(e) => setName(e.target.value)} />\n  );\n}"),
        i("explain_code", "ဒီ conditional render ကို ရှင်းပြပါ။",
          "ဒီ code က loading ဖြစ်ရင် စောင့်ကြောင်း ပြပါတယ်။\n\ntrue ဖြစ်ရင် Loading... ပြပါတယ်။ ပြီးရင် Ready ဖြစ်ပါတယ်။\n\n&& က မှန်မှ ပြတဲ့ ပုံစံ ဖြစ်ပါတယ်။",
          ["condition", "react"], CH,
          "function Status({ loading }) {\n  return <div>{loading ? \"Loading...\" : \"Ready\"}</div>;\n}"),
        i("explain_code", "ဒီ children props ကို ရှင်းပြပါ။",
          "ဒီ Card က အထဲက အကြောင်းအရာကို ခြုံပေးပါတယ်။\n\nchildren က tag နှစ်ခုကြားက ဟယ် ဖြစ်ပါတယ်။ ပြန်သုံးရ လွယ်ပါတယ်။\n\nHello က ကတ်ထဲ ပေါ်ပါတယ်။",
          ["props", "component"], CH,
          "function Card({ children }) {\n  return <div className=\"card\">{children}</div>;\n}"),
        i("explain_code", "ဒီ lifting state ဥပမာကို ရှင်းပြပါ။",
          "ဒီမိဘက query ကို ပိုင်ပြီး ကလေးနှစ်ခုကို ဝေပါတယ်။\n\nSearchBox က ပြောင်း၊ ResultList က ဖတ်ပါတယ်။ ဒေတာတစ်ခုတည်း ဖြစ်ပါတယ်။\n\nညီအစ်မ နှစ်ခု ဆက်သွယ်ပါတယ်။",
          ["state", "props"], CH,
          "function Page() {\n  const [query, setQuery] = useState(\"\");\n  return (\n    <>\n      <SearchBox query={query} setQuery={setQuery} />\n      <ResultList query={query} />\n    </>\n  );\n}"),
        i("debug_explain", "ဒီ hook မှားခေါ်တာကို ပြင်ပါ။",
          "useState ကို if ထဲမှာ ခေါ်လို့ စည်းကမ်း ဖောက်ပါတယ်။\n\nHook ကို component ထိပ်မှာ အမြဲ ခေါ်ရပါတယ်။\n\nမှန်ကန်သော code:\nfunction Box({ show }) {\n  const [n, setN] = useState(0);\n  if (!show) {\n    return null;\n  }\n  return <span>{n}</span>;\n}",
          ["hook", "state"], CH,
          "function Box({ show }) {\n  if (!show) {\n    return null;\n  }\n  const [n, setN] = useState(0);\n  return <span>{n}</span>;\n}"),
        i("debug_explain", "ဒီ list key ပျောက်တာကို ပြင်ပါ။",
          "map ထဲမှာ key မပေးလို့ React သတိပေးပါတယ်။\n\nတည်ငြိမ်တဲ့ id ကို key ထားပါ။\n\nမှန်ကန်သော code:\n{items.map((item) => (\n  <li key={item.id}>{item.name}</li>\n))}",
          ["react"], CH,
          "{items.map((item) => (\n  <li>{item.name}</li>\n))}"),
        i("debug_explain", "ဒီ props ပြင်တာကို ရှင်းပါ။",
          "props ကို တိုက်ရိုက် ပြင်လို့မရပါ။\n\nမိဘက တန်ဖိုးအသစ် ပို့ရပါတယ်။\n\nမှန်ကန်သော code:\nfunction Hello({ name }) {\n  return <p>{name}</p>;\n}",
          ["props"], CH,
          "function Hello(props) {\n  props.name = \"Aung\";\n  return <p>{props.name}</p>;\n}"),
        i("concept_qa", "Virtual DOM ဆိုတာ ဘာလဲ?",
          "Virtual DOM က UI ပုံစံကို မှတ်ထားတဲ့ JavaScript ပုံစံ ဖြစ်ပါတယ်။\n\nပြောင်းတာကို နှိုင်းပြီး လိုအပ်သလောက်သာ တကယ့် DOM ကို ပြင်ပါတယ်။ ပိုမြန်စေပါတယ်။\n\nReact ရဲ့ အဓိက အကြံ ဖြစ်ပါတယ်။",
          ["DOM", "react"], CH),
        i("concept_qa", "Fragment ဆိုတာ ဘာလဲ?",
          "Fragment က မလိုအပ်တဲ့ div မထည့်ဘဲ ဒြပ်စင်များ ခြုံခြင်း ဖြစ်ပါတယ်။\n\n<> </> သုံးပါတယ်။ HTML ဖွဲ့စည်းပုံ မပိုပါ။\n\nlist item ပြန်ပေးရာမှာ အသုံးဝင်ပါတယ်။",
          ["react"], CH),
        i("explain_code", "ဒီ useMemo ကို ရှင်းပြပါ။",
          "ဒီ code က တွက်ချက်မှုကို မလိုအပ်ဘဲ ထပ်မလုပ်အောင် မှတ်ပါတယ်။\n\nitems မပြောင်းရင် အရင်ရလဒ် ပြန်သုံးပါတယ်။ ကြီးတဲ့ list မှာ အထောက်အကူ ဖြစ်ပါတယ်။\n\nperformance အတွက် သုံးပါတယ်။",
          ["hook"], CH,
          "const total = useMemo(() => {\n  return items.reduce((sum, n) => sum + n, 0);\n}, [items]);"),
        i("explain_code", "ဒီ useRef ကို ရှင်းပြပါ။",
          "ဒီ code က input ကို အာရုံစိုက်ပါတယ်။\n\nref က DOM ကို တိုက်ရိုက် ညွှန်ပါတယ်။ click မှာ focus ခေါ်ပါတယ်။\n\nrender ထပ်မဖြစ်ဘဲ မှတ်နိုင်ပါတယ်။",
          ["hook", "DOM"], CH,
          "const inputRef = useRef(null);\nfunction focus() {\n  inputRef.current.focus();\n}"),
        i("explain_code", "ဒီ form submit ကို ရှင်းပြပါ။",
          "ဒီ form က refresh မဖြစ်အောင် တားပြီး နာမည် သိမ်းပါတယ်။\n\npreventDefault က ပုံမှန် submit ကို ရပ်ပါတယ်။ onSubmit က React event ဖြစ်ပါတယ်။\n\nနာမည်ကို JS နဲ့ ကိုင်ပါတယ်။",
          ["form", "react"], CH,
          "function Form() {\n  const [name, setName] = useState(\"\");\n  function onSubmit(e) {\n    e.preventDefault();\n    console.log(name);\n  }\n  return (\n    <form onSubmit={onSubmit}>\n      <input value={name} onChange={(e) => setName(e.target.value)} />\n    </form>\n  );\n}"),
        i("concept_qa", "Context ဆိုတာ ဘာလဲ?",
          "Context က props ကို အဆင့်များစွာ မပို့ဘဲ ဝေမျှခြင်း ဖြစ်ပါတယ်။\n\ntheme၊ user လို global နီးပါး data အတွက် သုံးပါတယ်။ မလိုအပ်ဘဲ သုံးရင် ပြင်ရ ခက်နိုင်ပါတယ်။\n\nProvider က တန်ဖိုး ပေးပါတယ်။",
          ["react"], CH),
        i("explain_code", "ဒီ createContext ကို ရှင်းပြပါ။",
          "ဒီ code က theme ကို ကလေးတွေဆီ ဝေပါတယ်။\n\nProvider value က dark ဖြစ်ပါတယ်။ useContext နဲ့ ယူနိုင်ပါတယ်။\n\nကြားက component တွေ props မခံရပါ။",
          ["react"], CH,
          "const ThemeContext = createContext(\"light\");\nfunction App() {\n  return (\n    <ThemeContext.Provider value=\"dark\">\n      <Page />\n    </ThemeContext.Provider>\n  );\n}"),
        i("concept_qa", "SPA ဆိုတာ ဘာလဲ?",
          "SPA က စာမျက်နှာအပြည့် ပြန်မရွှေ့ဘဲ UI ပြောင်းတဲ့ app ဖြစ်ပါတယ်။\n\nReact Router နဲ့ page ခွဲပါတယ်။ ပိုလျင်မြန်သလို ထင်ရပါတယ်။\n\nSEO အတွက် သတိထားရနိုင်ပါတယ်။",
          ["react", "route"], CH),
        i("explain_code", "ဒီ NavLink ပုံစံကို ရှင်းပြပါ။",
          "ဒီ code က /about ကို သွားတဲ့ လင့် ဖြစ်ပါတယ်။\n\nစာမျက်နှာအပြည့် reload မလုပ်ပါ။ React Router က component ပြောင်းပါတယ်။\n\nAbout စာမျက်နှာ ပေါ်ပါတယ်။",
          ["route"], CH,
          "function Menu() {\n  return <Link to=\"/about\">About</Link>;\n}"),
        i("debug_explain", "ဒီ stale state ကို ဘယ်လို ပြင်မလဲ?",
          "count + 1 ကို ဆက်တိုက်ခေါ်ရင် အဟောင်းပေါ် မူတည်နိုင်ပါတယ်။\n\nfunction update သုံးရင် နောက်ဆုံးတန်ဖိုး ရပါတယ်။\n\nမှန်ကန်သော code:\nsetCount((c) => c + 1);",
          ["state"], CH,
          "setCount(count + 1);\nsetCount(count + 1);"),
        i("concept_qa", "Pure component ဆိုတာ ဘာကို ဆိုလိုသလဲ?",
          "တူညီတဲ့ props ရရင် တူညီတဲ့ UI ထွက်သင့်ပါတယ်။\n\nအပြင်က ကျပန်း တန်ဖိုး မထည့်သင့်ပါ။ စမ်းသပ်ရ လွယ်ပါတယ်။\n\nReact က ဒီအတွေးကို အားပေးပါတယ်။",
          ["component"], CH),
        i("explain_code", "ဒီ default props ပုံစံကို ရှင်းပြပါ။",
          "ဒီ component က နာမည်မပို့ရင် Guest ပြပါတယ်။\n\n= \"Guest\" က default ဖြစ်ပါတယ်။ ပို့ရင် အဲဒီတန်ဖိုး သုံးပါတယ်။\n\nHello Guest ထွက်နိုင်ပါတယ်။",
          ["props"], CH,
          "function Hello({ name = \"Guest\" }) {\n  return <p>Hello {name}</p>;\n}"),
        i("explain_code", "ဒီ fragment list ကို ရှင်းပြပါ။",
          "ဒီ code က ခေါင်းစဉ်နဲ့ စာကို div မခြုံဘဲ ပြပါတယ်။\n\n<> က တစ်ခုတည်းသော parent လိုအပ်ချက်ကို ဖြေပါတယ်။\n\nHTML ပိုမပိုပါ။",
          ["react"], CH,
          "function Block() {\n  return (\n    <>\n      <h2>Title</h2>\n      <p>Body</p>\n    </>\n  );\n}"),
        i("concept_qa", "State ကို တိုက်ရိုက် ဘာကြောင့် မပြင်သင့်သလဲ?",
          "State ကို တိုက်ရိုက် ပြင်ရင် React က ပြောင်းမှန်း မသိနိုင်ပါ။\n\nsetState နဲ့ object/array အသစ် ပေးရပါတယ်။ UI မပြောင်းတဲ့ bug ဖြစ်တတ်ပါတယ်။\n\n[...list, item] လို ကူးထည့်သင့်ပါတယ်။",
          ["state"], CH),
        i("explain_code", "ဒီ immutable update ကို ရှင်းပြပါ။",
          "ဒီ code က list အသစ်ထည့်ပေမယ့် မူရင်းကို မဖျက်ပါ။\n\n...items က အဟောင်းကို ကူးပါတယ်။ React က ပြောင်းမှန်း သိပါတယ်။\n\nitem အသစ် ပေါ်ပါတယ်။",
          ["state", "array"], CH,
          "setItems([...items, \"mango\"]);"),
        i("concept_qa", "React မှာ className သုံးရတဲ့ အကြောင်းက ဘာလဲ?",
          "class က JavaScript keyword ဖြစ်လို့ JSX မှာ className သုံးပါတယ်။\n\nHTML class နဲ့ အတူတူပဲ ဖြစ်ပါတယ်။ CSS ချိတ်ရာမှာ ဒီနာမည် သုံးပါတယ်။\n\nမှားရေးရင် style မကပ်ပါ။",
          ["css", "react"], CH),
        i("explain_code", "ဒီ style object ကို ရှင်းပြပါ။",
          "ဒီ code က အရောင်နီနဲ့ ပြပါတယ်။\n\nstyle က object ဖြစ်ပြီး camelCase သုံးပါတယ်။ background-color မဟုတ်ဘဲ backgroundColor ဖြစ်ပါတယ်။\n\nစာနီနီ ပေါ်ပါတယ်။",
          ["css", "react"], CH,
          "function Label() {\n  return <span style={{ color: \"red\" }}>Error</span>;\n}"),
        i("debug_explain", "ဒီ missing return ကို ပြင်ပါ။",
          "component က JSX ပြန်မပေးလို့ ဘာမှ မပေါ်ပါ။\n\nreturn ထည့်ရပါတယ်။\n\nမှန်ကန်သော code:\nfunction Title() {\n  return <h1>Home</h1>;\n}",
          ["component"], CH,
          "function Title() {\n  <h1>Home</h1>;\n}"),
        i("concept_qa", "Custom hook ဆိုတာ ဘာလဲ?",
          "Custom hook က use နဲ့စတဲ့ function ထဲမှာ hook တွေ စုထားခြင်း ဖြစ်ပါတယ်။\n\nlogic ကို မျှဝေနိုင်ပါတယ်။ UI နဲ့ ခွဲပါတယ်။\n\nဥပမာ useAuth က user ကို ပြန်ပေးနိုင်ပါတယ်။",
          ["hook"], CH),
        i("explain_code", "ဒီ custom hook ကို ရှင်းပြပါ။",
          "ဒီ hook က online ဟုတ်မဟုတ် မှတ်ပါတယ်။\n\nuseState နဲ့ useEffect ကို စုထားပါတယ်။ component က တစ်ကြောင်းနဲ့ သုံးနိုင်ပါတယ်။\n\ntrue သို့မဟုတ် false ပြန်ပါတယ်။",
          ["hook"], CH,
          "function useOnline() {\n  const [online, setOnline] = useState(true);\n  return online;\n}"),
        i("explain_code", "ဒီ disabled button ကို ရှင်းပြပါ။",
          "ဒီ ခလုတ်က saving ဖြစ်ရင် နှိပ်မရအောင် ပိတ်ပါတယ်။\n\ndisabled={saving} က true ဖြစ်ရင် ပိတ်ပါတယ်။ နှစ်ခါသိမ်းတာ တားပါတယ်။\n\nအလုပ်ပြီးရင် ပြန်ဖွင့်နိုင်ပါတယ်။",
          ["state", "form"], CH,
          "function Save({ saving }) {\n  return <button disabled={saving}>Save</button>;\n}"),
        i("concept_qa", "Re-render ဖြစ်ရင် ဘာဖြစ်သလဲ?",
          "State သို့မဟုတ် props ပြောင်းရင် component ပြန်ဆွဲပါတယ်။\n\nfunction ထဲက ကုဒ် ထပ်မံ အလုပ်လုပ်ပါတယ်။ မလိုအပ်ဘဲ ဖြစ်ရင် နှေးနိုင်ပါတယ်။\n\nမှန်ကန်တဲ့ dependency နဲ့ memo က ကူနိုင်ပါတယ်။",
          ["state", "component"], CH),
        i("explain_code", "ဒီ multiple state ကို ရှင်းပြပါ။",
          "ဒီ form က email နဲ့ password ကို သီးခြား မှတ်ပါတယ်။\n\nstate ခွဲထားလို့ တစ်ခုချင်း ပြင်ရ လွယ်ပါတယ်။ input နှစ်ခုလုံး controlled ဖြစ်ပါတယ်။\n\nlogin ဖောင် အခြေခံ ဖြစ်ပါတယ်။",
          ["state", "form"], CH,
          "const [email, setEmail] = useState(\"\");\nconst [password, setPassword] = useState(\"\");"),
    ]
